CREATE TABLE [dbo].[System_Jobs]
(
	[SystemID] INT NOT NULL , 
    [JobID] INT NOT NULL IDENTITY, 
    [NameVisible] NVARCHAR(50) NULL, 
    [Description] NVARCHAR(200) NULL, 
    [JobType] INT NOT NULL DEFAULT 10, 
    [BpID] INT NOT NULL DEFAULT 0, 
    [UserID] INT NOT NULL DEFAULT 0, 
    [Frequency] INT NOT NULL DEFAULT 0, 
    [RepeatEvery] INT NOT NULL DEFAULT 1, 
    [ValidDays] CHAR(7) NULL, 
    [DayOfMonth] INT NOT NULL DEFAULT 1, 
    [DateBegin] DATE NULL, 
    [DateEnd] DATE NULL, 
    [StartTime] TIME NULL, 
    [NextStart] DATETIME      NULL, 
    [Started] DATETIME NULL, 
    [Terminated] DATETIME NULL, 
    [StatusID] INT NOT NULL DEFAULT 0, 
    [TerminationMessage] NVARCHAR(MAX) NULL, 
    [JobUrl] NVARCHAR(200) NULL, 
    [JobParameter] XML NULL, 
    [JobLanguage] NVARCHAR(10) NULL, 
    [Receiver] NVARCHAR(MAX) NULL,
    [CreatedFrom] NVARCHAR (50) NULL,
    [CreatedOn]   DATETIME      DEFAULT (sysdatetime()) NOT NULL,
    [EditFrom]    NVARCHAR (50) NULL,
    [EditOn]      DATETIME      DEFAULT (sysdatetime()) NOT NULL, 
    PRIMARY KEY ([SystemID], [JobID]), 
)
