CREATE TABLE [dbo].[History_Employees]
(
    [SystemID]         INT            NOT NULL,
    [BpID]             INT            NOT NULL,
    [EmployeeID] INT NOT NULL,
    [ExternalID] NVARCHAR(50) NULL, 
    [AddressID] INT NOT NULL DEFAULT 0, 
    [CompanyID] INT NOT NULL DEFAULT 0, 
    [TradeID] INT NOT NULL DEFAULT 0, 
    [StaffFunction] NVARCHAR(100) NULL, 
    [EmploymentStatusID] INT NOT NULL DEFAULT 0, 
    [MaxHrsPerMonth] INT NOT NULL DEFAULT 0, 
    [AttributeID] INT NOT NULL DEFAULT 0, 
    [ExternalPassID] NVARCHAR(50) NULL, 
    [Description] NVARCHAR (2000) NULL,
    [UserString1] NVARCHAR(50) NULL, 
    [UserString2] NVARCHAR(50) NULL, 
    [UserString3] NVARCHAR(50) NULL, 
    [UserString4] NVARCHAR(50) NULL, 
    [UserBit1] BIT NOT NULL DEFAULT 0, 
    [UserBit2] BIT NOT NULL DEFAULT 0, 
    [UserBit3] BIT NOT NULL DEFAULT 0, 
    [UserBit4] BIT NOT NULL DEFAULT 0, 
    [StatusID] INT NOT NULL DEFAULT 0, 
    [PassCount] INT NOT NULL DEFAULT 0, 
    [AccessRightValidUntil] DATETIME NULL, 
    [CreatedFrom]      NVARCHAR (50)  NULL,
    [CreatedOn]        DATETIME       DEFAULT (sysdatetime()) NOT NULL,
    [EditFrom]         NVARCHAR (50)  NOT NULL,
    [EditOn]           DATETIME       DEFAULT (sysdatetime()) NOT NULL, 
    [ReleaseCFrom] NVARCHAR(50) NULL, 
    [ReleaseCOn] DATETIME NULL , 
    [ReleaseBFrom] NVARCHAR(50) NULL, 
    [ReleaseBOn] DATETIME NULL , 
    [LockedFrom] NVARCHAR(50) NULL, 
    [LockedOn] DATETIME NULL  , 
    CONSTRAINT [PK_History_Employees] PRIMARY KEY ([SystemID], [BpID], [EmployeeID], [EditOn]), 
)
