<%@ Page Title="<%$ Resources:Resource, lblEmploymentStatus %>" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="EmploymentStatus.aspx.cs" Inherits="InSite.App.Views.Configuration.EmploymentStatus" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeaderContent" runat="server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="BodyContent" runat="server">
    <telerik:RadPersistenceManagerProxy ID="RadPersistenceManagerProxy1" runat="server">
        <PersistenceSettings>
            <telerik:PersistenceSetting ControlID="RadGrid1" />
        </PersistenceSettings>
    </telerik:RadPersistenceManagerProxy>

    <telerik:RadAjaxManagerProxy ID="AjaxManagerProxy1" runat="server">
        <AjaxSettings>
            <telerik:AjaxSetting AjaxControlID="RadGrid1">
                <UpdatedControls>
                    <telerik:AjaxUpdatedControl ControlID="RadGrid1" LoadingPanelID="RadAjaxLoadingPanelMaster" />
                </UpdatedControls>
            </telerik:AjaxSetting>
        </AjaxSettings>
    </telerik:RadAjaxManagerProxy>

    <div>
        <telerik:RadGrid ID="RadGrid1" runat="server" DataSourceID="SqlDataSource_EmploymentStatus" AllowPaging="True" AllowSorting="True" CellSpacing="0"
                         GridLines="None" AllowAutomaticDeletes="true" AllowAutomaticInserts="true" AllowAutomaticUpdates="true" CssClass="MainGrid" EnableHierarchyExpandAll="true" 
                         EnableGroupsExpandAll="true"
                         OnItemCommand="RadGrid1_ItemCommand" OnItemCreated="RadGrid1_ItemCreated" OnGroupsChanging="RadGrid1_GroupsChanging" OnItemEvent="RadGrid1_ItemEvent"
                         OnItemDeleted="RadGrid1_ItemDeleted" OnItemInserted="RadGrid1_ItemInserted" OnItemUpdated="RadGrid1_ItemUpdated" OnPreRender="RadGrid1_PreRender">

            <ExportSettings ExportOnlyData="true" IgnorePaging="true">
                <Pdf PaperSize="A4">
                </Pdf>
                <Excel Format="ExcelML" />
            </ExportSettings>

            <ClientSettings AllowColumnsReorder="True" AllowDragToGroup="True" EnableRowHoverStyle="True" EnablePostBackOnRowClick="false">
                <Resizing AllowColumnResize="true"></Resizing>
                <Selecting AllowRowSelect="True" />
                <ClientEvents OnRowClick="OnRowClick" OnGridCreated="OnGridCreated" OnKeyPress="GridKeyPress" />
            </ClientSettings>

        <SortingSettings SortedBackColor="Transparent" />

            <MasterTableView runat="server" DataSourceID="SqlDataSource_EmploymentStatus" DataKeyNames="SystemID,BpID,EmploymentStatusID" AutoGenerateColumns="False" CommandItemDisplay="Top"
                             EditMode="PopUp" Name="EmploymentStatus" ShowHeader="true" CssClass="MasterClass">

                <PagerStyle Mode="NextPrevAndNumeric" AlwaysVisible="true" />

            <SortExpressions>
                <telerik:GridSortExpression FieldName="NameVisible" SortOrder="Ascending"></telerik:GridSortExpression>
            </SortExpressions>

                <CommandItemSettings ShowRefreshButton="true" ShowAddNewRecordButton="true" ShowExportToCsvButton="False" ShowExportToExcelButton="True" ShowExportToPdfButton="False"
                                     AddNewRecordText="<%$ Resources:Resource, lblActionNew %>" RefreshText="<%$ Resources:Resource, lblActionRefresh %>" />

                <EditFormSettings EditFormType="AutoGenerated" CaptionDataField="NameVisible" CaptionFormatString="{0}">
                    <PopUpSettings Modal="true" ShowCaptionInEditForm="false" ScrollBars="Auto" />
                    <EditColumn ButtonType="ImageButton" UniqueName="EditColumn1" CancelText="<%$ Resources:Resource, lblActionCancel %>"
                                EditText="<%$ Resources:Resource, lblActionEdit %>" UpdateText="<%$ Resources:Resource, lblActionUpdate %>" />
                    <FormTableStyle CellPadding="3" CellSpacing="3" />
                </EditFormSettings>

                <Columns>
                <telerik:GridEditCommandColumn ButtonType="ImageButton" UniqueName="EditCommandColumn" CancelText="<%$ Resources:Resource, lblActionCancel %>" EditText="<%$ Resources:Resource, lblActionEdit %>"
                                               UpdateText="<%$ Resources:Resource, lblActionUpdate %>" Reorderable="false" Resizable="false">
                    <ItemStyle BackColor="Control" Width="30px" />
                    <HeaderStyle Width="30px" />
                </telerik:GridEditCommandColumn>

                    <telerik:GridTemplateColumn DataField="EmploymentStatusID" Visible="false" InsertVisiblityMode="AlwaysHidden" DataType="System.Int32"
                                                FilterControlAltText="Filter EmploymentStatusID column" HeaderText="<%$ Resources:Resource, lblID %>"
                                                SortExpression="EmploymentStatusID" UniqueName="EmploymentStatusID" GroupByExpression="EmploymentStatusID EmploymentStatusID GROUP BY EmploymentStatusID">
                        <EditItemTemplate>
                            <asp:Label runat="server" ID="LabelEmploymentStatusID" Text='<%# Eval("EmploymentStatusID") %>'></asp:Label>
                        </EditItemTemplate>
                        <InsertItemTemplate>
                        </InsertItemTemplate>
                        <ItemTemplate>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="NameVisible" HeaderText="<%$ Resources:Resource, lblNameVisible %>" SortExpression="NameVisible" UniqueName="NameVisible"
                                                GroupByExpression="NameVisible NameVisible GROUP BY NameVisible">
                        <EditItemTemplate>
                            <telerik:RadTextBox runat="server" ID="NameVisible" Text='<%# Bind("NameVisible") %>'></telerik:RadTextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="NameVisible" Text='<%# Eval("NameVisible") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="DescriptionShort" FilterControlAltText="Filter DescriptionShort column" HeaderText="<%$ Resources:Resource, lblDescriptionShort %>"
                                                SortExpression="DescriptionShort" UniqueName="DescriptionShort" GroupByExpression="DescriptionShort DescriptionShort GROUP BY DescriptionShort">
                        <EditItemTemplate>
                            <telerik:RadTextBox runat="server" ID="DescriptionShort" Text='<%# Bind("DescriptionShort") %>' Width="300px"></telerik:RadTextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="LabelDescriptionShort" Text='<%# Eval("DescriptionShort") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridCheckBoxColumn DataField="MWObligate" DataType="System.Boolean" FilterControlAltText="Filter MWObligate column" HeaderText="<%$ Resources:Resource, lblMWObligate %>"
                                                SortExpression="MWObligate" UniqueName="MWObligate">
                    </telerik:GridCheckBoxColumn>

                    <telerik:GridTemplateColumn DataField="MWFrom" DataType="System.DateTime" FilterControlAltText="Filter MWFrom column" HeaderText="<%$ Resources:Resource, lblMWFrom %>"
                                                SortExpression="MWFrom" UniqueName="MWFrom" GroupByExpression="MWFrom MWFrom GROUP BY MWFrom">
                        <EditItemTemplate>
                            <telerik:RadDatePicker ID="RadDatePicker1" runat="server" DbSelectedDate='<%# Bind("MWFrom") %>' MinDate="2010/1/1" MaxDate="2100/1/1" EnableShadows="true"
                                                   ShowPopupOnFocus="true">
                                <Calendar runat="server">
                                    <FastNavigationSettings CancelButtonCaption="<%$ Resources:Resource, lblActionCancel %>" OkButtonCaption="<%$ Resources:Resource, lblOK %>"
                                                            TodayButtonCaption="<%$ Resources:Resource, lblToday %>">
                                    </FastNavigationSettings>
                                </Calendar>
                            </telerik:RadDatePicker>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="LabelMWFrom" Text='<%# Eval("MWFrom", "{0:D}") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="MWTo" DataType="System.DateTime" FilterControlAltText="Filter MWTo column" HeaderText="<%$ Resources:Resource, lblMWTo %>"
                                                SortExpression="MWTo" UniqueName="MWTo" GroupByExpression="MWTo MWTo GROUP BY MWTo">
                        <EditItemTemplate>
                            <telerik:RadDatePicker ID="RadDatePicker2" runat="server" DbSelectedDate='<%# Bind("MWTo") %>' MinDate="2010/1/1" MaxDate="2100/1/1" EnableShadows="true"
                                                   ShowPopupOnFocus="true">
                                <Calendar runat="server">
                                    <FastNavigationSettings CancelButtonCaption="<%$ Resources:Resource, lblActionCancel %>" OkButtonCaption="<%$ Resources:Resource, lblOK %>"
                                                            TodayButtonCaption="<%$ Resources:Resource, lblToday %>">
                                    </FastNavigationSettings>
                                </Calendar>
                            </telerik:RadDatePicker>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="LabelMWTo" Text='<%# Eval("MWTo", "{0:D}") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="CreatedFrom" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter CreatedFrom column" HeaderText="<%$ Resources:Resource, lblCreatedFrom %>" SortExpression="CreatedFrom" UniqueName="CreatedFrom" Visible="False">
                        <ItemTemplate>
                            <asp:Label ID="CreatedFromLabel" runat="server" Text='<%# Eval("CreatedFrom") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="CreatedOn" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter CreatedOn column" HeaderText="<%$ Resources:Resource, lblCreatedOn %>" SortExpression="CreatedOn" UniqueName="CreatedOn" Visible="False">
                        <ItemTemplate>
                            <asp:Label ID="CreatedOnLabel" runat="server" Text='<%# Eval("CreatedOn") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="EditFrom" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter EditFrom column" HeaderText="<%$ Resources:Resource, lblEditFrom %>" SortExpression="EditFrom" UniqueName="EditFrom" Visible="False">
                        <ItemTemplate>
                            <asp:Label ID="EditFromLabel" runat="server" Text='<%# Eval("EditFrom") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="EditOn" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter EditOn column" HeaderText="<%$ Resources:Resource, lblEditOn %>" SortExpression="EditOn" UniqueName="EditOn" Visible="False">
                        <ItemTemplate>
                            <asp:Label ID="EditOnLabel" runat="server" Text='<%# Eval("EditOn") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                <telerik:GridButtonColumn UniqueName="deleteColumn" Visible="true" ConfirmText="<%$ Resources:Resource, qstDeleteRow %>" Text="<%$ Resources:Resource, lblActionDelete %>" 
                                          ConfirmDialogType="RadWindow"
                                          ConfirmTitle="<%$ Resources:Resource, lblActionDelete %>" ButtonType="ImageButton" CommandName="Delete" HeaderStyle-Width="30px" ItemStyle-Width="30px">
                    <ItemStyle BackColor="Control" />
                </telerik:GridButtonColumn>
                </Columns>

                <NestedViewTemplate>
                    <asp:Panel ID="NestedViewPanel" runat="server">
                        <div>
                            <fieldset style="padding: 10px;">
                                <legend style="padding: 5px;">
                                    <b><%= Resources.Resource.lblDetailsFor %> <%#Eval("NameVisible") %></b>
                                </legend>
                                <table>
                                    <tr>
                                        <td><%= Resources.Resource.lblID %>: </td>
                                        <td>
                                            <asp:Label Text='<%#Eval("EmploymentStatusID") %>' runat="server"></asp:Label>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td><%= Resources.Resource.lblCostLocationNameVisible %>: </td>
                                        <td>
                                            <asp:Label Text='<%#Eval("NameVisible") %>' runat="server"></asp:Label>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td><%= Resources.Resource.lblDescriptionShort %>: </td>
                                        <td>
                                            <asp:Label Text='<%#Eval("DescriptionShort") %>' runat="server"></asp:Label>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td><%= Resources.Resource.lblMWObligate %>: </td>
                                        <td>
                                            <asp:CheckBox Checked='<%#Eval("MWObligate") %>' runat="server" />
                                        </td>
                                    </tr>
                                    <tr>
                                        <td><%= Resources.Resource.lblMWFrom %>: </td>
                                        <td>
                                            <asp:Label Text='<%#Eval("MWFrom", "{0:D}") %>' runat="server"></asp:Label>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td><%= Resources.Resource.lblMWTo %>: </td>
                                        <td>
                                            <asp:Label Text='<%#Eval("MWTo", "{0:D}") %>' runat="server"></asp:Label>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td><%= Resources.Resource.lblCreatedFrom %>: </td>
                                        <td>
                                            <asp:Label Text='<%#Eval("CreatedFrom") %>' runat="server"></asp:Label>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td><%= Resources.Resource.lblCreatedOn %>: </td>
                                        <td>
                                            <asp:Label Text='<%#Eval("CreatedOn") %>' runat="server"></asp:Label>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td><%= Resources.Resource.lblEditFrom %>: </td>
                                        <td>
                                            <asp:Label Text='<%#Eval("EditFrom") %>' runat="server"></asp:Label>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td><%= Resources.Resource.lblEditOn %>: </td>
                                        <td>
                                            <asp:Label Text='<%#Eval("EditOn") %>' runat="server"></asp:Label>
                                        </td>
                                    </tr>
                                </table>
                            </fieldset>
                        </div>
                    </asp:Panel>
                </NestedViewTemplate>

            </MasterTableView>
        </telerik:RadGrid>
    </div>

    <asp:SqlDataSource ID="SqlDataSource_EmploymentStatus" runat="server" ConnectionString="<%$ ConnectionStrings:Insite_Dev_ConnectionString %>" OnInserted="SqlDataSource_Inserted"
                       OldValuesParameterFormatString="original_{0}"
                       SelectCommand="SELECT * FROM [Master_EmploymentStatus] WHERE (([SystemID] = @SystemID) AND ([BpID] = @BpID)) ORDER BY [NameVisible]"
                       InsertCommand="INSERT INTO Master_EmploymentStatus (SystemID, BpID, NameVisible, DescriptionShort, MWObligate, MWFrom, MWTo, CreatedFrom, CreatedOn, EditFrom, EditOn) VALUES (@SystemID, @BpID, @NameVisible, @DescriptionShort, @MWObligate, @MWFrom, @MWTo, @UserName, SYSDATETIME(), @UserName, SYSDATETIME()) 
                       SELECT @ReturnValue = SCOPE_IDENTITY()"
                       UpdateCommand="INSERT INTO History_EmploymentStatus SELECT * FROM Master_EmploymentStatus WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND EmploymentStatusID = @original_EmploymentStatusID; 
                       UPDATE Master_EmploymentStatus SET NameVisible = @NameVisible, DescriptionShort = @DescriptionShort, MWObligate = @MWObligate, MWFrom = @MWFrom, MWTo = @MWTo, EditFrom = @UserName, EditOn = SYSDATETIME() WHERE SystemID = @original_SystemID AND BpID = @original_BpID AND EmploymentStatusID = @original_EmploymentStatusID"
                       DeleteCommand="INSERT INTO History_EmploymentStatus SELECT * FROM Master_EmploymentStatus WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND EmploymentStatusID = @original_EmploymentStatusID; 
                       DELETE FROM Master_EmploymentStatus WHERE SystemID = @original_SystemID AND BpID = @original_BpID AND EmploymentStatusID = @original_EmploymentStatusID">
        <SelectParameters>
            <asp:SessionParameter DefaultValue="0" Name="SystemID" SessionField="SystemID" Type="Int32" />
            <asp:SessionParameter DefaultValue="0" Name="BpID" SessionField="BpID" Type="Int32" />
        </SelectParameters>
        <InsertParameters>
            <asp:SessionParameter DefaultValue="0" Name="SystemID" SessionField="SystemID" Type="Int32" />
            <asp:SessionParameter DefaultValue="0" Name="BpID" SessionField="BpID" Type="Int32" />
            <asp:Parameter Name="NameVisible" />
            <asp:Parameter Name="DescriptionShort" />
            <asp:Parameter Name="MWObligate" />
            <asp:Parameter Name="MWFrom" DbType="DateTime" />
            <asp:Parameter Name="MWTo" DbType="DateTime" />
            <asp:SessionParameter DefaultValue="" Name="UserName" SessionField="LoginName" Type="String" />
            <asp:Parameter Direction="Output" Name="ReturnValue" Type="Int32" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="original_SystemID" Type="Int32" />
            <asp:Parameter Name="original_BpID" Type="Int32" />
            <asp:Parameter Name="original_EmploymentStatusID" Type="Int32" />
            <asp:Parameter Name="NameVisible" />
            <asp:Parameter Name="DescriptionShort" />
            <asp:Parameter Name="MWObligate" />
            <asp:Parameter Name="MWFrom" DbType="DateTime" />
            <asp:Parameter Name="MWTo" DbType="DateTime" />
            <asp:SessionParameter DefaultValue="" Name="UserName" SessionField="LoginName" Type="String" />
        </UpdateParameters>
        <DeleteParameters>
            <asp:Parameter Name="original_SystemID" Type="Int32" />
            <asp:Parameter Name="original_BpID" Type="Int32" />
            <asp:Parameter Name="original_EmploymentStatusID" Type="Int32" />
        </DeleteParameters>
    </asp:SqlDataSource>
</asp:Content>
