<%@ Page Title="<%$ Resources:Resource, lblRolesRights %>" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="RolesRights.aspx.cs" Inherits="InSite.App.Views.Configuration.RolesRights" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeaderContent" runat="server">
    <telerik:RadScriptBlock ID="RadScriptBlock1" runat="server">
        <script type="text/javascript">
            function OnSingleRowClick(sender, args) {
                var _args = "Expand|" + args.get_tableView().get_id() + "|" + args.get_itemIndexHierarchical();
                sender.get_masterTableView().fireCommand("RowClick", _args);
            }
        </script>
    </telerik:RadScriptBlock>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="BodyContent" runat="server">
    <telerik:RadAjaxManagerProxy ID="AjaxManagerProxy1" runat="server">
        <AjaxSettings>
            <telerik:AjaxSetting AjaxControlID="RadGrid1">
                <UpdatedControls>
                    <telerik:AjaxUpdatedControl ControlID="RadGrid1" LoadingPanelID="RadAjaxLoadingPanelMaster" />
                </UpdatedControls>
            </telerik:AjaxSetting>
        </AjaxSettings>
    </telerik:RadAjaxManagerProxy>

    <telerik:RadPersistenceManagerProxy ID="RadPersistenceManagerProxy1" runat="server">
        <PersistenceSettings>
            <telerik:PersistenceSetting ControlID="RadGrid1" />
        </PersistenceSettings>
    </telerik:RadPersistenceManagerProxy>

    <telerik:RadInputManager ID="RadInputManager1" runat="server">
        <telerik:TextBoxSetting BehaviorID="TextBoxBehavior1" InitializeOnClient="false">
        </telerik:TextBoxSetting>
        <telerik:NumericTextBoxSetting BehaviorID="NumericBehavior1" InitializeOnClient="false"
                                       Type="Number" DecimalDigits="0">
        </telerik:NumericTextBoxSetting>
    </telerik:RadInputManager>

    <%-- Roles Grid --%>
    <telerik:RadGrid ID="RadGrid1" runat="server" AllowAutomaticUpdates="True" DataSourceID="SqlDataSource_Roles" AllowPaging="true" AllowSorting="true"
        CssClass="MainGrid" AllowAutomaticInserts="true" EnableHierarchyExpandAll="true" AllowAutomaticDeletes="true"
        OnItemInserted="RadGrid1_ItemInserted" OnPreRender="RadGrid1_PreRender" OnItemDataBound="RadGrid1_ItemDataBound"
        OnItemDeleted="RadGrid1_ItemDeleted" OnItemUpdated="RadGrid1_ItemUpdated" OnItemCommand="RadGrid1_ItemCommand"
        OnItemCreated="RadGrid1_ItemCreated" OnDetailTableDataBind="RadGrid1_DetailTableDataBind" OnGroupsChanging="RadGrid1_GroupsChanging">

        <ExportSettings ExportOnlyData="True" IgnorePaging="True">
            <Pdf PaperSize="A4">
            </Pdf>
            <Excel Format="ExcelML" />
        </ExportSettings>

        <ClientSettings AllowColumnsReorder="True" AllowDragToGroup="True" EnableRowHoverStyle="True" EnablePostBackOnRowClick="false" AllowGroupExpandCollapse="true" AllowExpandCollapse="true">
            <Resizing AllowColumnResize="true" AllowResizeToFit="true" EnableRealTimeResize="true"></Resizing>
            <Selecting AllowRowSelect="True" />
            <ClientEvents OnRowClick="OnRowClick" OnKeyPress="GridKeyPress" />
        </ClientSettings>

        <%-- Roles Master --%>
        <SortingSettings SortedBackColor="Transparent" />

        <MasterTableView Name="Roles" EnableHierarchyExpandAll="true" HierarchyLoadMode="Conditional" CssClass="MasterClass" AutoGenerateColumns="False"
                         DataKeyNames="SystemID,BpID,RoleID" EditMode="PopUp"
                         DataSourceID="SqlDataSource_Roles" CommandItemDisplay="Top" EnableHeaderContextMenu="true" ShowHeader="true" Caption="<%$ Resources:Resource, lblRoles %>">

            <PagerStyle Mode="NextPrevAndNumeric" AlwaysVisible="true" />

            <SortExpressions>
                <telerik:GridSortExpression FieldName="NameVisible" SortOrder="Ascending"></telerik:GridSortExpression>
            </SortExpressions>

            <EditFormSettings EditFormType="AutoGenerated" CaptionDataField="NameVisible" CaptionFormatString="{0}">
                <PopUpSettings Modal="true" ShowCaptionInEditForm="false" ScrollBars="Auto" />
                <EditColumn ButtonType="ImageButton" UniqueName="EditColumn1" CancelText="<%$ Resources:Resource, lblActionCancel %>"
                            EditText="<%$ Resources:Resource, lblActionEdit %>" UpdateText="<%$ Resources:Resource, lblActionUpdate %>" />
                <FormTableStyle CellPadding="3" CellSpacing="3" />
            </EditFormSettings>

            <CommandItemSettings ShowRefreshButton="true" ShowAddNewRecordButton="true" ShowExportToCsvButton="False" ShowExportToExcelButton="True" ShowExportToPdfButton="False"
                                 AddNewRecordText="<%$ Resources:Resource, lblActionNew %>" RefreshText="<%$ Resources:Resource, lblActionRefresh %>" />

            <%-- Roles Dialogs --%>
            <DetailTables>

                <%-- Dialogs GridTableView --%>
                <telerik:GridTableView Name="Dialogs" DataSourceID="SqlDataSource_Dialogs" EnableHierarchyExpandAll="true" AllowPaging="false"
                                       CssClass="MasterClass" AutoGenerateColumns="False" ShowHeader="true" Caption="<%$ Resources:Resource, lblDialogs %>"
                                       DataKeyNames="SystemID,BpID,RoleID,DialogID" EditMode="PopUp" CommandItemDisplay="None">

                    <ParentTableRelation>
                        <telerik:GridRelationFields DetailKeyField="SystemID" MasterKeyField="SystemID"></telerik:GridRelationFields>
                        <telerik:GridRelationFields DetailKeyField="BpID" MasterKeyField="BpID"></telerik:GridRelationFields>
                        <telerik:GridRelationFields DetailKeyField="RoleID" MasterKeyField="RoleID"></telerik:GridRelationFields>
                    </ParentTableRelation>

                    <PagerStyle Mode="NextPrevAndNumeric" AlwaysVisible="true" />

                    <%--                    <SortExpressions>
                    <telerik:GridSortExpression FieldName="ResourceID" SortOrder="Ascending"></telerik:GridSortExpression>
                    </SortExpressions>--%>

                    <EditFormSettings EditFormType="AutoGenerated" CaptionDataField="NameVisible" CaptionFormatString="{0}">
                        <PopUpSettings Modal="true" ShowCaptionInEditForm="false" ScrollBars="Auto" />
                        <EditColumn ButtonType="ImageButton" UniqueName="EditColumn2" CancelText="<%$ Resources:Resource, lblActionCancel %>"
                                    EditText="<%$ Resources:Resource, lblActionEdit %>" UpdateText="<%$ Resources:Resource, lblActionUpdate %>" />
                        <FormTableStyle CellPadding="3" CellSpacing="3" />
                    </EditFormSettings>

                    <%-- Dialog Actions --%>
                    <DetailTables>

                        <%-- Actions GridTableView --%>
                        <telerik:GridTableView Name="Actions" DataSourceID="SqlDataSource_Actions" EnableHierarchyExpandAll="true" AllowPaging="false"
                                               CssClass="MasterClass" AutoGenerateColumns="False" ShowHeader="true" Caption="<%$ Resources:Resource, lblActions %>"
                                               DataKeyNames="SystemID,BpID,RoleID,DialogID,ActionID" EditMode="PopUp"
                                               CommandItemDisplay="None">

                            <ParentTableRelation>
                                <telerik:GridRelationFields DetailKeyField="SystemID" MasterKeyField="SystemID"></telerik:GridRelationFields>
                                <telerik:GridRelationFields DetailKeyField="BpID" MasterKeyField="BpID"></telerik:GridRelationFields>
                                <telerik:GridRelationFields DetailKeyField="RoleID" MasterKeyField="RoleID"></telerik:GridRelationFields>
                                <telerik:GridRelationFields DetailKeyField="DialogID" MasterKeyField="DialogID"></telerik:GridRelationFields>
                            </ParentTableRelation>

                            <PagerStyle Mode="NextPrevAndNumeric" AlwaysVisible="true" />

                            <SortExpressions>
                                <telerik:GridSortExpression FieldName="ResourceID" SortOrder="Ascending"></telerik:GridSortExpression>
                            </SortExpressions>

                            <EditFormSettings EditFormType="AutoGenerated" CaptionDataField="NameVisible" CaptionFormatString="{0}">
                                <PopUpSettings Modal="true" ShowCaptionInEditForm="false" ScrollBars="Auto" />
                                <EditColumn ButtonType="ImageButton" UniqueName="EditColumn3" CancelText="<%$ Resources:Resource, lblActionCancel %>"
                                            EditText="<%$ Resources:Resource, lblActionEdit %>" UpdateText="<%$ Resources:Resource, lblActionUpdate %>" />
                                <FormTableStyle CellPadding="3" CellSpacing="3" />
                            </EditFormSettings>

                            <%-- Action Fields --%>
                            <DetailTables>

                                <%-- Fields GridTableView --%>
                                <telerik:GridTableView Name="Fields" DataSourceID="SqlDataSource_Fields" AllowPaging="false" 
                                                       EnableHierarchyExpandAll="true" CssClass="MasterClass" AutoGenerateColumns="False"
                                                       DataKeyNames="SystemID,BpID,RoleID,DialogID,ActionID,FieldID" ShowHeader="true" Caption="<%$ Resources:Resource, lblFields %>"
                                                       CommandItemDisplay="None" EnableHeaderContextMenu="true" EditMode="PopUp">

                                    <ParentTableRelation>
                                        <telerik:GridRelationFields DetailKeyField="SystemID" MasterKeyField="SystemID"></telerik:GridRelationFields>
                                        <telerik:GridRelationFields DetailKeyField="BpID" MasterKeyField="BpID"></telerik:GridRelationFields>
                                        <telerik:GridRelationFields DetailKeyField="RoleID" MasterKeyField="RoleID"></telerik:GridRelationFields>
                                        <telerik:GridRelationFields DetailKeyField="DialogID" MasterKeyField="DialogID"></telerik:GridRelationFields>
                                        <telerik:GridRelationFields DetailKeyField="ActionID" MasterKeyField="ActionID"></telerik:GridRelationFields>
                                    </ParentTableRelation>

                                    <PagerStyle Mode="NextPrevAndNumeric" AlwaysVisible="true" />

                                    <SortExpressions>
                                        <telerik:GridSortExpression FieldName="ResourceID" SortOrder="Ascending"></telerik:GridSortExpression>
                                    </SortExpressions>

                                    <EditFormSettings EditFormType="AutoGenerated" CaptionDataField="InternalName" CaptionFormatString="{0}">
                                        <PopUpSettings Modal="true" ShowCaptionInEditForm="false" ScrollBars="Auto" />
                                        <EditColumn ButtonType="ImageButton" UniqueName="EditColumn4" CancelText="<%$ Resources:Resource, lblActionCancel %>"
                                                    EditText="<%$ Resources:Resource, lblActionEdit %>" UpdateText="<%$ Resources:Resource, lblActionUpdate %>" />
                                        <FormTableStyle CellPadding="3" CellSpacing="3" />
                                    </EditFormSettings>

                                    <%-- Field Details --%>
                                    <NestedViewTemplate>
                                        <fieldset style="padding: 10px; width: 500px; margin-left: 10px; margin-bottom: 10px;">
                                            <legend style="padding: 5px; background-color: transparent;">
                                                <b><%= Resources.Resource.lblDetailsFor%> <%# GetResource(Eval("ResourceID").ToString())%></b>
                                            </legend>
                                            <table style="width: 100%;">
                                                <tr>
                                                    <td><%= Resources.Resource.lblID%>: </td>
                                                    <td>
                                                        <asp:Label ID="Label1" Text='<%#Eval("FieldID")%>' runat="server"></asp:Label>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td><%= Resources.Resource.lblNameVisible%>: </td>
                                                    <td>
                                                        <asp:HiddenField runat="server" ID="ResourceID" Value='<%#Eval("ResourceID")%>' />
                                                        <asp:Label ID="NameVisible" Text="" runat="server"></asp:Label>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td><%= Resources.Resource.lblInternalName%>: </td>
                                                    <td>
                                                        <asp:Label ID="Label2" Text='<%#Eval("InternalName")%>' runat="server"></asp:Label>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td><%= Resources.Resource.lblVisible%>: </td>
                                                    <td>
                                                        <asp:CheckBox ID="CheckBox1" Checked='<%#Eval("IsVisible")%>' runat="server" />
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td><%= Resources.Resource.lblEditable%>: </td>
                                                    <td>
                                                        <asp:CheckBox ID="CheckBox2" Checked='<%#Eval("IsEditable")%>' runat="server" />
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td><%= Resources.Resource.lblMandatory%>: </td>
                                                    <td>
                                                        <asp:CheckBox ID="CheckBox3" Checked='<%#Eval("IsMandatory")%>' runat="server" />
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td><%= Resources.Resource.lblDefault%>: </td>
                                                    <td>
                                                        <asp:Label ID="Label3" Text='<%#Eval("DefaultValue")%>' runat="server"></asp:Label>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td><%= Resources.Resource.lblCreatedFrom%>: </td>
                                                    <td>
                                                        <asp:Label ID="Label4" Text='<%#Eval("CreatedFrom")%>' runat="server"></asp:Label>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td><%= Resources.Resource.lblCreatedOn%>: </td>
                                                    <td>
                                                        <asp:Label ID="Label5" Text='<%#Eval("CreatedOn")%>' runat="server"></asp:Label>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td><%= Resources.Resource.lblEditFrom%>: </td>
                                                    <td>
                                                        <asp:Label ID="Label6" Text='<%#Eval("EditFrom")%>' runat="server"></asp:Label>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td><%= Resources.Resource.lblEditOn%>: </td>
                                                    <td>
                                                        <asp:Label ID="Label7" Text='<%#Eval("EditOn")%>' runat="server"></asp:Label>
                                                    </td>
                                                </tr>
                                            </table>
                                        </fieldset>
                                    </NestedViewTemplate>

                                    <%-- Fields Columns --%>
                                    <Columns>
                                        <telerik:GridEditCommandColumn ButtonType="ImageButton" UniqueName="EditCommandColumn4" CancelText="<%$ Resources:Resource, lblActionCancel %>" EditText="<%$ Resources:Resource, lblActionEdit %>"
                                                                       UpdateText="<%$ Resources:Resource, lblActionUpdate %>" Reorderable="false" Resizable="false">
                                            <ItemStyle BackColor="Control" Width="30px" />
                                            <HeaderStyle Width="30px" />
                                        </telerik:GridEditCommandColumn>

                                        <telerik:GridTemplateColumn DataField="FieldID" DataType="System.Int32" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter FieldID column" 
                                                                    HeaderText="<%$ Resources:Resource, lblID %>" SortExpression="FieldID" UniqueName="FieldID" Visible="False">
                                            <EditItemTemplate>
                                                <asp:Label ID="FieldIDLabel" runat="server" Text='<%# Eval("FieldID")%>'></asp:Label>
                                            </EditItemTemplate>
                                        </telerik:GridTemplateColumn>

                                        <telerik:GridTemplateColumn DataField="ResourceID" HeaderText="<%$ Resources:Resource, lblNameVisible %>" SortExpression="ResourceID" UniqueName="ResourceID"
                                                                    GroupByExpression="ResourceID ResourceID GROUP BY ResourceID">
                                            <EditItemTemplate>
                                                <asp:Label runat="server" ID="NameVisible" Text=""></asp:Label>
                                            </EditItemTemplate>
                                            <ItemTemplate>
                                                <asp:Label runat="server" ID="NameVisible" Text=""></asp:Label>
                                            </ItemTemplate>
                                        </telerik:GridTemplateColumn>

                                        <telerik:GridTemplateColumn DataField="InternalName" HeaderText="<%$ Resources:Resource, lblInternalName %>" SortExpression="InternalName" UniqueName="InternalName"
                                                                    GroupByExpression="InternalName InternalName GROUP BY InternalName">
                                            <EditItemTemplate>
                                                <asp:Label runat="server" ID="InternalName" Text='<%# Bind("InternalName")%>'></asp:Label>
                                            </EditItemTemplate>
                                            <ItemTemplate>
                                                <asp:Label runat="server" ID="InternalName" Text='<%# Bind("InternalName")%>'></asp:Label>
                                            </ItemTemplate>
                                        </telerik:GridTemplateColumn>

                                        <telerik:GridCheckBoxColumn DataField="IsVisible" DataType="System.Boolean" FilterControlAltText="Filter IsVisible column" HeaderText="<%$ Resources:Resource, lblVisible %>" SortExpression="IsVisible" UniqueName="IsVisible">
                                        </telerik:GridCheckBoxColumn>

                                        <telerik:GridCheckBoxColumn DataField="IsEditable" DataType="System.Boolean" FilterControlAltText="Filter IsEditable column" HeaderText="<%$ Resources:Resource, lblEditable %>" SortExpression="IsEditable" UniqueName="IsEditable">
                                        </telerik:GridCheckBoxColumn>

                                        <telerik:GridCheckBoxColumn DataField="IsMandatory" DataType="System.Boolean" FilterControlAltText="Filter IsMandatory column" HeaderText="<%$ Resources:Resource, lblMandatory %>" SortExpression="IsMandatory" UniqueName="IsMandatory">
                                        </telerik:GridCheckBoxColumn>

                                        <telerik:GridTemplateColumn DataField="DefaultValue" FilterControlAltText="Filter DefaultValue column" HeaderText="<%$ Resources:Resource, lblDefault %>"
                                                                    SortExpression="DefaultValue" UniqueName="DefaultValue" GroupByExpression="DefaultValue DefaultValue GROUP BY DefaultValue">
                                            <EditItemTemplate>
                                                <telerik:RadTextBox runat="server" ID="DefaultValue" Text='<%# Bind("DefaultValue")%>'></telerik:RadTextBox>
                                            </EditItemTemplate>
                                            <ItemTemplate>
                                                <asp:Label runat="server" ID="DefaultValue" Text='<%# Eval("DefaultValue")%>'></asp:Label>
                                            </ItemTemplate>
                                        </telerik:GridTemplateColumn>

                                        <telerik:GridTemplateColumn DataField="CreatedFrom" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter CreatedFrom column" HeaderText="<%$ Resources:Resource, lblCreatedFrom %>" SortExpression="CreatedFrom" UniqueName="CreatedFrom" Visible="False">
                                            <ItemTemplate>
                                                <asp:Label ID="CreatedFromLabel" runat="server" Text='<%# Eval("CreatedFrom")%>'></asp:Label>
                                            </ItemTemplate>
                                        </telerik:GridTemplateColumn>

                                        <telerik:GridTemplateColumn DataField="CreatedOn" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter CreatedOn column" HeaderText="<%$ Resources:Resource, lblCreatedOn %>" SortExpression="CreatedOn" UniqueName="CreatedOn" Visible="False">
                                            <ItemTemplate>
                                                <asp:Label ID="CreatedOnLabel" runat="server" Text='<%# Eval("CreatedOn")%>'></asp:Label>
                                            </ItemTemplate>
                                        </telerik:GridTemplateColumn>

                                        <telerik:GridTemplateColumn DataField="EditFrom" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter EditFrom column" HeaderText="<%$ Resources:Resource, lblEditFrom %>" SortExpression="EditFrom" UniqueName="EditFrom" Visible="False">
                                            <ItemTemplate>
                                                <asp:Label ID="EditFromLabel" runat="server" Text='<%# Eval("EditFrom")%>'></asp:Label>
                                            </ItemTemplate>
                                        </telerik:GridTemplateColumn>

                                        <telerik:GridTemplateColumn DataField="EditOn" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter EditOn column" HeaderText="<%$ Resources:Resource, lblEditOn %>" SortExpression="EditOn" UniqueName="EditOn" Visible="False">
                                            <ItemTemplate>
                                                <asp:Label ID="EditOnLabel" runat="server" Text='<%# Eval("EditOn")%>'></asp:Label>
                                            </ItemTemplate>
                                        </telerik:GridTemplateColumn>

                                        <telerik:GridButtonColumn UniqueName="deleteColumn" Visible="false" ConfirmText="<%$ Resources:Resource, qstDeleteRow %>" Text="<%$ Resources:Resource, lblActionDelete %>" 
                                                                  ConfirmDialogType="RadWindow" 
                                                                  ConfirmTitle="<%$ Resources:Resource, lblActionDelete %>" ButtonType="ImageButton" CommandName="Delete" HeaderStyle-Width="30px" ItemStyle-Width="30px">
                                            <ItemStyle BackColor="Control" />
                                        </telerik:GridButtonColumn>

                                    </Columns>

                                </telerik:GridTableView>
                            </DetailTables>

                            <%-- Actions Columns --%>
                            <Columns>
                                <telerik:GridEditCommandColumn ButtonType="ImageButton" UniqueName="EditCommandColumn3" CancelText="<%$ Resources:Resource, lblActionCancel %>" EditText="<%$ Resources:Resource, lblActionEdit %>"
                                                               UpdateText="<%$ Resources:Resource, lblActionUpdate %>" Reorderable="false" Resizable="false">
                                    <ItemStyle BackColor="Control" Width="30px" />
                                    <HeaderStyle Width="30px" />
                                </telerik:GridEditCommandColumn>

                                <telerik:GridTemplateColumn DataField="ActionID" DataType="System.Int32" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter ActionID column" 
                                                            HeaderText="<%$ Resources:Resource, lblID %>" SortExpression="ActionID" UniqueName="ActionID" Visible="False">
                                    <EditItemTemplate>
                                        <asp:Label ID="ActionIDLabel" runat="server" Text='<%# Eval("ActionID")%>'></asp:Label>
                                    </EditItemTemplate>
                                </telerik:GridTemplateColumn>

                                <telerik:GridTemplateColumn DataField="ResourceID" HeaderText="<%$ Resources:Resource, lblNameVisible %>" SortExpression="ResourceID" UniqueName="ResourceID"
                                                            GroupByExpression="ResourceID ResourceID GROUP BY ResourceID">
                                    <EditItemTemplate>
                                        <asp:Label runat="server" ID="NameVisible" Text=""></asp:Label>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label runat="server" ID="NameVisible" Text=""></asp:Label>
                                    </ItemTemplate>
                                </telerik:GridTemplateColumn>

                                <telerik:GridTemplateColumn DataField="DescriptionShort" FilterControlAltText="Filter DescriptionShort column" HeaderText="<%$ Resources:Resource, lblDescriptionShort %>"
                                                            SortExpression="DescriptionShort" UniqueName="DescriptionShort" GroupByExpression="DescriptionShort DescriptionShort GROUP BY DescriptionShort">
                                    <EditItemTemplate>
                                        <asp:Label runat="server" ID="LabelDescriptionShort" Text='<%# Eval("DescriptionShort")%>'></asp:Label>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label runat="server" ID="LabelDescriptionShort" Text='<%# Eval("DescriptionShort")%>'></asp:Label>
                                    </ItemTemplate>
                                </telerik:GridTemplateColumn>

                                <telerik:GridCheckBoxColumn DataField="IsActive" DataType="System.Boolean" FilterControlAltText="Filter IsActive column" HeaderText="<%$ Resources:Resource, lblActive %>" SortExpression="IsActive" UniqueName="IsActive">
                                </telerik:GridCheckBoxColumn>

                                <telerik:GridTemplateColumn DataField="CreatedFrom" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter CreatedFrom column" HeaderText="<%$ Resources:Resource, lblCreatedFrom %>" SortExpression="CreatedFrom" UniqueName="CreatedFrom" Visible="False">
                                    <ItemTemplate>
                                        <asp:Label ID="CreatedFromLabel" runat="server" Text='<%# Eval("CreatedFrom")%>'></asp:Label>
                                    </ItemTemplate>
                                </telerik:GridTemplateColumn>

                                <telerik:GridTemplateColumn DataField="CreatedOn" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter CreatedOn column" HeaderText="<%$ Resources:Resource, lblCreatedOn %>" SortExpression="CreatedOn" UniqueName="CreatedOn" Visible="False">
                                    <ItemTemplate>
                                        <asp:Label ID="CreatedOnLabel" runat="server" Text='<%# Eval("CreatedOn")%>'></asp:Label>
                                    </ItemTemplate>
                                </telerik:GridTemplateColumn>

                                <telerik:GridTemplateColumn DataField="EditFrom" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter EditFrom column" HeaderText="<%$ Resources:Resource, lblEditFrom %>" SortExpression="EditFrom" UniqueName="EditFrom" Visible="False">
                                    <ItemTemplate>
                                        <asp:Label ID="EditFromLabel" runat="server" Text='<%# Eval("EditFrom")%>'></asp:Label>
                                    </ItemTemplate>
                                </telerik:GridTemplateColumn>

                                <telerik:GridTemplateColumn DataField="EditOn" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter EditOn column" HeaderText="<%$ Resources:Resource, lblEditOn %>" SortExpression="EditOn" UniqueName="EditOn" Visible="False">
                                    <ItemTemplate>
                                        <asp:Label ID="EditOnLabel" runat="server" Text='<%# Eval("EditOn")%>'></asp:Label>
                                    </ItemTemplate>
                                </telerik:GridTemplateColumn>

                                <telerik:GridButtonColumn UniqueName="deleteColumn" Visible="false" ConfirmText="<%$ Resources:Resource, qstDeleteRow %>" Text="<%$ Resources:Resource, lblActionDelete %>" 
                                                          ConfirmDialogType="RadWindow"
                                                          ConfirmTitle="<%$ Resources:Resource, lblActionDelete %>" ButtonType="ImageButton" CommandName="Delete" HeaderStyle-Width="30px" ItemStyle-Width="30px">
                                    <ItemStyle BackColor="Control" />
                                </telerik:GridButtonColumn>
                            </Columns>
                        </telerik:GridTableView>

                    </DetailTables>

                    <%-- Dialogs Columns --%>
                    <Columns>
                        <telerik:GridEditCommandColumn ButtonType="ImageButton" UniqueName="EditCommandColumn2" CancelText="<%$ Resources:Resource, lblActionCancel %>" EditText="<%$ Resources:Resource, lblActionEdit %>"
                                                       UpdateText="<%$ Resources:Resource, lblActionUpdate %>" Reorderable="false" Resizable="false">
                            <ItemStyle BackColor="Control" Width="30px" />
                            <HeaderStyle Width="30px" />
                        </telerik:GridEditCommandColumn>

                        <telerik:GridTemplateColumn DataField="DialogID" DataType="System.Int32" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter DialogID column" 
                                                    HeaderText="<%$ Resources:Resource, lblID %>" SortExpression="DialogID" UniqueName="DialogID" Visible="False">
                            <EditItemTemplate>
                                <asp:Label ID="DialogIDLabel" runat="server" Text='<%# Eval("DialogID")%>'></asp:Label>
                            </EditItemTemplate>
                        </telerik:GridTemplateColumn>

                        <telerik:GridTemplateColumn DataField="ResourceID" HeaderText="<%$ Resources:Resource, lblNameVisible %>" SortExpression="ResourceID" UniqueName="ResourceID"
                                                    GroupByExpression="ResourceID ResourceID GROUP BY ResourceID">
                            <EditItemTemplate>
                                <asp:Label runat="server" ID="NameVisible" Text='<%# GetResource(Eval("ResourceID").ToString())%>'></asp:Label>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <table CellPadding="0" CellSpacing="0" style="border-width: 0px; padding: 0px; border-style: none; border-color: transparent; ">
                                    <tr>
                                        <td style='border-width: 0px; padding: 0px; border-style: none; border-color: transparent; padding-right: 5px; padding-left: <%# (Convert.ToInt32(Eval("IndentLevel")) * 20 - 40).ToString() + "px" %>'>
                                            <asp:Image runat="server" ImageUrl='<%# string.Concat(ConfigurationManager.AppSettings["ImageFilesHome"], Eval("ImagePath"), "/", Eval("ImageName")) %>'
                                                       Width="22px" Height="22px" />
                                        </td>
                                        <td style="border-width: 0px; padding: 0px; border-style: none; border-color: transparent; ">
                                            <asp:Label runat="server" ID="NameVisible" Text='<%# GetResource(Eval("ResourceID").ToString())%>'></asp:Label>
                                        </td>
                                    </tr>
                                </table>
                            </ItemTemplate>
                        </telerik:GridTemplateColumn>

                        <telerik:GridTemplateColumn DataField="DescriptionShort" FilterControlAltText="Filter DescriptionShort column" HeaderText="<%$ Resources:Resource, lblDescriptionShort %>"
                                                    SortExpression="DescriptionShort" UniqueName="DescriptionShort" Visible="false" 
                                                    GroupByExpression="DescriptionShort DescriptionShort GROUP BY DescriptionShort">
                            <EditItemTemplate>
                                <asp:Label runat="server" ID="DescriptionShort" Text='<%# Eval("DescriptionShort")%>'></asp:Label>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label runat="server" ID="LabelDescriptionShort" Text='<%# Eval("DescriptionShort")%>'></asp:Label>
                            </ItemTemplate>
                        </telerik:GridTemplateColumn>

                        <telerik:GridCheckBoxColumn DataField="UseCompanyAssignment" DataType="System.Boolean" FilterControlAltText="Filter UseCompanyAssignment column" 
                            HeaderText="<%$ Resources:Resource, lblUseCompanyAssignment %>" SortExpression="UseCompanyAssignment" UniqueName="UseCompanyAssignment">
                        </telerik:GridCheckBoxColumn>

                        <telerik:GridCheckBoxColumn DataField="IsActive" DataType="System.Boolean" FilterControlAltText="Filter IsActive column" HeaderText="<%$ Resources:Resource, lblActive %>" 
                                                    SortExpression="IsActive" UniqueName="IsActive">
                        </telerik:GridCheckBoxColumn>

                        <telerik:GridTemplateColumn DataField="ParentIsActive" HeaderText="<%$ Resources:Resource, lblParentIsActive %>" SortExpression="ParentIsActive" UniqueName="ParentIsActive"
                                                    GroupByExpression="ParentIsActive ParentIsActive GROUP BY ParentIsActive">
                            <ItemTemplate>
                                <asp:CheckBox runat="server" ID="ParentIsActive" Checked='<%# Eval("ParentIsActive") %>' Enabled="false" Width="70px" Height="22px" 
                                              BackColor='<%# (!(Convert.ToBoolean(Eval("ParentIsActive"))) && Convert.ToBoolean(Eval("IsActive"))) ? System.Drawing.Color.OrangeRed : System.Drawing.Color.White %>' 
                                              Text='<%# (!(Convert.ToBoolean(Eval("ParentIsActive"))) && Convert.ToBoolean(Eval("IsActive"))) ? "  " + Resources.Resource.lblError + "! " : "" %>'/>
                            </ItemTemplate>
                        </telerik:GridTemplateColumn>

                        <telerik:GridTemplateColumn DataField="ParentResourceID" HeaderText="<%$ Resources:Resource, lblParentName %>" SortExpression="ParentResourceID" UniqueName="ParentResourceID"
                                                    GroupByExpression="ParentResourceID ParentResourceID GROUP BY ParentResourceID">
                            <ItemTemplate>
                                <asp:Label runat="server" ID="ParentResourceID" Text='<%# GetResource(Eval("ParentResourceID").ToString())%>'></asp:Label>
                            </ItemTemplate>
                        </telerik:GridTemplateColumn>

                        <telerik:GridTemplateColumn DataField="CreatedFrom" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter CreatedFrom column" HeaderText="<%$ Resources:Resource, lblCreatedFrom %>" SortExpression="CreatedFrom" UniqueName="CreatedFrom" Visible="False">
                            <ItemTemplate>
                                <asp:Label ID="CreatedFromLabel" runat="server" Text='<%# Eval("CreatedFrom")%>'></asp:Label>
                            </ItemTemplate>
                        </telerik:GridTemplateColumn>

                        <telerik:GridTemplateColumn DataField="CreatedOn" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter CreatedOn column" HeaderText="<%$ Resources:Resource, lblCreatedOn %>" SortExpression="CreatedOn" UniqueName="CreatedOn" Visible="False">
                            <ItemTemplate>
                                <asp:Label ID="CreatedOnLabel" runat="server" Text='<%# Eval("CreatedOn")%>'></asp:Label>
                            </ItemTemplate>
                        </telerik:GridTemplateColumn>

                        <telerik:GridTemplateColumn DataField="EditFrom" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter EditFrom column" HeaderText="<%$ Resources:Resource, lblEditFrom %>" SortExpression="EditFrom" UniqueName="EditFrom" Visible="False">
                            <ItemTemplate>
                                <asp:Label ID="EditFromLabel" runat="server" Text='<%# Eval("EditFrom")%>'></asp:Label>
                            </ItemTemplate>
                        </telerik:GridTemplateColumn>

                        <telerik:GridTemplateColumn DataField="EditOn" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter EditOn column" HeaderText="<%$ Resources:Resource, lblEditOn %>" SortExpression="EditOn" UniqueName="EditOn" Visible="False">
                            <ItemTemplate>
                                <asp:Label ID="EditOnLabel" runat="server" Text='<%# Eval("EditOn")%>'></asp:Label>
                            </ItemTemplate>
                        </telerik:GridTemplateColumn>

                        <telerik:GridButtonColumn UniqueName="deleteColumn" Visible="false" ConfirmText="<%$ Resources:Resource, qstDeleteRow %>" Text="<%$ Resources:Resource, lblActionDelete %>" 
                                                  ConfirmDialogType="RadWindow"
                                                  ConfirmTitle="<%$ Resources:Resource, lblActionDelete %>" ButtonType="ImageButton" CommandName="Delete" HeaderStyle-Width="30px" ItemStyle-Width="30px">
                            <ItemStyle BackColor="Control" />
                        </telerik:GridButtonColumn>
                    </Columns>
                </telerik:GridTableView>

            </DetailTables>

            <%-- Roles Columns --%>
            <Columns>
                <telerik:GridEditCommandColumn ButtonType="ImageButton" UniqueName="EditCommandColumn1" CancelText="<%$ Resources:Resource, lblActionCancel %>" EditText="<%$ Resources:Resource, lblActionEdit %>"
                                               UpdateText="<%$ Resources:Resource, lblActionUpdate %>" Reorderable="false" Resizable="false">
                    <ItemStyle BackColor="Control" Width="30px" />
                    <HeaderStyle Width="30px" />
                </telerik:GridEditCommandColumn>

                <telerik:GridTemplateColumn DataField="RoleID" DataType="System.Int32" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter RoleID column" 
                                            HeaderText="<%$ Resources:Resource, lblID %>" SortExpression="RoleID" UniqueName="RoleID" Visible="False">
                    <EditItemTemplate>
                        <asp:Label ID="RoleIDLabel" runat="server" Text='<%# Eval("RoleID")%>'></asp:Label>
                    </EditItemTemplate>
                </telerik:GridTemplateColumn>

                <telerik:GridTemplateColumn DataField="NameVisible" HeaderText="<%$ Resources:Resource, lblNameVisible %>" SortExpression="NameVisible" UniqueName="NameVisible"
                                            GroupByExpression="NameVisible NameVisible GROUP BY NameVisible">
                    <EditItemTemplate>
                        <telerik:RadTextBox runat="server" ID="NameVisible" Text='<%# Bind("NameVisible")%>'></telerik:RadTextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label runat="server" ID="NameVisible" Text='<%# Eval("NameVisible")%>'></asp:Label>
                    </ItemTemplate>
                </telerik:GridTemplateColumn>

                <telerik:GridTemplateColumn DataField="DescriptionShort" FilterControlAltText="Filter DescriptionShort column" HeaderText="<%$ Resources:Resource, lblDescriptionShort %>"
                                            SortExpression="DescriptionShort" UniqueName="DescriptionShort" GroupByExpression="DescriptionShort DescriptionShort GROUP BY DescriptionShort">
                    <EditItemTemplate>
                        <telerik:RadTextBox runat="server" ID="DescriptionShort" Text='<%# Bind("DescriptionShort")%>' Width="300px"></telerik:RadTextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label runat="server" ID="LabelDescriptionShort" Text='<%# Eval("DescriptionShort")%>'></asp:Label>
                    </ItemTemplate>
                </telerik:GridTemplateColumn>

                <telerik:GridTemplateColumn DataField="TypeID" DataType="System.Byte" HeaderText="<%$ Resources:Resource, lblAuthorizationLevel %>" SortExpression="TypeID" UniqueName="TypeID"
                                            GroupByExpression="TypeID TypeID GROUP BY TypeID" InsertVisiblityMode="AlwaysVisible" HeaderStyle-HorizontalAlign="Right" 
                                            ItemStyle-HorizontalAlign="Right" Visible="false">
                    <EditItemTemplate>
                        <telerik:RadNumericTextBox runat="server" ID="TypeID" Text='<%# Bind("TypeID")%>' MaxValue='<%# Convert.ToDouble(Session["UserType"]) %>' MinValue="1" ShowSpinButtons="true" 
                                                   ButtonsPosition="Right">
                            <IncrementSettings Step="1" />
                            <NumberFormat DecimalDigits="0" />
                        </telerik:RadNumericTextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label runat="server" ID="TypeID" Text='<%# Eval("TypeID")%>'></asp:Label>
                    </ItemTemplate>
                </telerik:GridTemplateColumn>

                <telerik:GridCheckBoxColumn DataField="IsVisible" DataType="System.Boolean" FilterControlAltText="Filter IsVisible column" HeaderText="<%$ Resources:Resource, lblActive %>" SortExpression="IsVisible" UniqueName="IsVisible">
                </telerik:GridCheckBoxColumn>

                <telerik:GridCheckBoxColumn DataField="ShowInList" DataType="System.Boolean" FilterControlAltText="Filter ShowInList column" HeaderText="<%$ Resources:Resource, lblShowInLists %>" 
                                            SortExpression="ShowInList" UniqueName="ShowInList">
                </telerik:GridCheckBoxColumn>

                <telerik:GridCheckBoxColumn DataField="SelfAndSubcontractors" DataType="System.Boolean" FilterControlAltText="Filter SelfAndSubcontractors column" HeaderText="<%$ Resources:Resource, lblSelfAndSubcontractors %>" 
                                            SortExpression="SelfAndSubcontractors" UniqueName="SelfAndSubcontractors">
                </telerik:GridCheckBoxColumn>

                <telerik:GridTemplateColumn DataField="CreatedFrom" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter CreatedFrom column" HeaderText="<%$ Resources:Resource, lblCreatedFrom %>" SortExpression="CreatedFrom" UniqueName="CreatedFrom" Visible="False">
                    <ItemTemplate>
                        <asp:Label ID="CreatedFromLabel" runat="server" Text='<%# Eval("CreatedFrom")%>'></asp:Label>
                    </ItemTemplate>
                </telerik:GridTemplateColumn>

                <telerik:GridTemplateColumn DataField="CreatedOn" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter CreatedOn column" HeaderText="<%$ Resources:Resource, lblCreatedOn %>" SortExpression="CreatedOn" UniqueName="CreatedOn" Visible="False">
                    <ItemTemplate>
                        <asp:Label ID="CreatedOnLabel" runat="server" Text='<%# Eval("CreatedOn")%>'></asp:Label>
                    </ItemTemplate>
                </telerik:GridTemplateColumn>

                <telerik:GridTemplateColumn DataField="EditFrom" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter EditFrom column" HeaderText="<%$ Resources:Resource, lblEditFrom %>" SortExpression="EditFrom" UniqueName="EditFrom" Visible="False">
                    <ItemTemplate>
                        <asp:Label ID="EditFromLabel" runat="server" Text='<%# Eval("EditFrom")%>'></asp:Label>
                    </ItemTemplate>
                </telerik:GridTemplateColumn>

                <telerik:GridTemplateColumn DataField="EditOn" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter EditOn column" HeaderText="<%$ Resources:Resource, lblEditOn %>" SortExpression="EditOn" UniqueName="EditOn" Visible="False">
                    <ItemTemplate>
                        <asp:Label ID="EditOnLabel" runat="server" Text='<%# Eval("EditOn") %>'></asp:Label>
                    </ItemTemplate>
                </telerik:GridTemplateColumn>

                <telerik:GridButtonColumn UniqueName="deleteColumn" Visible="true" ConfirmText="<%$ Resources:Resource, qstDeleteRow %>" Text="<%$ Resources:Resource, lblActionDelete %>" 
                                          ConfirmDialogType="RadWindow"
                                          ConfirmTitle="<%$ Resources:Resource, lblActionDelete %>" ButtonType="ImageButton" CommandName="Delete" HeaderStyle-Width="30px" ItemStyle-Width="30px">
                    <ItemStyle BackColor="Control" />
                </telerik:GridButtonColumn>
            </Columns>

        </MasterTableView>

    </telerik:RadGrid>

    <telerik:RadToolTipManager ID="RadToolTipManager1" OffsetY="-1" HideEvent="LeaveToolTip" runat="server" OnAjaxUpdate="OnAjaxUpdate"
                               RelativeTo="Element" Position="MiddleRight" ShowDelay="2000">
    </telerik:RadToolTipManager>

    <%-- Fields Datasource --%>
    <asp:SqlDataSource ID="SqlDataSource_Fields" runat="server" ConnectionString="<%$ ConnectionStrings:Insite_Dev_ConnectionString %>"
                       OldValuesParameterFormatString="original_{0}"
                       SelectCommand="SELECT Master_Actions_Fields.SystemID, Master_Actions_Fields.BpID, Master_Actions_Fields.RoleID, Master_Actions_Fields.DialogID, Master_Actions_Fields.ActionID, Master_Actions_Fields.FieldID, Master_Actions_Fields.IsVisible, Master_Actions_Fields.IsEditable, Master_Actions_Fields.IsMandatory, Master_Actions_Fields.DefaultValue, Master_Actions_Fields.CreatedFrom, Master_Actions_Fields.CreatedOn, Master_Actions_Fields.EditFrom, Master_Actions_Fields.EditOn, System_Fields.InternalName, System_Fields.ResourceID FROM Master_Actions_Fields INNER JOIN System_Fields ON Master_Actions_Fields.SystemID = System_Fields.SystemID AND Master_Actions_Fields.FieldID = System_Fields.FieldID AND Master_Actions_Fields.DialogID = System_Fields.DialogID WHERE (Master_Actions_Fields.SystemID = @SystemID) AND (Master_Actions_Fields.BpID = @BpID) AND (Master_Actions_Fields.RoleID = @RoleID) AND (Master_Actions_Fields.DialogID = @DialogID) AND (Master_Actions_Fields.ActionID = @ActionID) ORDER BY System_Fields.InternalName"
                       UpdateCommand="INSERT INTO History_Actions_Fields SELECT * FROM Master_Actions_Fields WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND [RoleID] = @original_RoleID AND [DialogID] = @original_DialogID AND [ActionID] = @original_ActionID AND [FieldID] = @original_FieldID; 
                       UPDATE [Master_Actions_Fields] SET [IsVisible] = @IsVisible, [IsEditable] = @IsEditable, [IsMandatory] = @IsMandatory, [DefaultValue] = @DefaultValue, [EditFrom] = @UserName, [EditOn] = SYSDATETIME() WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND [RoleID] = @original_RoleID AND [DialogID] = @original_DialogID AND [ActionID] = @original_ActionID AND [FieldID] = @original_FieldID">
        <SelectParameters>
            <asp:SessionParameter DefaultValue="0" Name="SystemID" SessionField="SystemID" Type="Int32" />
            <asp:SessionParameter DefaultValue="0" Name="BpID" SessionField="BpID" Type="Int32" />
            <asp:Parameter Name="RoleID" Type="Int32" />
            <asp:Parameter Name="DialogID" Type="Int32" />
            <asp:Parameter Name="ActionID" Type="Int32" />
        </SelectParameters>
        <UpdateParameters>
            <asp:Parameter Name="IsVisible" Type="Boolean" />
            <asp:Parameter Name="IsEditable" Type="Boolean" />
            <asp:Parameter Name="IsMandatory" Type="Boolean" />
            <asp:Parameter Name="DefaultValue" />
            <asp:SessionParameter DefaultValue="" Name="UserName" SessionField="LoginName" Type="String" />
            <asp:Parameter Name="original_SystemID" Type="Int32" />
            <asp:Parameter Name="original_BpID" Type="Int32" />
            <asp:Parameter Name="original_RoleID" Type="Int32" />
            <asp:Parameter Name="original_DialogID" Type="Int32" />
            <asp:Parameter Name="original_ActionID" Type="Int32" />
            <asp:Parameter Name="original_FieldID" Type="Int32" />
        </UpdateParameters>
    </asp:SqlDataSource>

    <%-- Actions Datasource --%>
    <asp:SqlDataSource ID="SqlDataSource_Actions" runat="server" ConnectionString="<%$ ConnectionStrings:Insite_Dev_ConnectionString %>"
                       OldValuesParameterFormatString="original_{0}"
                       SelectCommand="SELECT Master_Dialogs_Actions.SystemID, Master_Dialogs_Actions.BpID, Master_Dialogs_Actions.RoleID, Master_Dialogs_Actions.DialogID, Master_Dialogs_Actions.ActionID, Master_Dialogs_Actions.IsActive, Master_Dialogs_Actions.CreatedFrom, Master_Dialogs_Actions.CreatedOn, Master_Dialogs_Actions.EditFrom, Master_Dialogs_Actions.EditOn, System_Actions.NameVisible, System_Actions.DescriptionShort, System_Actions.ResourceID FROM Master_Dialogs_Actions INNER JOIN System_Actions ON Master_Dialogs_Actions.SystemID = System_Actions.SystemID AND Master_Dialogs_Actions.ActionID = System_Actions.ActionID WHERE (Master_Dialogs_Actions.SystemID = @SystemID) AND (Master_Dialogs_Actions.BpID = @BpID) AND (Master_Dialogs_Actions.RoleID = @RoleID) AND (Master_Dialogs_Actions.DialogID = @DialogID) ORDER BY System_Actions.NameVisible"
                       UpdateCommand="INSERT INTO History_Dialogs_Actions SELECT * FROM Master_Dialogs_Actions WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND [RoleID] = @original_RoleID AND [DialogID] = @original_DialogID AND [ActionID] = @original_ActionID; 
                       UPDATE [Master_Dialogs_Actions] SET [IsActive] = @IsActive, [EditFrom] = @UserName, [EditOn] = SYSDATETIME() WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND [RoleID] = @original_RoleID AND [DialogID] = @original_DialogID AND [ActionID] = @original_ActionID">
        <SelectParameters>
            <asp:SessionParameter DefaultValue="0" Name="SystemID" SessionField="SystemID" Type="Int32" />
            <asp:SessionParameter DefaultValue="0" Name="BpID" SessionField="BpID" Type="Int32" />
            <asp:Parameter Name="RoleID" Type="Int32" />
            <asp:Parameter Name="DialogID" Type="Int32" />
        </SelectParameters>
        <UpdateParameters>
            <asp:Parameter Name="IsActive" Type="Boolean" />
            <asp:SessionParameter DefaultValue="" Name="UserName" SessionField="LoginName" Type="String" />
            <asp:Parameter Name="original_SystemID" Type="Int32" />
            <asp:Parameter Name="original_BpID" Type="Int32" />
            <asp:Parameter Name="original_RoleID" Type="Int32" />
            <asp:Parameter Name="original_DialogID" Type="Int32" />
            <asp:Parameter Name="original_ActionID" Type="Int32" />
        </UpdateParameters>
    </asp:SqlDataSource>

    <%-- Dialogs Datasource --%>
    <asp:SqlDataSource ID="SqlDataSource_Dialogs" runat="server" ConnectionString="<%$ ConnectionStrings:Insite_Dev_ConnectionString %>"
        OldValuesParameterFormatString="original_{0}"
        SelectCommand="WITH Dialogs AS ( SELECT m_tn1.SystemID, @BpID AS BpID, m_tn1.NodeID, NULL AS ParentID, m_tn1.NameVisible, m_tn1.DescriptionShort, CAST(0 AS int) AS RoleID , CAST(1 AS bit) AS UseCompanyAssignment, CAST(1 AS bit) AS IsActive, CAST(1 AS bit) AS ParentIsActive, CAST('' AS nvarchar(50)) AS ParentResourceID, m_tn1.ResourceID, m_tn1.DialogID, s_i.ImageName, s_i.ImagePath, CAST('' AS nvarchar(50)) AS CreatedFrom, CAST(NULL AS datetime) AS CreatedOn, CAST('' AS nvarchar(50)) AS EditFrom, CAST(NULL AS datetime) AS EditOn, CAST(ROW_NUMBER() OVER(PARTITION BY m_tn1.ParentID ORDER BY m_tn1.[Rank]) AS nvarchar(50)) AS TreeLevel, 1 AS IndentLevel FROM Master_TreeNodes AS m_tn1 INNER JOIN System_Images s_i ON m_tn1.SystemID = s_i.SystemID AND m_tn1.ImageID = s_i.ImageID WHERE m_tn1.SystemID = @SystemID AND m_tn1.ParentID IS NULL AND m_tn1.IsVisible = 1 AND m_tn1.IsValid = 1 UNION ALL SELECT m_tn2.SystemID, m_rd.BpID, m_tn2.NodeID, m_tn2.ParentID, m_tn2.NameVisible, m_tn2.DescriptionShort, m_rd.RoleID, m_rd.UseCompanyAssignment, m_rd.IsActive, Dialogs.IsActive AS ParentIsActive, Dialogs.ResourceID AS ParentResourceID, m_tn2.ResourceID, m_tn2.DialogID, s_i.ImageName, s_i.ImagePath, m_rd.CreatedFrom, m_rd.CreatedOn, m_rd.EditFrom, m_rd.EditOn, CAST(TreeLevel + ';' + CAST(ROW_NUMBER() OVER(PARTITION BY m_tn2.ParentID ORDER BY m_tn2.[Rank]) AS nvarchar(50)) AS nvarchar(50)) AS TreeLevel, IndentLevel + 1 AS IndentLevel FROM Master_TreeNodes m_tn2 INNER JOIN Dialogs ON Dialogs.SystemID = m_tn2.SystemID AND Dialogs.NodeID = m_tn2.ParentID INNER JOIN Master_Roles_Dialogs AS m_rd ON m_tn2.SystemID = m_rd.SystemID AND m_tn2.DialogID = m_rd.DialogID INNER JOIN System_Images s_i ON m_tn2.SystemID = s_i.SystemID AND m_tn2.ImageID = s_i.ImageID WHERE m_tn2.IsVisible = 1 AND m_tn2.IsValid = 1 AND m_rd.BpID = @BpID AND m_rd.RoleID = @RoleID ) SELECT DISTINCT SystemID, BpID, NodeID, ParentID, NameVisible, DescriptionShort, RoleID, UseCompanyAssignment, IsActive, ParentIsActive, ParentResourceID, ResourceID, DialogID, ImageName, ImagePath, CreatedFrom, CreatedOn, EditFrom, EditOn, TreeLevel, IndentLevel FROM Dialogs WHERE IndentLevel > 1 ORDER BY TreeLevel"
        UpdateCommand="INSERT INTO History_Roles_Dialogs SELECT * FROM Master_Roles_Dialogs WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND [RoleID] = @original_RoleID AND [DialogID] = @original_DialogID; 
                       UPDATE [Master_Roles_Dialogs] SET UseCompanyAssignment = @UseCompanyAssignment, [IsActive] = @IsActive, [EditFrom] = @UserName, [EditOn] = SYSDATETIME() WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND [RoleID] = @original_RoleID AND [DialogID] = @original_DialogID">
        <SelectParameters>
            <asp:SessionParameter DefaultValue="0" Name="BpID" SessionField="BpID" Type="Int32" />
            <asp:SessionParameter DefaultValue="0" Name="SystemID" SessionField="SystemID" Type="Int32" />
            <asp:Parameter Name="RoleID" Type="Int32" />
        </SelectParameters>
        <UpdateParameters>
            <asp:Parameter Name="original_SystemID" Type="Int32" />
            <asp:Parameter Name="original_BpID" Type="Int32" />
            <asp:Parameter Name="original_RoleID" Type="Int32" />
            <asp:Parameter Name="original_DialogID" Type="Int32" />
            <asp:Parameter Name="UseCompanyAssignment" />
            <asp:Parameter Name="IsActive" Type="Boolean"></asp:Parameter>
            <asp:SessionParameter SessionField="LoginName" DefaultValue="" Name="UserName" Type="String"></asp:SessionParameter>
        </UpdateParameters>
    </asp:SqlDataSource>

    <asp:SqlDataSource ID="SqlDataSource_Roles" runat="server" ConnectionString="<%$ ConnectionStrings:Insite_Dev_ConnectionString %>"
        OldValuesParameterFormatString="original_{0}"
        DeleteCommand="INSERT INTO History_Roles SELECT * FROM Master_Roles WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND [RoleID] = @original_RoleID; 
                       DELETE FROM [Master_Roles] WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND [RoleID] = @original_RoleID"
        InsertCommand="INSERT INTO [Master_Roles] ([SystemID], [BpID], [NameVisible], [DescriptionShort], [TypeID], [IsVisible], ShowInList, SelfAndSubcontractors, [CreatedFrom], [CreatedOn], [EditFrom], [EditOn]) VALUES (@SystemID, @BpID, @NameVisible, @DescriptionShort, @TypeID, @IsVisible, @ShowInList, @SelfAndSubcontractors, @UserName, SYSDATETIME(), @UserName, SYSDATETIME()); EXEC dbo.CreateRightsHierarchy @SystemID, @BpID"
        SelectCommand="SELECT * FROM [Master_Roles] WHERE (([SystemID] = @SystemID) AND ([BpID] = @BpID) AND (TypeID <= @UserType)) ORDER BY NameVisible"
        UpdateCommand="INSERT INTO History_Roles SELECT * FROM Master_Roles WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND [RoleID] = @original_RoleID; 
                       UPDATE [Master_Roles] SET [NameVisible] = @NameVisible, [DescriptionShort] = @DescriptionShort, [TypeID] = @TypeID, [IsVisible] = @IsVisible, ShowInList = @ShowInList, SelfAndSubcontractors = @SelfAndSubcontractors, [EditFrom] = @UserName, [EditOn] = SYSDATETIME() WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND [RoleID] = @original_RoleID">
        <DeleteParameters>
            <asp:Parameter Name="original_SystemID" Type="Int32" />
            <asp:Parameter Name="original_BpID" Type="Int32" />
            <asp:Parameter Name="original_RoleID" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:SessionParameter DefaultValue="0" Name="SystemID" SessionField="SystemID" Type="Int32" />
            <asp:SessionParameter DefaultValue="0" Name="BpID" SessionField="BpID" Type="Int32" />
            <asp:Parameter Name="NameVisible" Type="String" />
            <asp:Parameter Name="DescriptionShort" Type="String" />
            <asp:Parameter Name="TypeID" Type="Byte" />
            <asp:Parameter Name="IsVisible" Type="Boolean" />
            <asp:Parameter Name="ShowInList" Type="Boolean" />
            <asp:Parameter Name="SelfAndSubcontractors"></asp:Parameter>
            <asp:SessionParameter DefaultValue="" Name="UserName" SessionField="LoginName" Type="String" />
        </InsertParameters>
        <SelectParameters>
            <asp:SessionParameter DefaultValue="0" Name="SystemID" SessionField="SystemID" Type="Int32" />
            <asp:SessionParameter DefaultValue="0" Name="BpID" SessionField="BpID" Type="Int32" />
            <asp:SessionParameter DefaultValue="0" Name="UserType" SessionField="UserType" />
        </SelectParameters>
        <UpdateParameters>
            <asp:Parameter Name="original_SystemID" Type="Int32" />
            <asp:Parameter Name="original_BpID" Type="Int32" />
            <asp:Parameter Name="original_RoleID" Type="Int32" />
            <asp:Parameter Name="NameVisible" Type="String" />
            <asp:Parameter Name="DescriptionShort" Type="String" />
            <asp:Parameter Name="TypeID" Type="Byte"></asp:Parameter>

            <asp:Parameter Name="IsVisible" Type="Boolean" />
            <asp:Parameter Name="ShowInList" Type="Boolean" />
            <asp:Parameter Name="SelfAndSubcontractors" />
            <asp:SessionParameter SessionField="LoginName" DefaultValue="" Name="UserName" Type="String"></asp:SessionParameter>
        </UpdateParameters>
    </asp:SqlDataSource>

</asp:Content>
