<%@ Page Title="<%$ Resources:Resource, lblTariffContracts %>" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="TariffContracts.aspx.cs" Inherits="InSite.App.Views.Configuration.TariffContracts" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeaderContent" runat="server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="BodyContent" runat="server">
    <telerik:RadPersistenceManagerProxy ID="RadPersistenceManagerProxy1" runat="server">
        <PersistenceSettings>
            <telerik:PersistenceSetting ControlID="RadGrid1" />
            <telerik:PersistenceSetting ControlID="RadGridTariffData" />
        </PersistenceSettings>
    </telerik:RadPersistenceManagerProxy>

    <telerik:RadAjaxManagerProxy ID="AjaxManagerProxy1" runat="server">
        <AjaxSettings>
            <telerik:AjaxSetting AjaxControlID="RadGrid1">
                <UpdatedControls>
                    <telerik:AjaxUpdatedControl ControlID="RadGrid1" LoadingPanelID="RadAjaxLoadingPanelMaster" />
                </UpdatedControls>
            </telerik:AjaxSetting>
            <telerik:AjaxSetting AjaxControlID="RadGridTariffData">
                <UpdatedControls>
                    <telerik:AjaxUpdatedControl ControlID="RadGridTariffData" LoadingPanelID="RadAjaxLoadingPanelMaster" />
                </UpdatedControls>
            </telerik:AjaxSetting>
        </AjaxSettings>
    </telerik:RadAjaxManagerProxy>

    <div>
        <%-- TariffContracts Grid --%>
        <telerik:RadGrid ID="RadGrid1" runat="server" CellSpacing="0" DataSourceID="SqlDataSource_TariffContracts" GridLines="None" CssClass="MainGrid" AllowAutomaticDeletes="True"
                         AllowAutomaticInserts="True" AllowAutomaticUpdates="True"
                         OnPreRender="RadGrid1_PreRender" OnItemDeleted="RadGrid1_ItemDeleted" OnItemCommand="RadGrid1_ItemCommand" OnItemUpdated="RadGrid1_ItemUpdated"
                         OnItemInserted="RadGrid1_ItemInserted" OnItemCreated="RadGrid1_ItemCreated" OnItemDataBound="RadGrid1_ItemDataBound" OnGroupsChanging="RadGrid1_GroupsChanging">

            <ExportSettings>
                <Pdf PaperSize="A4">
                </Pdf>
                <Excel Format="ExcelML" />
            </ExportSettings>

            <ClientSettings AllowColumnsReorder="True" AllowDragToGroup="True" EnableRowHoverStyle="True" EnablePostBackOnRowClick="false">
                <Resizing AllowColumnResize="true"></Resizing>
                <Selecting AllowRowSelect="True" />
                <ClientEvents OnRowClick="OnRowClick" OnGridCreated="OnGridCreated" OnKeyPress="GridKeyPress" />
            </ClientSettings>

            <%-- TariffContracts Master --%>
        <SortingSettings SortedBackColor="Transparent" />

            <MasterTableView AutoGenerateColumns="False" DataKeyNames="SystemID,BpID,TariffContractID" CommandItemDisplay="Top" EditMode="PopUp" DataSourceID="SqlDataSource_TariffContracts"
                             HierarchyLoadMode="ServerOnDemand" Name="TariffContracts" ShowHeader="true" Caption="<%$ Resources:Resource, lblTariffContracts %>" AllowPaging="true" PageSize="10" CssClass="MasterClass">

                <PagerStyle Mode="NextPrevAndNumeric" AlwaysVisible="true" />

                <CommandItemSettings ShowRefreshButton="true" ShowAddNewRecordButton="true" ShowExportToCsvButton="False" ShowExportToExcelButton="True" ShowExportToPdfButton="False"
                                     AddNewRecordText="<%$ Resources:Resource, lblActionNew %>" RefreshText="<%$ Resources:Resource, lblActionRefresh %>" />

                <EditFormSettings EditFormType="AutoGenerated" CaptionDataField="NameVisible" CaptionFormatString="{0}">
                    <PopUpSettings Modal="true" ShowCaptionInEditForm="false" ScrollBars="Auto" />
                    <EditColumn ButtonType="ImageButton" UniqueName="EditCommandColumn1" CancelText="<%$ Resources:Resource, lblActionCancel %>" EditText="<%$ Resources:Resource, lblActionEdit %>"
                                UpdateText="<%$ Resources:Resource, lblActionUpdate %>" />
                    <FormTableStyle CellPadding="3" CellSpacing="3" />
                </EditFormSettings>

                <%-- TariffContract Nested View --%>
                <NestedViewTemplate>
                    <asp:Panel runat="server" ID="InnerContainer1" Visible="true">
                        <telerik:RadTabStrip runat="server" ID="TabStrip1" MultiPageID="Multipage1" SelectedIndex="0">
                            <Tabs>
                                <telerik:RadTab runat="server" Text='<%$ Resources:Resource, lblTariffData %>' Font-Bold="true" PageViewID="PageView1_1">
                                </telerik:RadTab>
                                <telerik:RadTab runat="server" Text="<%$ Resources:Resource, lblDetails %>" Font-Bold="true" PageViewID="PageView1_2">
                                </telerik:RadTab>
                            </Tabs>
                        </telerik:RadTabStrip>

                        <telerik:RadMultiPage runat="server" ID="Multipage1" SelectedIndex="0" RenderSelectedPageOnly="false">

                            <%-- TariffContract TariffData --%>
                            <telerik:RadPageView runat="server" ID="PageView1_1">
                                <asp:HiddenField runat="server" ID="TariffContractID" Value='<%# Eval("TariffContractID") %>' />

                                <%-- TariffData Grid --%>
                                <telerik:RadGrid ID="RadGridTariffData" EnableHierarchyExpandAll="true" DataSourceID="SqlDataSource_TariffData" Width="100%"
                                                 runat="server" AllowPaging="true" ShowFooter="false" EnableLinqExpressions="false" AllowAutomaticUpdates="True" AllowAutomaticDeletes="true" 
                                                 AllowAutomaticInserts="true"
                                                 OnItemInserted="RadGrid1_ItemInserted" OnPreRender="RadGrid1_PreRender" OnItemDataBound="RadGridTariffData_ItemDataBound"
                                                 OnItemDeleted="RadGridTariffData_ItemDeleted" OnItemUpdated="RadGridTariffData_ItemUpdated" OnItemCommand="RadGridTariffData_ItemCommand" 
                                                 OnItemCreated="RadGridTariffData_ItemCreated">

                                    <ClientSettings AllowColumnsReorder="True" AllowDragToGroup="True" EnableRowHoverStyle="True" EnablePostBackOnRowClick="false">
                                        <Resizing AllowColumnResize="true"></Resizing>
                                        <Selecting AllowRowSelect="True" />
                                        <ClientEvents OnRowClick="OnRowClick" OnGridCreated="OnGridCreated" OnKeyPress="GridKeyPress" />
                                    </ClientSettings>

                                    <%-- TariffData Master --%>
        <SortingSettings SortedBackColor="Transparent" />

                                    <MasterTableView Name="TariffData" DataSourceID="SqlDataSource_TariffData" HierarchyLoadMode="ServerOnDemand" EnableHierarchyExpandAll="true"
                                                     CssClass="MasterClass" EditMode="PopUp" AutoGenerateColumns="False"
                                                     DataKeyNames="SystemID,BpID,TariffContractID,TariffDataID"
                                                     CommandItemDisplay="Top">

                                        <PagerStyle Mode="NextPrevAndNumeric" AlwaysVisible="true" />

                                        <CommandItemSettings ShowRefreshButton="true" ShowAddNewRecordButton="true" ShowExportToCsvButton="False" ShowExportToExcelButton="True" ShowExportToPdfButton="False"
                                                             AddNewRecordText="<%$ Resources:Resource, lblActionNew %>" RefreshText="<%$ Resources:Resource, lblActionRefresh %>" />

                                        <EditFormSettings EditFormType="AutoGenerated" CaptionDataField="NameVisible" CaptionFormatString="{0}">
                                            <PopUpSettings Modal="true" ShowCaptionInEditForm="false" ScrollBars="Auto" />
                                            <EditColumn ButtonType="ImageButton" UniqueName="EditCommandColumn2" CancelText="<%$ Resources:Resource, lblActionCancel %>" EditText="<%$ Resources:Resource, lblActionEdit %>"
                                                        UpdateText="<%$ Resources:Resource, lblActionUpdate %>" />
                                            <FormTableStyle CellPadding="3" CellSpacing="3" />
                                        </EditFormSettings>

                                        <%-- TariffData Details --%>
                                        <NestedViewTemplate>
                                            <fieldset style="padding: 10px; width: 500px; margin-left: 10px; margin-bottom: 10px;">
                                                <legend style="padding: 5px; background-color: transparent;">
                                                    <b><%= Resources.Resource.lblDetailsFor%> <%# Eval("NameVisible") %></b>
                                                </legend>
                                                <table style="width: 100%;">
                                                    <tr>
                                                        <td><%= Resources.Resource.lblID%>: </td>
                                                        <td>
                                                            <asp:Label Text='<%#Eval("TariffDataID")%>' runat="server"></asp:Label>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td><%= Resources.Resource.lblNameVisible%>: </td>
                                                        <td>
                                                            <asp:Label Text='<%#Eval("NameVisible")%>' runat="server"></asp:Label>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td><%= Resources.Resource.lblDescriptionShort%>: </td>
                                                        <td>
                                                            <asp:Label Text='<%#Eval("DescriptionShort")%>' runat="server"></asp:Label>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td><%#Eval("TariffValue1Name")%>: </td>
                                                        <td>
                                                            <asp:Label Text='<%#Eval("TariffValue1", "{0:#,##0.00}")%>' runat="server"></asp:Label>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td><%#Eval("TariffValue2Name")%>: </td>
                                                        <td>
                                                            <asp:Label Text='<%#Eval("TariffValue2", "{0:#,##0.00}")%>' runat="server"></asp:Label>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td><%#Eval("TariffValue3Name")%>: </td>
                                                        <td>
                                                            <asp:Label Text='<%#Eval("TariffValue3", "{0:#,##0.00}")%>' runat="server"></asp:Label>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td><%#Eval("TariffValue4Name")%>: </td>
                                                        <td>
                                                            <asp:Label Text='<%#Eval("TariffValue4", "{0:#,##0.00}")%>' runat="server"></asp:Label>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td>&nbsp; </td>
                                                        <td>&nbsp; </td>
                                                    </tr>
                                                    <tr>
                                                        <td><%= Resources.Resource.lblCreatedFrom%>: </td>
                                                        <td>
                                                            <asp:Label Text='<%#Eval("CreatedFrom")%>' runat="server"></asp:Label>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td><%= Resources.Resource.lblCreatedOn%>: </td>
                                                        <td>
                                                            <asp:Label Text='<%#Eval("CreatedOn")%>' runat="server"></asp:Label>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td><%= Resources.Resource.lblEditFrom%>: </td>
                                                        <td>
                                                            <asp:Label Text='<%#Eval("EditFrom")%>' runat="server"></asp:Label>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td><%= Resources.Resource.lblEditOn%>: </td>
                                                        <td>
                                                            <asp:Label Text='<%#Eval("EditOn")%>' runat="server"></asp:Label>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </fieldset>
                                        </NestedViewTemplate>

                                        <%-- TariffData Columns --%>
                                        <Columns>
                <telerik:GridEditCommandColumn ButtonType="ImageButton" UniqueName="EditCommandColumn" CancelText="<%$ Resources:Resource, lblActionCancel %>" EditText="<%$ Resources:Resource, lblActionEdit %>"
                                               UpdateText="<%$ Resources:Resource, lblActionUpdate %>" Reorderable="false" Resizable="false">
                    <ItemStyle BackColor="Control" Width="30px" />
                    <HeaderStyle Width="30px" />
                </telerik:GridEditCommandColumn>

                                            <telerik:GridTemplateColumn DataField="TariffDataID" FilterControlAltText="Filter TariffDataID column" 
                                                                        HeaderText="<%$ Resources:Resource, lblID %>" SortExpression="TariffDataID" UniqueName="TariffDataID" 
                                                                        GroupByExpression="TariffDataID TariffDataID GROUP BY TariffDataID" Visible="false" InsertVisiblityMode="AlwaysHidden">
                                                <EditItemTemplate>
                                                    <asp:Label runat="server" ID="TariffDataID" Text='<%# Eval("TariffDataID") %>'></asp:Label>
                                                </EditItemTemplate>
                                            </telerik:GridTemplateColumn>

                                            <telerik:GridTemplateColumn DataField="NameVisible" HeaderText="<%$ Resources:Resource, lblNameVisible %>" SortExpression="NameVisible" UniqueName="NameVisible"
                                                                        GroupByExpression="NameVisible NameVisible GROUP BY NameVisible">
                                                <EditItemTemplate>
                                                    <telerik:RadTextBox runat="server" ID="NameVisible" Text='<%# Bind("NameVisible") %>'></telerik:RadTextBox>
                                                </EditItemTemplate>
                                                <ItemTemplate>
                                                    <asp:Label runat="server" ID="NameVisible" Text='<%# Eval("NameVisible") %>'></asp:Label>
                                                </ItemTemplate>
                                            </telerik:GridTemplateColumn>

                                            <telerik:GridTemplateColumn DataField="DescriptionShort" FilterControlAltText="Filter DescriptionShort column" HeaderText="<%$ Resources:Resource, lblDescriptionShort %>"
                                                                        SortExpression="DescriptionShort" UniqueName="DescriptionShort" GroupByExpression="DescriptionShort DescriptionShort GROUP BY DescriptionShort">
                                                <EditItemTemplate>
                                                    <telerik:RadTextBox runat="server" ID="DescriptionShort" Text='<%# Bind("DescriptionShort") %>' Width="300px"></telerik:RadTextBox>
                                                </EditItemTemplate>
                                                <ItemTemplate>
                                                    <asp:Label runat="server" ID="LabelDescriptionShort" Text='<%# Eval("DescriptionShort") %>'></asp:Label>
                                                </ItemTemplate>
                                            </telerik:GridTemplateColumn>

                                            <telerik:GridTemplateColumn DataField="TariffValue1" SortExpression="TariffValue1" DataType="System.Decimal" DefaultInsertValue="0"
                                                                        UniqueName="TariffValue1" GroupByExpression="TariffValue1 TariffValue1 GROUP BY TariffValue1">
                                                <EditItemTemplate>
                                                    <telerik:RadTextBox runat="server" ID="TariffValue1" Type="Number" DataType="Decimal" Text='<%# Bind("TariffValue1", "{0:#,##0.00}") %>'></telerik:RadTextBox>
                                                </EditItemTemplate>
                                                <ItemTemplate>
                                                    <asp:Label runat="server" ID="TariffValue1" Text='<%# Eval("TariffValue1", "{0:#,##0.00}") %>'></asp:Label>
                                                </ItemTemplate>
                                            </telerik:GridTemplateColumn>

                                            <telerik:GridTemplateColumn DataField="TariffValue2" SortExpression="TariffValue2" DataType="System.Decimal" DefaultInsertValue="0"
                                                                        UniqueName="TariffValue2" GroupByExpression="TariffValue2 TariffValue2 GROUP BY TariffValue2">
                                                <EditItemTemplate>
                                                    <telerik:RadTextBox runat="server" ID="TariffValue2" Text='<%# Bind("TariffValue2", "{0:#,##0.00}") %>'></telerik:RadTextBox>
                                                </EditItemTemplate>
                                                <ItemTemplate>
                                                    <asp:Label runat="server" ID="TariffValue2" Type="Number" DataType="Decimal" Text='<%# Eval("TariffValue2", "{0:#,##0.00}") %>'></asp:Label>
                                                </ItemTemplate>
                                            </telerik:GridTemplateColumn>

                                            <telerik:GridTemplateColumn DataField="TariffValue3" SortExpression="TariffValue3" DataType="System.Decimal" DefaultInsertValue="0" 
                                                                        UniqueName="TariffValue3" GroupByExpression="TariffValue3 TariffValue3 GROUP BY TariffValue3">
                                                <EditItemTemplate>
                                                    <telerik:RadTextBox runat="server" ID="TariffValue3" Text='<%# Bind("TariffValue3", "{0:#,##0.00}") %>'></telerik:RadTextBox>
                                                </EditItemTemplate>
                                                <ItemTemplate>
                                                    <asp:Label runat="server" ID="TariffValue3" Type="Number" DataType="Decimal" Text='<%# Eval("TariffValue3", "{0:#,##0.00}") %>'></asp:Label>
                                                </ItemTemplate>
                                            </telerik:GridTemplateColumn>

                                            <telerik:GridTemplateColumn DataField="TariffValue4" SortExpression="TariffValue4" DataType="System.Decimal" DefaultInsertValue="0" 
                                                                        UniqueName="TariffValue4" GroupByExpression="TariffValue4 TariffValue4 GROUP BY TariffValue4">
                                                <EditItemTemplate>
                                                    <telerik:RadTextBox runat="server" ID="TariffValue4" Text='<%# Bind("TariffValue4", "{0:#,##0.00}") %>'></telerik:RadTextBox>
                                                </EditItemTemplate>
                                                <ItemTemplate>
                                                    <asp:Label runat="server" ID="TariffValue4" Type="Number" DataType="Decimal" Text='<%# Eval("TariffValue4", "{0:#,##0.00}") %>'></asp:Label>
                                                </ItemTemplate>
                                            </telerik:GridTemplateColumn>

                                            <telerik:GridTemplateColumn DataField="CreatedFrom" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter CreatedFrom column" HeaderText="<%$ Resources:Resource, lblCreatedFrom %>" SortExpression="CreatedFrom" UniqueName="CreatedFrom" Visible="False">
                                                <ItemTemplate>
                                                    <asp:Label ID="CreatedFromLabel" runat="server" Text='<%# Eval("CreatedFrom")%>'></asp:Label>
                                                </ItemTemplate>
                                            </telerik:GridTemplateColumn>

                                            <telerik:GridTemplateColumn DataField="CreatedOn" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter CreatedOn column" HeaderText="<%$ Resources:Resource, lblCreatedOn %>" SortExpression="CreatedOn" UniqueName="CreatedOn" Visible="False">
                                                <ItemTemplate>
                                                    <asp:Label ID="CreatedOnLabel" runat="server" Text='<%# Eval("CreatedOn")%>'></asp:Label>
                                                </ItemTemplate>
                                            </telerik:GridTemplateColumn>

                                            <telerik:GridTemplateColumn DataField="EditFrom" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter EditFrom column" HeaderText="<%$ Resources:Resource, lblEditFrom %>" SortExpression="EditFrom" UniqueName="EditFrom" Visible="False">
                                                <ItemTemplate>
                                                    <asp:Label ID="EditFromLabel" runat="server" Text='<%# Eval("EditFrom")%>'></asp:Label>
                                                </ItemTemplate>
                                            </telerik:GridTemplateColumn>

                                            <telerik:GridTemplateColumn DataField="EditOn" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter EditOn column" HeaderText="<%$ Resources:Resource, lblEditOn %>" SortExpression="EditOn" UniqueName="EditOn" Visible="False">
                                                <ItemTemplate>
                                                    <asp:Label ID="EditOnLabel" runat="server" Text='<%# Eval("EditOn") %>'></asp:Label>
                                                </ItemTemplate>
                                            </telerik:GridTemplateColumn>

                <telerik:GridButtonColumn UniqueName="deleteColumn1" Visible="true" ConfirmText="<%$ Resources:Resource, qstDeleteRow %>" Text="<%$ Resources:Resource, lblActionDelete %>" 
                                          ConfirmDialogType="RadWindow"
                                          ConfirmTitle="<%$ Resources:Resource, lblActionDelete %>" ButtonType="ImageButton" CommandName="Delete" HeaderStyle-Width="30px" ItemStyle-Width="30px">
                    <ItemStyle BackColor="Control" />
                </telerik:GridButtonColumn>
                                        </Columns>
                                    </MasterTableView>
                                </telerik:RadGrid>

                                <asp:SqlDataSource ID="SqlDataSource_TariffData" runat="server" ConnectionString="<%$ ConnectionStrings:Insite_Dev_ConnectionString %>" OnInserted="SqlDataSource_Inserted"
                                                   OldValuesParameterFormatString="original_{0}"
                                                   DeleteCommand="INSERT INTO History_TariffData SELECT * FROM Master_TariffData WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND [TariffContractID] = @original_TariffContractID AND [TariffDataID] = @original_TariffDataID; 
                                                   DELETE FROM [Master_TariffData] WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND [TariffContractID] = @original_TariffContractID AND [TariffDataID] = @original_TariffDataID"
                                                   InsertCommand="INSERT INTO [Master_TariffData] ([SystemID], [BpID], [TariffContractID], [NameVisible], [DescriptionShort], [TariffValue1], [TariffValue2], [TariffValue3], [TariffValue4], [CreatedFrom], [CreatedOn], [EditFrom], [EditOn]) VALUES (@SystemID, @BpID, @TariffContractID, @NameVisible, @DescriptionShort, @TariffValue1, @TariffValue2, @TariffValue3, @TariffValue4, @UserName, SYSDATETIME(), @UserName, SYSDATETIME()) 
                                                   SELECT @ReturnValue = SCOPE_IDENTITY()"
                                                   SelectCommand="SELECT Master_TariffData.SystemID, Master_TariffData.BpID, Master_TariffData.TariffContractID, Master_TariffData.TariffDataID, Master_TariffData.NameVisible, 
                                                   Master_TariffData.DescriptionShort, Master_TariffData.TariffValue1, Master_TariffData.TariffValue2, Master_TariffData.TariffValue3, Master_TariffData.TariffValue4, 
                                                   Master_TariffData.CreatedFrom, Master_TariffData.CreatedOn, Master_TariffData.EditFrom, Master_TariffData.EditOn, Master_TariffContracts.TariffValue1Name, 
                                                   Master_TariffContracts.TariffValue2Name, Master_TariffContracts.TariffValue3Name, Master_TariffContracts.TariffValue4Name
                                                   FROM Master_TariffData INNER JOIN
                                                   Master_TariffContracts ON Master_TariffData.SystemID = Master_TariffContracts.SystemID AND Master_TariffData.BpID = Master_TariffContracts.BpID AND 
                                                   Master_TariffData.TariffContractID = Master_TariffContracts.TariffContractID
                                                   WHERE (Master_TariffData.SystemID = @SystemID) AND (Master_TariffData.BpID = @BpID) AND (Master_TariffData.TariffContractID = @TariffContractID)
                                                   ORDER BY Master_TariffData.NameVisible"
                                                   UpdateCommand="INSERT INTO History_TariffData SELECT * FROM Master_TariffData WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND [TariffContractID] = @original_TariffContractID AND [TariffDataID] = @original_TariffDataID; 
                                                   UPDATE [Master_TariffData] SET [NameVisible] = @NameVisible, [DescriptionShort] = @DescriptionShort, [TariffValue1] = @TariffValue1, [TariffValue2] = @TariffValue2, [TariffValue3] = @TariffValue3, [TariffValue4] = @TariffValue4, [EditFrom] = @UserName, [EditOn] = SYSDATETIME() WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND [TariffContractID] = @original_TariffContractID AND [TariffDataID] = @original_TariffDataID">
                                    <DeleteParameters>
                                        <asp:Parameter Name="original_SystemID" Type="String" />
                                        <asp:Parameter Name="original_BpID" Type="String" />
                                        <asp:Parameter Name="original_TariffContractID" Type="Int32" />
                                        <asp:Parameter Name="original_TariffDataID" Type="Int32" />
                                    </DeleteParameters>
                                    <InsertParameters>
                                        <asp:SessionParameter DefaultValue="0" Name="SystemID" SessionField="SystemID" Type="Int32" />
                                        <asp:SessionParameter DefaultValue="0" Name="BpID" SessionField="BpID" Type="Int32" />
                                        <asp:ControlParameter ControlID="TariffContractID" PropertyName="Value" Type="Int32" Name="TariffContractID"></asp:ControlParameter>
                                        <asp:Parameter Name="NameVisible" Type="String" />
                                        <asp:Parameter Name="DescriptionShort" Type="String" />
                                        <asp:Parameter Name="TariffValue1" Type="Decimal" />
                                        <asp:Parameter Name="TariffValue2" Type="Decimal" />
                                        <asp:Parameter Name="TariffValue3" Type="Decimal" />
                                        <asp:Parameter Name="TariffValue4" Type="Decimal" />
                                        <asp:SessionParameter DefaultValue="" Name="UserName" SessionField="LoginName" Type="String" />
                                        <asp:Parameter Direction="Output" Name="ReturnValue" Type="Int32" />
                                    </InsertParameters>
                                    <SelectParameters>
                                        <asp:SessionParameter DefaultValue="0" Name="SystemID" SessionField="SystemID" Type="Int32" />
                                        <asp:SessionParameter DefaultValue="0" Name="BpID" SessionField="BpID" Type="Int32" />
                                        <asp:ControlParameter ControlID="TariffContractID" PropertyName="Value" Type="Int32" Name="TariffContractID"></asp:ControlParameter>
                                    </SelectParameters>
                                    <UpdateParameters>
                                        <asp:Parameter Name="NameVisible" Type="String" />
                                        <asp:Parameter Name="DescriptionShort" Type="String" />
                                        <asp:Parameter Name="TariffValue1" Type="Decimal" />
                                        <asp:Parameter Name="TariffValue2" Type="Decimal" />
                                        <asp:Parameter Name="TariffValue3" Type="Decimal" />
                                        <asp:Parameter Name="TariffValue4" Type="Decimal" />
                                        <asp:SessionParameter DefaultValue="" Name="UserName" SessionField="LoginName" Type="String" />
                                        <asp:Parameter Name="original_SystemID" Type="String" />
                                        <asp:Parameter Name="original_BpID" Type="String" />
                                        <asp:Parameter Name="original_TariffContractID" Type="Int32" />
                                        <asp:Parameter Name="original_TariffDataID" Type="Int32" />
                                    </UpdateParameters>
                                </asp:SqlDataSource>
                            </telerik:RadPageView>

                            <%-- TariffContract Details --%>
                            <telerik:RadPageView runat="server" ID="PageView1_2">
                                <fieldset style="padding: 10px; width: 500px; margin-left: 10px; margin-bottom: 10px;">
                                    <legend style="padding: 5px; background-color: transparent;">
                                        <b><%# String.Concat(Resources.Resource.lblDetailsFor, " ", Eval("NameVisible"))%></b>
                                    </legend>
                                    <table style="width: 100%;">
                                        <tr>
                                            <td><%= Resources.Resource.lblID%>: </td>
                                            <td>
                                                <asp:Label Text='<%#Eval("TariffContractID")%>' runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><%= Resources.Resource.lblNameVisible%>: </td>
                                            <td>
                                                <asp:Label Text='<%#Eval("NameVisible")%>' runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><%= Resources.Resource.lblDescriptionShort%>: </td>
                                            <td>
                                                <asp:Label Text='<%#Eval("DescriptionShort")%>' runat="server" Width="300px"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><%= Resources.Resource.lblValidFrom%>: </td>
                                            <td>
                                                <asp:Label Text='<%#Eval("ValidFrom")%>' runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><%= Resources.Resource.lblStatus%>: </td>
                                            <td>
                                                <asp:Label Text='<%#Eval("Status")%>' runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><%= String.Format(Resources.Resource.lblTariffXValueHeader, "1") %>: </td>
                                            <td>
                                                <asp:Label Text='<%#Eval("TariffValue1Name")%>' runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><%= String.Format(Resources.Resource.lblTariffXValueHeader, "2") %>: </td>
                                            <td>
                                                <asp:Label Text='<%#Eval("TariffValue2Name")%>' runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><%= String.Format(Resources.Resource.lblTariffXValueHeader, "3") %>: </td>
                                            <td>
                                                <asp:Label Text='<%#Eval("TariffValue3Name")%>' runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><%= String.Format(Resources.Resource.lblTariffXValueHeader, "4") %>: </td>
                                            <td>
                                                <asp:Label Text='<%#Eval("TariffValue4Name")%>' runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>&nbsp; </td>
                                            <td>&nbsp; </td>
                                        </tr>
                                        <tr>
                                            <td><%= Resources.Resource.lblCreatedFrom%>: </td>
                                            <td>
                                                <asp:Label Text='<%#Eval("CreatedFrom")%>' runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><%= Resources.Resource.lblCreatedOn%>: </td>
                                            <td>
                                                <asp:Label Text='<%#Eval("CreatedOn")%>' runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><%= Resources.Resource.lblEditFrom%>: </td>
                                            <td>
                                                <asp:Label Text='<%#Eval("EditFrom")%>' runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><%= Resources.Resource.lblEditOn%>: </td>
                                            <td>
                                                <asp:Label Text='<%#Eval("EditOn")%>' runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                    </table>
                                </fieldset>
                            </telerik:RadPageView>

                        </telerik:RadMultiPage>
                    </asp:Panel>
                </NestedViewTemplate>

                <%-- TariffContract Columns --%>
                <Columns>
                <telerik:GridEditCommandColumn ButtonType="ImageButton" UniqueName="EditCommandColumn" CancelText="<%$ Resources:Resource, lblActionCancel %>" EditText="<%$ Resources:Resource, lblActionEdit %>"
                                               UpdateText="<%$ Resources:Resource, lblActionUpdate %>" Reorderable="false" Resizable="false">
                    <ItemStyle BackColor="Control" Width="30px" />
                    <HeaderStyle Width="30px" />
                </telerik:GridEditCommandColumn>

                    <telerik:GridTemplateColumn DataField="TariffContractID" Visible="false" DataType="System.Int32" FilterControlAltText="Filter TariffContractID column" 
                                                HeaderText="<%$ Resources:Resource, lblID %>" SortExpression="TariffContractID" UniqueName="TariffContractID" InsertVisiblityMode="AlwaysHidden"
                                                GroupByExpression="TariffContractID TariffContractID GROUP BY TariffContractID">
                        <EditItemTemplate>
                            <asp:Label runat="server" ID="LabelTariffContractID" Text='<%# Eval("TariffContractID") %>'></asp:Label>
                        </EditItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="NameVisible" HeaderText="<%$ Resources:Resource, lblNameVisible %>" SortExpression="NameVisible" UniqueName="NameVisible"
                                                GroupByExpression="NameVisible NameVisible GROUP BY NameVisible">
                        <EditItemTemplate>
                            <telerik:RadTextBox runat="server" ID="NameVisible" Text='<%# Bind("NameVisible") %>'></telerik:RadTextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="NameVisible" Text='<%# Eval("NameVisible") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="DescriptionShort" FilterControlAltText="Filter DescriptionShort column" HeaderText="<%$ Resources:Resource, lblDescriptionShort %>"
                                                SortExpression="DescriptionShort" UniqueName="DescriptionShort" GroupByExpression="DescriptionShort DescriptionShort GROUP BY DescriptionShort">
                        <EditItemTemplate>
                            <telerik:RadTextBox runat="server" ID="DescriptionShort" Text='<%# Bind("DescriptionShort") %>' Width="300px"></telerik:RadTextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="LabelDescriptionShort" Text='<%# Eval("DescriptionShort") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="ValidFrom" DataType="System.DateTime" FilterControlAltText="Filter ValidFrom column" HeaderText="<%$ Resources:Resource, lblValidFrom %>"
                                                SortExpression="ValidFrom" UniqueName="ValidFrom" GroupByExpression="ValidFrom ValidFrom GROUP BY ValidFrom">
                        <EditItemTemplate>
                            <telerik:RadDatePicker ID="RadDatePicker1" runat="server" DbSelectedDate='<%# Bind("ValidFrom") %>' MinDate="2010/1/1" MaxDate="2100/1/1" EnableShadows="true"
                                                   ShowPopupOnFocus="true" >
                                <Calendar runat="server">
                                    <FastNavigationSettings CancelButtonCaption="<%$ Resources:Resource, lblActionCancel %>" OkButtonCaption="<%$ Resources:Resource, lblOK %>"
                                                            TodayButtonCaption="<%$ Resources:Resource, lblToday %>">
                                    </FastNavigationSettings>
                                </Calendar>
                            </telerik:RadDatePicker>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="LabelValidFrom" Text='<%# Eval("ValidFrom", "{0:D}") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="Status" HeaderText="<%$ Resources:Resource, lblStatus %>" SortExpression="Status" UniqueName="Status"
                                                GroupByExpression="Status Status GROUP BY Status">
                        <EditItemTemplate>
                            <telerik:RadTextBox runat="server" ID="Status" Text='<%# Bind("Status") %>'></telerik:RadTextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="Status" Text='<%# Eval("Status") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="TariffValue1Name" SortExpression="TariffValue1Name" 
                                                UniqueName="TariffValue1Name" GroupByExpression="TariffValue1Name TariffValue1Name GROUP BY TariffValue1Name">
                        <EditItemTemplate>
                            <telerik:RadTextBox runat="server" ID="TariffValue1Name" Text='<%# Bind("TariffValue1Name") %>'></telerik:RadTextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="TariffValue1Name" Text='<%# Eval("TariffValue1Name") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="TariffValue2Name" SortExpression="TariffValue2Name" 
                                                UniqueName="TariffValue2Name" GroupByExpression="TariffValue2Name TariffValue2Name GROUP BY TariffValue2Name">
                        <EditItemTemplate>
                            <telerik:RadTextBox runat="server" ID="TariffValue2Name" Text='<%# Bind("TariffValue2Name") %>'></telerik:RadTextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="TariffValue2Name" Text='<%# Eval("TariffValue2Name") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="TariffValue3Name" SortExpression="TariffValue3Name" 
                                                UniqueName="TariffValue3Name" GroupByExpression="TariffValue3Name TariffValue3Name GROUP BY TariffValue3Name">
                        <EditItemTemplate>
                            <telerik:RadTextBox runat="server" ID="TariffValue3Name" Text='<%# Bind("TariffValue3Name") %>'></telerik:RadTextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="TariffValue3Name" Text='<%# Eval("TariffValue3Name") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="TariffValue4Name" SortExpression="TariffValue4Name" 
                                                UniqueName="TariffValue4Name" GroupByExpression="TariffValue4Name TariffValue4Name GROUP BY TariffValue4Name">
                        <EditItemTemplate>
                            <telerik:RadTextBox runat="server" ID="TariffValue4Name" Text='<%# Bind("TariffValue4Name") %>'></telerik:RadTextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="TariffValue4Name" Text='<%# Eval("TariffValue4Name") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="CreatedFrom" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter CreatedFrom column" HeaderText="<%$ Resources:Resource, lblCreatedFrom %>" SortExpression="CreatedFrom" UniqueName="CreatedFrom" Visible="False">
                        <ItemTemplate>
                            <asp:Label ID="CreatedFromLabel" runat="server" Text='<%# Eval("CreatedFrom")%>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="CreatedOn" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter CreatedOn column" HeaderText="<%$ Resources:Resource, lblCreatedOn %>" SortExpression="CreatedOn" UniqueName="CreatedOn" Visible="False">
                        <ItemTemplate>
                            <asp:Label ID="CreatedOnLabel" runat="server" Text='<%# Eval("CreatedOn")%>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="EditFrom" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter EditFrom column" HeaderText="<%$ Resources:Resource, lblEditFrom %>" SortExpression="EditFrom" UniqueName="EditFrom" Visible="False">
                        <ItemTemplate>
                            <asp:Label ID="EditFromLabel" runat="server" Text='<%# Eval("EditFrom")%>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="EditOn" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter EditOn column" HeaderText="<%$ Resources:Resource, lblEditOn %>" SortExpression="EditOn" UniqueName="EditOn" Visible="False">
                        <ItemTemplate>
                            <asp:Label ID="EditOnLabel" runat="server" Text='<%# Eval("EditOn") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                <telerik:GridButtonColumn UniqueName="deleteColumn" Visible="true" ConfirmText="<%$ Resources:Resource, qstDeleteRow %>" Text="<%$ Resources:Resource, lblActionDelete %>" 
                                          ConfirmDialogType="RadWindow"
                                          ConfirmTitle="<%$ Resources:Resource, lblActionDelete %>" ButtonType="ImageButton" CommandName="Delete" HeaderStyle-Width="30px" ItemStyle-Width="30px">
                    <ItemStyle BackColor="Control" />
                </telerik:GridButtonColumn>
                </Columns>
            </MasterTableView>

        </telerik:RadGrid>
    </div>

    <asp:SqlDataSource ID="SqlDataSource_TariffContracts" runat="server" ConnectionString="<%$ ConnectionStrings:Insite_Dev_ConnectionString %>" OnInserted="SqlDataSource_Inserted"
                       OldValuesParameterFormatString="original_{0}"
                       DeleteCommand="INSERT INTO History_TariffContracts SELECT * FROM Master_TariffContracts WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND [TariffContractID] = @original_TariffContractID; 
                       DELETE FROM [Master_TariffContracts] WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND [TariffContractID] = @original_TariffContractID"
                       InsertCommand="INSERT INTO [Master_TariffContracts] ([SystemID], [BpID], [NameVisible], [DescriptionShort], [ValidFrom], [Status], [TariffValue1Name], [TariffValue2Name], [TariffValue3Name], [TariffValue4Name], [CreatedFrom], [CreatedOn], [EditFrom], [EditOn]) VALUES (@SystemID, @BpID, @NameVisible, @DescriptionShort, @ValidFrom, @Status, @TariffValue1Name, @TariffValue2Name, @TariffValue3Name, @TariffValue4Name, @UserName, SYSDATETIME(), @UserName, SYSDATETIME()) 
                       SELECT @ReturnValue = SCOPE_IDENTITY()"
                       SelectCommand="SELECT * FROM [Master_TariffContracts] WHERE (([SystemID] = @SystemID) AND ([BpID] = @BpID)) ORDER BY [NameVisible]"
                       UpdateCommand="INSERT INTO History_TariffContracts SELECT * FROM Master_TariffContracts WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND [TariffContractID] = @original_TariffContractID; 
                       UPDATE [Master_TariffContracts] SET [NameVisible] = @NameVisible, [DescriptionShort] = @DescriptionShort, [ValidFrom] = @ValidFrom, [Status] = @Status, [TariffValue1Name] = @TariffValue1Name, [TariffValue2Name] = @TariffValue2Name, [TariffValue3Name] = @TariffValue3Name, [TariffValue4Name] = @TariffValue4Name, [EditFrom] = @UserName, [EditOn] = SYSDATETIME() WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND [TariffContractID] = @original_TariffContractID">
        <DeleteParameters>
            <asp:Parameter Name="original_SystemID" Type="String" />
            <asp:Parameter Name="original_BpID" Type="String" />
            <asp:Parameter Name="original_TariffContractID" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:SessionParameter DefaultValue="0" Name="SystemID" SessionField="SystemID" />
            <asp:SessionParameter DefaultValue="0" Name="BpID" SessionField="BpID" />
            <asp:Parameter Name="NameVisible" Type="String" />
            <asp:Parameter Name="DescriptionShort" Type="String" />
            <asp:Parameter DbType="Date" Name="ValidFrom" />
            <asp:Parameter Name="Status" Type="Int32" />
            <asp:Parameter Name="TariffValue1Name" Type="String" />
            <asp:Parameter Name="TariffValue2Name" Type="String" />
            <asp:Parameter Name="TariffValue3Name" Type="String" />
            <asp:Parameter Name="TariffValue4Name" Type="String" />
            <asp:SessionParameter DefaultValue="" Name="UserName" SessionField="LoginName" Type="String" />
            <asp:Parameter Direction="Output" Name="ReturnValue" Type="Int32" />
        </InsertParameters>
        <SelectParameters>
            <asp:SessionParameter DefaultValue="0" Name="SystemID" SessionField="SystemID" Type="Int32" />
            <asp:SessionParameter DefaultValue="0" Name="BpID" SessionField="BpID" Type="Int32" />
        </SelectParameters>
        <UpdateParameters>
            <asp:Parameter Name="NameVisible" Type="String" />
            <asp:Parameter Name="DescriptionShort" Type="String" />
            <asp:Parameter DbType="Date" Name="ValidFrom" />
            <asp:Parameter Name="Status" Type="Int32" />
            <asp:Parameter Name="TariffValue1Name" Type="String" />
            <asp:Parameter Name="TariffValue2Name" Type="String" />
            <asp:Parameter Name="TariffValue3Name" Type="String" />
            <asp:Parameter Name="TariffValue4Name" Type="String" />
            <asp:Parameter Name="original_SystemID" />
            <asp:Parameter Name="original_BpID" />
            <asp:Parameter Name="original_TariffContractID" />
            <asp:SessionParameter DefaultValue="" Name="UserName" SessionField="LoginName" Type="String" />
        </UpdateParameters>
    </asp:SqlDataSource>
</asp:Content>
