//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Passes
    {
        public int SystemID { get; set; }
        public int BpID { get; set; }
        public int PassID { get; set; }
        public string InternalID { get; set; }
        public string ExternalID { get; set; }
        public string NameVisible { get; set; }
        public string DescriptionShort { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidUntil { get; set; }
        public int EmployeeID { get; set; }
        public int TypeID { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public byte[] FileData { get; set; }
        public byte[] BarcodeData { get; set; }
        public string PrintedFrom { get; set; }
        public Nullable<System.DateTime> PrintedOn { get; set; }
        public string ActivatedFrom { get; set; }
        public Nullable<System.DateTime> ActivatedOn { get; set; }
        public string DeactivatedFrom { get; set; }
        public Nullable<System.DateTime> DeactivatedOn { get; set; }
        public string LockedFrom { get; set; }
        public Nullable<System.DateTime> LockedOn { get; set; }
        public string CreatedFrom { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string EditFrom { get; set; }
        public System.DateTime EditOn { get; set; }
    }
}
