<%@ Page Title="<%$ Resources:Resource, lblQualification %>" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="StaffRoles.aspx.cs" Inherits="InSite.App.Views.Configuration.StaffRoles" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeaderContent" runat="server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="BodyContent" runat="server">
    <telerik:RadPersistenceManagerProxy ID="RadPersistenceManagerProxy1" runat="server">
        <PersistenceSettings>
            <telerik:PersistenceSetting ControlID="RadGrid1" />
        </PersistenceSettings>
    </telerik:RadPersistenceManagerProxy>

    <telerik:RadAjaxManagerProxy ID="AjaxManagerProxy1" runat="server">
        <AjaxSettings>
            <telerik:AjaxSetting AjaxControlID="RadGrid1">
                <UpdatedControls>
                    <telerik:AjaxUpdatedControl ControlID="RadGrid1" LoadingPanelID="RadAjaxLoadingPanelMaster" />
                </UpdatedControls>
            </telerik:AjaxSetting>
        </AjaxSettings>
    </telerik:RadAjaxManagerProxy>

    <div>
        <telerik:RadGrid ID="RadGrid1" runat="server" DataSourceID="SqlDataSource_StaffRoles" AllowPaging="True" AllowSorting="True" AllowAutomaticDeletes="true" AllowAutomaticInserts="true" 
            AllowAutomaticUpdates="true" CssClass="MainGrid" EnableHierarchyExpandAll="true"
            EnableGroupsExpandAll="true"
            OnItemCommand="RadGrid1_ItemCommand" OnItemDeleted="RadGrid1_ItemDeleted" OnItemInserted="RadGrid1_ItemInserted" OnItemUpdated="RadGrid1_ItemUpdated"
            OnPreRender="RadGrid1_PreRender" OnItemCreated="RadGrid1_ItemCreated" OnGroupsChanging="RadGrid1_GroupsChanging">

            <ExportSettings ExportOnlyData="true" IgnorePaging="true">
                <Pdf PaperSize="A4">
                </Pdf>
                <Excel Format="ExcelML" />
            </ExportSettings>

            <ClientSettings AllowColumnsReorder="True" AllowDragToGroup="True" EnableRowHoverStyle="True" EnablePostBackOnRowClick="false">
                <Resizing AllowColumnResize="true"></Resizing>
                <Selecting AllowRowSelect="True" />
                <ClientEvents OnRowClick="OnRowClick" OnGridCreated="OnGridCreated" OnKeyPress="GridKeyPress" />
            </ClientSettings>

        <SortingSettings SortedBackColor="Transparent" />

            <MasterTableView runat="server" DataSourceID="SqlDataSource_StaffRoles" DataKeyNames="SystemID,BpID,StaffRoleID" AutoGenerateColumns="False" CommandItemDisplay="Top"
                             EditMode="PopUp" Name="StaffRoles" ShowHeader="true" CssClass="MasterClass">

                <PagerStyle Mode="NextPrevAndNumeric" AlwaysVisible="true" />

                <SortExpressions>
                    <telerik:GridSortExpression FieldName="NameVisible" SortOrder="Ascending"></telerik:GridSortExpression>
                </SortExpressions>

                <CommandItemSettings ShowRefreshButton="true" ShowAddNewRecordButton="true" ShowExportToCsvButton="False" ShowExportToExcelButton="True" ShowExportToPdfButton="False"
                                     AddNewRecordText="<%$ Resources:Resource, lblActionNew %>" RefreshText="<%$ Resources:Resource, lblActionRefresh %>" />

                <EditFormSettings EditFormType="AutoGenerated" CaptionDataField="NameVisible" CaptionFormatString="{0}">
                    <PopUpSettings Modal="true" ShowCaptionInEditForm="false" ScrollBars="Auto" />
                    <EditColumn ButtonType="ImageButton" UniqueName="EditColumn1" CancelText="<%$ Resources:Resource, lblActionCancel %>"
                                EditText="<%$ Resources:Resource, lblActionEdit %>" UpdateText="<%$ Resources:Resource, lblActionUpdate %>" />
                    <FormTableStyle CellPadding="3" CellSpacing="3" />
                </EditFormSettings>

                <Columns>
                <telerik:GridEditCommandColumn ButtonType="ImageButton" UniqueName="EditCommandColumn" CancelText="<%$ Resources:Resource, lblActionCancel %>" EditText="<%$ Resources:Resource, lblActionEdit %>"
                                               UpdateText="<%$ Resources:Resource, lblActionUpdate %>" Reorderable="false" Resizable="false">
                    <ItemStyle BackColor="Control" Width="30px" />
                    <HeaderStyle Width="30px" />
                </telerik:GridEditCommandColumn>

                    <telerik:GridTemplateColumn DataField="StaffRoleID" Visible="false" InsertVisiblityMode="AlwaysHidden" DataType="System.Int32"
                                                FilterControlAltText="Filter StaffRoleID column" HeaderText="<%$ Resources:Resource, lblID %>"
                                                SortExpression="StaffRoleID" UniqueName="StaffRoleID" GroupByExpression="StaffRoleID StaffRoleID GROUP BY StaffRoleID">
                        <EditItemTemplate>
                            <asp:Label runat="server" ID="LabelEmploymentStatusID" Text='<%# Eval("StaffRoleID") %>'></asp:Label>
                        </EditItemTemplate>
                        <InsertItemTemplate>
                        </InsertItemTemplate>
                        <ItemTemplate>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="NameVisible" HeaderText="<%$ Resources:Resource, lblNameVisible %>" SortExpression="NameVisible" UniqueName="NameVisible"
                                                GroupByExpression="NameVisible NameVisible GROUP BY NameVisible">
                        <EditItemTemplate>
                            <telerik:RadTextBox runat="server" ID="NameVisible" Text='<%# Bind("NameVisible") %>'></telerik:RadTextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="NameVisible" Text='<%# Eval("NameVisible") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="DescriptionShort" FilterControlAltText="Filter DescriptionShort column" HeaderText="<%$ Resources:Resource, lblDescriptionShort %>"
                                                SortExpression="DescriptionShort" UniqueName="DescriptionShort" GroupByExpression="DescriptionShort DescriptionShort GROUP BY DescriptionShort">
                        <EditItemTemplate>
                            <telerik:RadTextBox runat="server" ID="DescriptionShort" Text='<%# Bind("DescriptionShort") %>' Width="300px"></telerik:RadTextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="LabelDescriptionShort" Text='<%# Eval("DescriptionShort") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridCheckBoxColumn DataField="IsVisible" DataType="System.Boolean" FilterControlAltText="Filter IsVisible column" HeaderText="<%$ Resources:Resource, lblVisible %>"
                                                SortExpression="IsVisible" UniqueName="IsVisible" DefaultInsertValue="True">
                    </telerik:GridCheckBoxColumn>

                    <telerik:GridCheckBoxColumn DataField="IsFirstAider" DataType="System.Boolean" FilterControlAltText="Filter IsFirstAider column" HeaderText="<%$ Resources:Resource, lblIsFirstAider %>"
                                                SortExpression="IsFirstAider" UniqueName="IsFirstAider">
                    </telerik:GridCheckBoxColumn>

                    <telerik:GridCheckBoxColumn DataField="IsDisposalExpert" DataType="System.Boolean" FilterControlAltText="Filter IsDisposalExpert column" 
                                                HeaderText="<%$ Resources:Resource, lblDisposalEntitled %>" SortExpression="IsDisposalExpert" UniqueName="IsDisposalExpert">
                    </telerik:GridCheckBoxColumn>

                    <telerik:GridTemplateColumn DataField="CreatedFrom" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter CreatedFrom column" HeaderText="<%$ Resources:Resource, lblCreatedFrom %>" SortExpression="CreatedFrom" UniqueName="CreatedFrom" Visible="False">
                        <ItemTemplate>
                            <asp:Label ID="CreatedFromLabel" runat="server" Text='<%# Eval("CreatedFrom") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="CreatedOn" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter CreatedOn column" HeaderText="<%$ Resources:Resource, lblCreatedOn %>" SortExpression="CreatedOn" UniqueName="CreatedOn" Visible="False">
                        <ItemTemplate>
                            <asp:Label ID="CreatedOnLabel" runat="server" Text='<%# Eval("CreatedOn") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="EditFrom" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter EditFrom column" HeaderText="<%$ Resources:Resource, lblEditFrom %>" SortExpression="EditFrom" UniqueName="EditFrom" Visible="False">
                        <ItemTemplate>
                            <asp:Label ID="EditFromLabel" runat="server" Text='<%# Eval("EditFrom") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="EditOn" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter EditOn column" HeaderText="<%$ Resources:Resource, lblEditOn %>" SortExpression="EditOn" UniqueName="EditOn" Visible="False">
                        <ItemTemplate>
                            <asp:Label ID="EditOnLabel" runat="server" Text='<%# Eval("EditOn") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                <telerik:GridButtonColumn UniqueName="deleteColumn" Visible="true" ConfirmText="<%$ Resources:Resource, qstDeleteRow %>" Text="<%$ Resources:Resource, lblActionDelete %>" 
                                          ConfirmDialogType="RadWindow"
                                          ConfirmTitle="<%$ Resources:Resource, lblActionDelete %>" ButtonType="ImageButton" CommandName="Delete" HeaderStyle-Width="30px" ItemStyle-Width="30px">
                    <ItemStyle BackColor="Control" />
                </telerik:GridButtonColumn>
                </Columns>

                <NestedViewTemplate>
                    <fieldset style="padding: 10px; width: 500px; margin-left: 10px; margin-bottom: 10px;">
                        <legend style="padding: 5px; background-color: transparent;">
                            <b><%= Resources.Resource.lblDetailsFor %> <%#Eval("NameVisible") %></b>
                        </legend>
                        <table style="width: 100%;">
                            <tr>
                                <td><%= Resources.Resource.lblID %>: </td>
                                <td>
                                    <asp:Label Text='<%#Eval("StaffRoleID") %>' runat="server"></asp:Label>
                                </td>
                            </tr>
                            <tr>
                                <td><%= Resources.Resource.lblNameVisible %>: </td>
                                <td>
                                    <asp:Label Text='<%#Eval("NameVisible") %>' runat="server"></asp:Label>
                                </td>
                            </tr>
                            <tr>
                                <td><%= Resources.Resource.lblDescriptionShort %>: </td>
                                <td>
                                    <asp:Label Text='<%#Eval("DescriptionShort") %>' runat="server" Width="300px"></asp:Label>
                                </td>
                            </tr>
                            <tr>
                                <td><%= Resources.Resource.lblVisible %>: </td>
                                <td>
                                    <asp:CheckBox Checked='<%#Eval("IsVisible") %>' runat="server" />
                                </td>
                            </tr>
                            <tr>
                                <td><%= Resources.Resource.lblIsFirstAider %>: </td>
                                <td>
                                    <asp:CheckBox Checked='<%#Eval("IsFirstAider") %>' runat="server" />
                                </td>
                            </tr>
                            <tr>
                                <td><%= Resources.Resource.lblCreatedFrom %>: </td>
                                <td>
                                    <asp:Label Text='<%#Eval("CreatedFrom") %>' runat="server"></asp:Label>
                                </td>
                            </tr>
                            <tr>
                                <td><%= Resources.Resource.lblCreatedOn %>: </td>
                                <td>
                                    <asp:Label Text='<%#Eval("CreatedOn") %>' runat="server"></asp:Label>
                                </td>
                            </tr>
                            <tr>
                                <td><%= Resources.Resource.lblEditFrom %>: </td>
                                <td>
                                    <asp:Label Text='<%#Eval("EditFrom") %>' runat="server"></asp:Label>
                                </td>
                            </tr>
                            <tr>
                                <td><%= Resources.Resource.lblEditOn %>: </td>
                                <td>
                                    <asp:Label Text='<%#Eval("EditOn") %>' runat="server"></asp:Label>
                                </td>
                            </tr>
                        </table>
                    </fieldset>
                </NestedViewTemplate>

            </MasterTableView>
        </telerik:RadGrid>
    </div>

    <asp:SqlDataSource ID="SqlDataSource_StaffRoles" runat="server" ConnectionString="<%$ ConnectionStrings:Insite_Dev_ConnectionString %>" OnInserted="SqlDataSource_Inserted"
        OldValuesParameterFormatString="original_{0}"
        DeleteCommand="INSERT INTO History_StaffRoles SELECT * FROM Master_StaffRoles WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND [StaffRoleID] = @original_StaffRoleID; 
                       DELETE FROM [Master_StaffRoles] WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND [StaffRoleID] = @original_StaffRoleID"
        InsertCommand="INSERT INTO [Master_StaffRoles] ([SystemID], [BpID], [NameVisible], [DescriptionShort], [IsVisible], IsFirstAider, IsDisposalExpert, [CreatedFrom], [CreatedOn], [EditFrom], [EditOn]) VALUES (@SystemID, @BpID, @NameVisible, @DescriptionShort, @IsVisible, @IsFirstAider, @IsDisposalExpert, @UserName, SYSDATETIME(), @UserName, SYSDATETIME()); 
                       SELECT @ReturnValue = SCOPE_IDENTITY()"
        SelectCommand="SELECT * FROM [Master_StaffRoles] WHERE (([SystemID] = @SystemID) AND ([BpID] = @BpID)) ORDER BY [NameVisible]"
        UpdateCommand="INSERT INTO History_StaffRoles SELECT * FROM Master_StaffRoles WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND [StaffRoleID] = @original_StaffRoleID; 
                       UPDATE [Master_StaffRoles] SET [NameVisible] = @NameVisible, [DescriptionShort] = @DescriptionShort, [IsVisible] = @IsVisible, IsFirstAider = @IsFirstAider, IsDisposalExpert = @IsDisposalExpert, [EditFrom] = @UserName, [EditOn] = SYSDATETIME() WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND [StaffRoleID] = @original_StaffRoleID">
        <DeleteParameters>
            <asp:Parameter Name="original_SystemID" Type="Int32" />
            <asp:Parameter Name="original_BpID" Type="Int32" />
            <asp:Parameter Name="original_StaffRoleID" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:SessionParameter DefaultValue="0" Name="SystemID" SessionField="SystemID" Type="Int32" />
            <asp:SessionParameter DefaultValue="0" Name="BpID" SessionField="BpID" Type="Int32" />
            <asp:Parameter Name="NameVisible" Type="String" />
            <asp:Parameter Name="DescriptionShort" Type="String" />
            <asp:Parameter Name="IsVisible" Type="Boolean" />
            <asp:Parameter Name="IsFirstAider" Type="Boolean" />
            <asp:Parameter Name="IsDisposalExpert"></asp:Parameter>
            <asp:SessionParameter DefaultValue="" Name="UserName" SessionField="LoginName" Type="String" />
            <asp:Parameter Name="ReturnValue" />
        </InsertParameters>
        <SelectParameters>
            <asp:SessionParameter DefaultValue="0" Name="SystemID" SessionField="SystemID" Type="Int32" />
            <asp:SessionParameter DefaultValue="0" Name="BpID" SessionField="BpID" Type="Int32" />
        </SelectParameters>
        <UpdateParameters>
            <asp:Parameter Name="original_SystemID" Type="Int32" />
            <asp:Parameter Name="original_BpID" Type="Int32" />
            <asp:Parameter Name="original_StaffRoleID" Type="Int32" />
            <asp:Parameter Name="NameVisible" Type="String" />
            <asp:Parameter Name="DescriptionShort" Type="String"></asp:Parameter>

            <asp:Parameter Name="IsVisible" Type="Boolean" />
            <asp:Parameter Name="IsFirstAider" Type="Boolean" />
            <asp:Parameter Name="IsDisposalExpert" />
            <asp:SessionParameter SessionField="LoginName" DefaultValue="" Name="UserName" Type="String"></asp:SessionParameter>
        </UpdateParameters>
    </asp:SqlDataSource>
</asp:Content>
