//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    
    public partial class GetStatistics_Result
    {
        public int SystemID { get; set; }
        public int BfID { get; set; }
        public int BpID { get; set; }
        public string NameVisible { get; set; }
        public string DescriptionShort { get; set; }
        public string BuilderName { get; set; }
        public System.DateTime StatisticsDate { get; set; }
        public int AssignedEmployees { get; set; }
        public int AccessEventsCount { get; set; }
        public Nullable<System.DateTime> LastCompression { get; set; }
        public Nullable<System.DateTime> LastCorrection { get; set; }
        public int CorrectedEvents { get; set; }
        public int ReplacementPasses { get; set; }
        public int MaximumPresentTime { get; set; }
        public int PresentOvernight { get; set; }
        public Nullable<System.DateTime> SnapshotTimestamp { get; set; }
    }
}
