CREATE TABLE [dbo].[History_Companies] (
    [SystemID]         INT            NOT NULL,
    [BpID]             INT            NOT NULL,
    [CompanyID]        INT NOT NULL,
    [CompanyCentralID] INT NOT NULL DEFAULT 0, 
    [NameVisible]      NVARCHAR (50)  NULL,
    [NameAdditional]      NVARCHAR (50)  NULL,
    [Description] NVARCHAR (2000) NULL,
    [AddressID] INT NOT NULL DEFAULT 0, 
    [ParentID] INT NOT NULL DEFAULT 0, 
    [IsVisible] BIT NOT NULL DEFAULT 1, 
    [IsValid] BIT NOT NULL DEFAULT 1, 
    [TradeAssociation] NVARCHAR(200) NULL, 
    [BlnSOKA] BIT NOT NULL DEFAULT 0, 
    [IsPartner] BIT NOT NULL DEFAULT 0, 
    [RiskAssessment] BIT NOT NULL DEFAULT 0, 
    [MinWageAttestation] BIT NOT NULL DEFAULT 0, 
    [MinWageAccessRelevance] BIT NOT NULL DEFAULT 0, 
    [LockSubContractors] BIT NOT NULL DEFAULT 0, 
    [UserString1] NVARCHAR(50) NULL, 
    [UserString2] NVARCHAR(50) NULL, 
    [UserString3] NVARCHAR(50) NULL, 
    [UserString4] NVARCHAR(50) NULL, 
    [UserBit1] BIT NOT NULL DEFAULT 0, 
    [UserBit2] BIT NOT NULL DEFAULT 0, 
    [UserBit3] BIT NOT NULL DEFAULT 0, 
    [UserBit4] BIT NOT NULL DEFAULT 0, 
    [RegistrationCode] NVARCHAR(20) NULL, 
    [CodeValidUntil] DATETIME NULL, 
	[StatusID] INT NOT NULL DEFAULT 0,
    [PassBudget] DECIMAL(12, 4) NOT NULL DEFAULT 0, 
    [AllowSubcontractorEdit] BIT NOT NULL DEFAULT 0, 
    [RequestFrom] NVARCHAR(50) NULL, 
    [RequestOn] DATETIME NULL , 
    [ReleaseFrom] NVARCHAR(50) NULL, 
    [ReleaseOn] DATETIME NULL , 
    [LockedFrom] NVARCHAR(50) NULL, 
    [LockedOn] DATETIME NULL , 
    [CreatedFrom]      NVARCHAR (50)  NULL,
    [CreatedOn]        DATETIME       DEFAULT (sysdatetime()) NOT NULL,
    [EditFrom]         NVARCHAR (50)  NULL,
    [EditOn]           DATETIME       DEFAULT (sysdatetime()) NOT NULL,
    CONSTRAINT [PK_History_M_Companies] PRIMARY KEY CLUSTERED ([CompanyID], [SystemID], [BpID], [EditOn])
);
