//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    
    public partial class GetEmployeeWageGroups_Result
    {
        public int TariffWageGroupID { get; set; }
        public string NameVisible { get; set; }
        public string DescriptionShort { get; set; }
        public System.DateTime ValidFrom { get; set; }
    }
}
