//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    
    public partial class GetExpiringTariffs_Result
    {
        public int SystemID { get; set; }
        public int TariffID { get; set; }
        public int TariffContractID { get; set; }
        public string TariffName { get; set; }
        public string TariffContractName { get; set; }
        public System.DateTime ValidTo { get; set; }
    }
}
