//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    
    public partial class GetPresenceDataNow_Result
    {
        public int SystemID { get; set; }
        public int BpID { get; set; }
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public int TradeID { get; set; }
        public string TradeNumber { get; set; }
        public string TradeName { get; set; }
        public Nullable<System.DateTime> PresenceDay { get; set; }
        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> AccessAt { get; set; }
        public Nullable<System.DateTime> ExitAt { get; set; }
        public int PresenceSeconds { get; set; }
        public int AccessAreaID { get; set; }
        public string AccessAreaName { get; set; }
        public int EmploymentStatusID { get; set; }
        public string EmploymentStatusName { get; set; }
        public string TreeLevel { get; set; }
        public Nullable<int> IndentLevel { get; set; }
        public Nullable<int> IsPresent { get; set; }
        public int PassType { get; set; }
        public Nullable<bool> IsFirstAider { get; set; }
        public string Qualification { get; set; }
    }
}
