//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    
    public partial class GetPassPrintData_Result
    {
        public int SystemID { get; set; }
        public int BpID { get; set; }
        public int EmployeeID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyNameAdditional { get; set; }
        public string ClientName { get; set; }
        public string ClientNameAdditional { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmployeeName { get; set; }
        public byte[] PhotoData { get; set; }
        public string CountryName { get; set; }
        public string InternalID { get; set; }
        public string ExternalID { get; set; }
        public string BuildingProjectName { get; set; }
        public string TradeName { get; set; }
        public Nullable<System.DateTime> PrintedOn { get; set; }
        public int PassID { get; set; }
        public bool MWObligate { get; set; }
        public string PassCaseName { get; set; }
        public bool WillBeCharged { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string TradeColor { get; set; }
        public string EmployeeColor { get; set; }
        public byte[] BarcodeData { get; set; }
        public string StaffFunction { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string EmploymentStatus { get; set; }
        public bool UserBit1 { get; set; }
        public bool UserBit2 { get; set; }
        public bool UserBit3 { get; set; }
        public bool UserBit4 { get; set; }
        public string UserString1 { get; set; }
        public string UserString2 { get; set; }
        public string UserString3 { get; set; }
        public string UserString4 { get; set; }
        public string AttributeName { get; set; }
        public string AttributeDescription { get; set; }
        public Nullable<int> MainContractorID { get; set; }
        public string MainContractorName { get; set; }
    }
}
