CREATE PROCEDURE [dbo].[CreateTablesColumnsCatalog]

AS

-- Tabellen
INSERT INTO System_Tables
(
	TABLE_CATALOG, 
	TABLE_SCHEMA, 
	TABLE_NAME
)
SELECT        
	i_s_t.TABLE_CATALOG, 
	i_s_t.TABLE_SCHEMA, 
	i_s_t.TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES i_s_t
WHERE NOT EXISTS (
					SELECT 1 FROM System_Tables s_t
					WHERE s_t.TABLE_CATALOG = i_s_t.TABLE_CATALOG
						AND s_t.TABLE_SCHEMA = i_s_t.TABLE_SCHEMA
						AND s_t.TABLE_NAME = i_s_t.TABLE_NAME
				 )

-- Spalten
INSERT INTO System_Tables_Columns
(
	TABLE_CATALOG, 
	TABLE_SCHEMA, 
	TABLE_NAME, 
	COLUMN_NAME, 
	ORDINAL_POSITION, 
	COLUMN_DEFAULT, 
	IS_NULLABLE, 
	DATA_TYPE, 
	CHARACTER_MAXIMUM_LENGTH, 
	CHARACTER_OCTET_LENGTH, 
	NUMERIC_PRECISION, 
	NUMERIC_PRECISION_RADIX, 
	NUMERIC_SCALE, 
	DATETIME_PRECISION, 
	CHARACTER_SET_CATALOG, 
	CHARACTER_SET_SCHEMA, 
	CHARACTER_SET_NAME, 
	COLLATION_CATALOG, 
	COLLATION_SCHEMA, 
	COLLATION_NAME, 
	DOMAIN_CATALOG, 
	DOMAIN_SCHEMA, 
	DOMAIN_NAME
)
SELECT        
	TABLE_CATALOG, 
	TABLE_SCHEMA, 
	TABLE_NAME, 
	COLUMN_NAME, 
	ORDINAL_POSITION, 
	COLUMN_DEFAULT, 
	IS_NULLABLE, 
	DATA_TYPE, 
	CHARACTER_MAXIMUM_LENGTH, 
	CHARACTER_OCTET_LENGTH, 
	NUMERIC_PRECISION, 
	NUMERIC_PRECISION_RADIX, 
	NUMERIC_SCALE, 
	DATETIME_PRECISION, 
	CHARACTER_SET_CATALOG, 
	CHARACTER_SET_SCHEMA, 
	CHARACTER_SET_NAME, 
	COLLATION_CATALOG, 
	COLLATION_SCHEMA, 
	COLLATION_NAME, 
	DOMAIN_CATALOG, 
	DOMAIN_SCHEMA, 
	DOMAIN_NAME
FROM INFORMATION_SCHEMA.COLUMNS AS i_s_c
WHERE NOT EXISTS (
					SELECT 1 FROM System_Tables_Columns s_t_c
					WHERE s_t_c.TABLE_CATALOG = i_s_c.TABLE_CATALOG
						AND s_t_c.TABLE_SCHEMA = i_s_c.TABLE_SCHEMA
						AND s_t_c.TABLE_NAME = i_s_c.TABLE_NAME
						AND s_t_c.COLUMN_NAME = i_s_c.COLUMN_NAME
						AND s_t_c.ORDINAL_POSITION = i_s_c.ORDINAL_POSITION
				 )