CREATE TABLE [dbo].[Data_ShortTermPasses]
(
    [SystemID]         INT            NOT NULL,
    [BpID]             INT            NOT NULL,
    [ShortTermPassID]           INT            IDENTITY (1, 1) NOT NULL,
    [ShortTermPassTypeID]           INT        NOT NULL,
    [StatusID] INT NOT NULL DEFAULT 0, 
    [InternalID] NVARCHAR(50) NULL, 
    [ExternalID] NVARCHAR(50) NULL, 
    [ShortTermVisitorID] INT NULL, 
    [PrintID] INT NULL, 
    [BarcodeData] IMAGE NULL, 
    [PrintedFrom] NVARCHAR(50) NULL, 
    [PrintedOn] DATETIME NULL, 
    [AssignedFrom] NVARCHAR(50) NULL, 
    [AssignedOn] DATETIME NULL, 
    [ActivatedFrom] NVARCHAR(50) NULL, 
    [ActivatedOn] DATETIME NULL, 
    [DeactivatedFrom] NVARCHAR(50) NULL, 
    [DeactivatedOn] DATETIME NULL, 
    [LockedFrom] NVARCHAR(50) NULL, 
    [LockedOn] DATETIME NULL, 
    [CreatedFrom]      NVARCHAR (50)  NULL,
    [CreatedOn]        DATETIME DEFAULT (sysdatetime()) NOT NULL,
    [EditFrom]         NVARCHAR (50)  NULL,
    [EditOn]           DATETIME DEFAULT (sysdatetime()) NOT NULL, 
    CONSTRAINT [PK_Data_ShortTermPasses] PRIMARY KEY ([SystemID], [BpID], [ShortTermPassID]),
)
