//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    
    public partial class GetPresentPersonsCount_Result
    {
        public int EmployeesCount { get; set; }
        public int VisitorCount { get; set; }
        public int EmployeesFaultyCount { get; set; }
        public int VisitorFaultyCount { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<System.DateTime> LastAccess { get; set; }
        public Nullable<System.DateTime> LastExit { get; set; }
    }
}
