//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_UserControlStates
    {
        public int SystemID { get; set; }
        public int UserID { get; set; }
        public string UserKey { get; set; }
        public string UserSettings { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
