//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_AccessRightEvents
    {
        public int SystemID { get; set; }
        public int BpID { get; set; }
        public int AccessRightEventID { get; set; }
        public int PassID { get; set; }
        public int PassType { get; set; }
        public string ExternalID { get; set; }
        public int OwnerID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> ValidUntil { get; set; }
        public bool AccessAllowed { get; set; }
        public string AccessDenialReason { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> MessageFrom { get; set; }
        public Nullable<System.DateTime> MessageUntil { get; set; }
        public bool IsDelivered { get; set; }
        public Nullable<System.DateTime> DeliveredAt { get; set; }
        public string DeliveryMessage { get; set; }
        public bool IsNewest { get; set; }
        public bool HasSubstitute { get; set; }
        public string CreatedFrom { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string EditFrom { get; set; }
        public System.DateTime EditOn { get; set; }
    }
}
