//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_Logging
    {
        public long LoggingID { get; set; }
        public Nullable<int> SystemID { get; set; }
        public Nullable<int> BpID { get; set; }
        public System.DateTime Date { get; set; }
        public string Thread { get; set; }
        public string Level { get; set; }
        public string Logger { get; set; }
        public string Message { get; set; }
        public string Exception { get; set; }
        public string SessionID { get; set; }
        public Nullable<int> DialogID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ActionID { get; set; }
        public string RefID { get; set; }
    }
}
