//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_ProcessEvents
    {
        public int SystemID { get; set; }
        public int ProcessEventID { get; set; }
        public int BpID { get; set; }
        public int CompanyCentralID { get; set; }
        public int UserIDInitiator { get; set; }
        public int UserIDExecutive { get; set; }
        public string NameVisible { get; set; }
        public string ResourceID { get; set; }
        public string DescriptionShort { get; set; }
        public int TypeID { get; set; }
        public int DialogID { get; set; }
        public int ActionID { get; set; }
        public int RefID { get; set; }
        public int StatusID { get; set; }
        public string ProcessUrl { get; set; }
        public string DoneFrom { get; set; }
        public Nullable<System.DateTime> DoneOn { get; set; }
        public string CreatedFrom { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string EditFrom { get; set; }
        public System.DateTime EditOn { get; set; }
    }
}
