//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_RelevantDocuments
    {
        public int SystemID { get; set; }
        public int BpID { get; set; }
        public int RelevantDocumentID { get; set; }
        public byte RelevantFor { get; set; }
        public string NameVisible { get; set; }
        public string DescriptionShort { get; set; }
        public bool IsAccessRelevant { get; set; }
        public bool RecExpirationDate { get; set; }
        public bool RecIDNumber { get; set; }
        public string SampleFileName { get; set; }
        public byte[] SampleData { get; set; }
        public string CreatedFrom { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string EditFrom { get; set; }
        public System.DateTime EditOn { get; set; }
    }
}
