//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Rights
    {
        public int SystemID { get; set; }
        public int BpID { get; set; }
        public int RightID { get; set; }
        public int RefID1 { get; set; }
        public int RefID2 { get; set; }
        public int RefID3 { get; set; }
        public string NameInternal { get; set; }
        public bool IsValid { get; set; }
        public string CreatedFrom { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string EditFrom { get; set; }
        public System.DateTime EditOn { get; set; }
    }
}
