//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_CostLocations
    {
        public int SystemID { get; set; }
        public int BpID { get; set; }
        public int CostLocationID { get; set; }
        public string CostLocationNumber { get; set; }
        public string NameVisible { get; set; }
        public string DescriptionShort { get; set; }
        public byte TypeID { get; set; }
        public bool IsVisible { get; set; }
        public string CreatedFrom { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string EditFrom { get; set; }
        public System.DateTime EditOn { get; set; }
    }
}
