//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_TariffData
    {
        public int SystemID { get; set; }
        public int BpID { get; set; }
        public int TariffContractID { get; set; }
        public int TariffDataID { get; set; }
        public string NameVisible { get; set; }
        public string DescriptionShort { get; set; }
        public decimal TariffValue1 { get; set; }
        public decimal TariffValue2 { get; set; }
        public decimal TariffValue3 { get; set; }
        public decimal TariffValue4 { get; set; }
        public string CreatedFrom { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string EditFrom { get; set; }
        public System.DateTime EditOn { get; set; }
    }
}
