//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_TreeNodes
    {
        public int SystemID { get; set; }
        public int NodeID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int DialogID { get; set; }
        public string NameVisible { get; set; }
        public string DescriptionShort { get; set; }
        public string ResourceID { get; set; }
        public string ContextMenuID { get; set; }
        public string NodeUrl { get; set; }
        public int ImageID { get; set; }
        public int RefID { get; set; }
        public int RefType { get; set; }
        public byte IsVisible { get; set; }
        public byte IsValid { get; set; }
        public int Rank { get; set; }
        public byte NeededTypeID { get; set; }
    }
}
