//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Languages
    {
        public string CultureID { get; set; }
        public string CultureName { get; set; }
        public string FlagName { get; set; }
        public string CountryID { get; set; }
        public string CountryName { get; set; }
        public string LanguageID { get; set; }
        public string LanguageName { get; set; }
    }
}
