//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_SessionLog
    {
        public string SessionID { get; set; }
        public Nullable<int> SystemID { get; set; }
        public Nullable<int> UserID { get; set; }
        public System.DateTime FirstUsed { get; set; }
        public Nullable<System.DateTime> LastUsed { get; set; }
        public int SessionState { get; set; }
    }
}
