//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Jobs
    {
        public int SystemID { get; set; }
        public int JobID { get; set; }
        public string NameVisible { get; set; }
        public string Description { get; set; }
        public int JobType { get; set; }
        public int BpID { get; set; }
        public int UserID { get; set; }
        public int Frequency { get; set; }
        public int RepeatEvery { get; set; }
        public string ValidDays { get; set; }
        public int DayOfMonth { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.DateTime> NextStart { get; set; }
        public Nullable<System.DateTime> Started { get; set; }
        public Nullable<System.DateTime> Terminated { get; set; }
        public int StatusID { get; set; }
        public string TerminationMessage { get; set; }
        public string JobUrl { get; set; }
        public string JobParameter { get; set; }
        public string JobLanguage { get; set; }
        public string Receiver { get; set; }
        public string CreatedFrom { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string EditFrom { get; set; }
        public System.DateTime EditOn { get; set; }
    }
}
