//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Dialogs
    {
        public int SystemID { get; set; }
        public int DialogID { get; set; }
        public byte TypeID { get; set; }
        public string NameVisible { get; set; }
        public string DescriptionShort { get; set; }
        public string ResourceID { get; set; }
        public string PageName { get; set; }
        public bool IsVisible { get; set; }
        public bool UseFieldRights { get; set; }
        public bool TranslationOnly { get; set; }
        public bool UseReportingServer { get; set; }
    }
}
