//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Fields
    {
        public int SystemID { get; set; }
        public int DialogID { get; set; }
        public int FieldID { get; set; }
        public string InternalName { get; set; }
        public string ResourceID { get; set; }
        public byte TypeID { get; set; }
        public bool IsVisible { get; set; }
        public bool IsMandatory { get; set; }
        public string DefaultValue { get; set; }
        public bool HasVariables { get; set; }
    }
}
