<%@ Page Title="<%$ Resources:Resource, lblReplacementPassCases %>" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ReplacementPassCases.aspx.cs" Inherits="InSite.App.Views.Configuration.ReplacementPassCases" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeaderContent" runat="server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="BodyContent" runat="server">
    <telerik:RadPersistenceManagerProxy ID="RadPersistenceManagerProxy1" runat="server">
        <PersistenceSettings>
            <telerik:PersistenceSetting ControlID="RadGrid1" />
        </PersistenceSettings>
    </telerik:RadPersistenceManagerProxy>

    <telerik:RadAjaxManagerProxy ID="AjaxManagerProxy1" runat="server">
        <AjaxSettings>
            <telerik:AjaxSetting AjaxControlID="RadGrid1">
                <UpdatedControls>
                    <telerik:AjaxUpdatedControl ControlID="RadGrid1" LoadingPanelID="RadAjaxLoadingPanelMaster" />
                </UpdatedControls>
            </telerik:AjaxSetting>
        </AjaxSettings>
    </telerik:RadAjaxManagerProxy>

    <div>
        <telerik:RadGrid ID="RadGrid1" runat="server" DataSourceID="SqlDataSource_ReplacementPassCases" AllowPaging="True" AllowSorting="True" AllowAutomaticDeletes="true" AllowAutomaticInserts="true" 
                         AllowAutomaticUpdates="true" CssClass="MainGrid" EnableHierarchyExpandAll="true"
                         EnableGroupsExpandAll="true"
                         OnItemCommand="RadGrid1_ItemCommand" OnItemDeleted="RadGrid1_ItemDeleted" OnItemInserted="RadGrid1_ItemInserted" OnItemUpdated="RadGrid1_ItemUpdated"
                         OnPreRender="RadGrid1_PreRender" OnItemCreated="RadGrid1_ItemCreated" OnGroupsChanging="RadGrid1_GroupsChanging" Culture="de-DE" GroupPanelPosition="Top">

            <ExportSettings ExportOnlyData="true" IgnorePaging="true">
                <Pdf PaperSize="A4">
                </Pdf>
                <Excel Format="ExcelML" />
            </ExportSettings>

            <ClientSettings AllowColumnsReorder="True" AllowDragToGroup="True" EnableRowHoverStyle="True" EnablePostBackOnRowClick="false">
                <Resizing AllowColumnResize="true"></Resizing>
                <Selecting AllowRowSelect="True" />
                <ClientEvents OnRowClick="OnRowClick" OnGridCreated="OnGridCreated" OnKeyPress="GridKeyPress" />
            </ClientSettings>

        <SortingSettings SortedBackColor="Transparent" />

            <MasterTableView runat="server" DataSourceID="SqlDataSource_ReplacementPassCases" DataKeyNames="SystemID,BpID,ReplacementPassCaseID" AutoGenerateColumns="False"
                             CommandItemDisplay="Top" EditMode="PopUp" Name="ReplacementPassCases" ShowHeader="true" CssClass="MasterClass" TableLayout="Auto">

                <PagerStyle Mode="NextPrevAndNumeric" AlwaysVisible="true" />

                <SortExpressions>
                    <telerik:GridSortExpression FieldName="NameVisible" SortOrder="Ascending"></telerik:GridSortExpression>
                </SortExpressions>

                <CommandItemSettings ShowRefreshButton="true" ShowAddNewRecordButton="true" ShowExportToCsvButton="False" ShowExportToExcelButton="True" ShowExportToPdfButton="False"
                                     AddNewRecordText="<%$ Resources:Resource, lblActionNew %>" RefreshText="<%$ Resources:Resource, lblActionRefresh %>" />

                <EditFormSettings EditFormType="AutoGenerated" CaptionDataField="NameVisible" CaptionFormatString="{0}">
                    <PopUpSettings Modal="true" ShowCaptionInEditForm="false" ScrollBars="Auto" />
                    <EditColumn ButtonType="ImageButton" UniqueName="EditColumn1" CancelText="<%$ Resources:Resource, lblActionCancel %>"
                                EditText="<%$ Resources:Resource, lblActionEdit %>" UpdateText="<%$ Resources:Resource, lblActionUpdate %>" />
                    <FormTableStyle CellPadding="3" CellSpacing="3" />
                </EditFormSettings>

                <NestedViewTemplate>
                    <fieldset style="padding: 10px; width: 500px; margin-left: 10px; margin-bottom: 10px;">
                        <legend style="padding: 5px; background-color: transparent;">
                            <b><%= Resources.Resource.lblDetailsFor %> <%#Eval("NameVisible") %></b>
                        </legend>
                        <table style="width: 100%;">
                            <tr>
                                <td><%= Resources.Resource.lblID %>: </td>
                                <td>
                                    <asp:Label Text='<%#Eval("ReplacementPassCaseID") %>' runat="server"></asp:Label>
                                </td>
                            </tr>
                            <tr>
                                <td><%= Resources.Resource.lblNameVisible %>: </td>
                                <td>
                                    <asp:Label Text='<%#Eval("NameVisible") %>' runat="server"></asp:Label>
                                </td>
                            </tr>
                            <tr>
                                <td><%= Resources.Resource.lblDescriptionShort %>: </td>
                                <td>
                                    <asp:Label Text='<%#Eval("DescriptionShort") %>' runat="server" Width="300px"></asp:Label>
                                </td>
                            </tr>
                            <tr>
                                <td><%= Resources.Resource.lblWillBeCharged %>: </td>
                                <td>
                                    <asp:CheckBox Checked='<%#Eval("WillBeCharged") %>' runat="server" />
                                </td>
                            </tr>
                            <tr>
                                <td><%= Resources.Resource.lblCost %>: </td>
                                <td>
                                    <asp:Label Text='<%# String.Concat(Eval("Cost", "{0:#,##0.00}"), " ", Eval("Currency")) %>' runat="server"></asp:Label>
                                </td>
                            </tr>
                            <tr>
                                <td><%= Resources.Resource.lblInvoiceTo %>: </td>
                                <td>
                                    <asp:Label Text='<%#Eval("InvoiceTo") %>' runat="server"></asp:Label>
                                </td>
                            </tr>
                            <tr>
                                <td><%= Resources.Resource.lblOldPassInvalid %>: </td>
                                <td>
                                    <asp:CheckBox Checked='<%#Eval("OldPassInvalid") %>' runat="server" />
                                </td>
                            </tr>
                            <tr>
                                <td><%= Resources.Resource.lblCreditForOldPass %>: </td>
                                <td>
                                    <asp:CheckBox Checked='<%#Eval("CreditForOldPass") %>' runat="server" />
                                </td>
                            </tr>
                            <tr>
                                <td><%= Resources.Resource.lblIsInitialIssue %>: </td>
                                <td>
                                    <asp:CheckBox Checked='<%#Eval("IsInitialIssue") %>' runat="server" />
                                </td>
                            </tr>
                            <tr>
                                <td>&nbsp; </td>
                                <td>&nbsp; </td>
                            </tr>
                            <tr>
                                <td><%= Resources.Resource.lblCreatedFrom %>: </td>
                                <td>
                                    <asp:Label Text='<%#Eval("CreatedFrom") %>' runat="server"></asp:Label>
                                </td>
                            </tr>
                            <tr>
                                <td><%= Resources.Resource.lblCreatedOn %>: </td>
                                <td>
                                    <asp:Label Text='<%#Eval("CreatedOn") %>' runat="server"></asp:Label>
                                </td>
                            </tr>
                            <tr>
                                <td><%= Resources.Resource.lblEditFrom %>: </td>
                                <td>
                                    <asp:Label Text='<%#Eval("EditFrom") %>' runat="server"></asp:Label>
                                </td>
                            </tr>
                            <tr>
                                <td><%= Resources.Resource.lblEditOn %>: </td>
                                <td>
                                    <asp:Label Text='<%#Eval("EditOn") %>' runat="server"></asp:Label>
                                </td>
                            </tr>
                        </table>
                    </fieldset>
                </NestedViewTemplate>

                <Columns>
                <telerik:GridEditCommandColumn ButtonType="ImageButton" UniqueName="EditCommandColumn" CancelText="<%$ Resources:Resource, lblActionCancel %>" EditText="<%$ Resources:Resource, lblActionEdit %>"
                                               UpdateText="<%$ Resources:Resource, lblActionUpdate %>" Reorderable="false" Resizable="false">
                    <ItemStyle BackColor="Control" Width="30px" />
                    <HeaderStyle Width="30px" />
                </telerik:GridEditCommandColumn>

                    <telerik:GridTemplateColumn DataField="ReplacementPassCaseID" Visible="false" InsertVisiblityMode="AlwaysHidden" DataType="System.Int32"
                                                FilterControlAltText="Filter ShortTermPassTypeID column" HeaderText="<%$ Resources:Resource, lblID %>"
                                                SortExpression="ReplacementPassCaseID" UniqueName="ReplacementPassCaseID"
                                                GroupByExpression="ReplacementPassCaseID ReplacementPassCaseID GROUP BY ReplacementPassCaseID">
                        <EditItemTemplate>
                            <asp:Label runat="server" ID="LabelReplacementPassCaseID" Text='<%# Eval("ReplacementPassCaseID") %>'></asp:Label>
                        </EditItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="NameVisible" HeaderText="<%$ Resources:Resource, lblNameVisible %>" SortExpression="NameVisible" UniqueName="NameVisible"
                                                GroupByExpression="NameVisible NameVisible GROUP BY NameVisible">
                        <EditItemTemplate>
                            <telerik:RadTextBox runat="server" ID="NameVisible" Text='<%# Bind("NameVisible") %>'></telerik:RadTextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="NameVisible" Text='<%# Eval("NameVisible") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="DescriptionShort" FilterControlAltText="Filter DescriptionShort column" HeaderText="<%$ Resources:Resource, lblDescriptionShort %>"
                                                SortExpression="DescriptionShort" UniqueName="DescriptionShort" GroupByExpression="DescriptionShort DescriptionShort GROUP BY DescriptionShort">
                        <EditItemTemplate>
                            <telerik:RadTextBox runat="server" ID="DescriptionShort" Text='<%# Bind("DescriptionShort") %>' Width="300px"></telerik:RadTextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="LabelDescriptionShort" Text='<%# Eval("DescriptionShort") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridCheckBoxColumn DataField="WillBeCharged" DataType="System.Boolean" FilterControlAltText="Filter WillBeCharged column" 
                                                HeaderText="<%$ Resources:Resource, lblWillBeCharged %>" SortExpression="WillBeCharged" UniqueName="WillBeCharged" DefaultInsertValue="True">
                    </telerik:GridCheckBoxColumn>

                    <telerik:GridTemplateColumn DataField="Cost" DataType="System.Decimal" HeaderText="<%$ Resources:Resource, lblCost %>" SortExpression="Cost" UniqueName="Cost"
                                                GroupByExpression="Cost NameVisible Cost BY Cost">
                        <EditItemTemplate>
                            <telerik:RadTextBox runat="server" Type="Number" DataType="Decimal" Culture="de-DE" ID="Cost" Text='<%# Bind("Cost", "{0:#,##0.00}") %>'>
                            </telerik:RadTextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="Cost" Text='<%# Eval("Cost", "{0:#,##0.00}") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridDropDownColumn DataField="Currency" DataSourceID="SqlDataSource_Currencies" HeaderText="<%$ Resources:Resource, lblCurrency %>" ListTextField="Currency"
                                                ListValueField="ISO_Alphabetic" UniqueName="Currency" DropDownControlType="RadComboBox" DefaultInsertValue="EUR" InsertVisiblityMode="AlwaysVisible">
                    </telerik:GridDropDownColumn>

                    <telerik:GridTemplateColumn DataField="InvoiceTo" FilterControlAltText="Filter InvoiceTo column" HeaderText="<%$ Resources:Resource, lblInvoiceTo %>"
                                                SortExpression="InvoiceTo" UniqueName="InvoiceTo" GroupByExpression="InvoiceTo InvoiceTo GROUP BY InvoiceTo">
                        <EditItemTemplate>
                            <telerik:RadTextBox runat="server" ID="InvoiceTo" Text='<%# Bind("InvoiceTo") %>' Width="300px"></telerik:RadTextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="LabelInvoiceTo" Text='<%# Eval("InvoiceTo") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridCheckBoxColumn DataField="OldPassInvalid" DataType="System.Boolean" FilterControlAltText="Filter OldPassInvalid column" 
                                                HeaderText="<%$ Resources:Resource, lblOldPassInvalid %>" SortExpression="OldPassInvalid" UniqueName="OldPassInvalid" DefaultInsertValue="True">
                    </telerik:GridCheckBoxColumn>

                    <telerik:GridCheckBoxColumn DataField="CreditForOldPass" DataType="System.Boolean" FilterControlAltText="Filter CreditForOldPass column" 
                                                HeaderText="<%$ Resources:Resource, lblCreditForOldPass %>" SortExpression="CreditForOldPass" UniqueName="CreditForOldPass" DefaultInsertValue="False">
                    </telerik:GridCheckBoxColumn>

                    <telerik:GridCheckBoxColumn DataField="IsInitialIssue" DataType="System.Boolean" FilterControlAltText="Filter IsInitialIssue column" 
                                                HeaderText="<%$ Resources:Resource, lblIsInitialIssue %>" SortExpression="IsInitialIssue" UniqueName="IsInitialIssue" 
                                                DefaultInsertValue="False">
                    </telerik:GridCheckBoxColumn>

                    <telerik:GridTemplateColumn DataField="CreatedFrom" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter CreatedFrom column" HeaderText="<%$ Resources:Resource, lblCreatedFrom %>" SortExpression="CreatedFrom" UniqueName="CreatedFrom" Visible="False">
                        <ItemTemplate>
                            <asp:Label ID="CreatedFromLabel" runat="server" Text='<%# Eval("CreatedFrom") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="CreatedOn" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter CreatedOn column" HeaderText="<%$ Resources:Resource, lblCreatedOn %>" SortExpression="CreatedOn" UniqueName="CreatedOn" Visible="False">
                        <ItemTemplate>
                            <asp:Label ID="CreatedOnLabel" runat="server" Text='<%# Eval("CreatedOn") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="EditFrom" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter EditFrom column" HeaderText="<%$ Resources:Resource, lblEditFrom %>" SortExpression="EditFrom" UniqueName="EditFrom" Visible="False">
                        <ItemTemplate>
                            <asp:Label ID="EditFromLabel" runat="server" Text='<%# Eval("EditFrom") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="EditOn" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter EditOn column" HeaderText="<%$ Resources:Resource, lblEditOn %>" SortExpression="EditOn" UniqueName="EditOn" Visible="False">
                        <ItemTemplate>
                            <asp:Label ID="EditOnLabel" runat="server" Text='<%# Eval("EditOn") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                <telerik:GridButtonColumn UniqueName="deleteColumn" Visible="true" ConfirmText="<%$ Resources:Resource, qstDeleteRow %>" Text="<%$ Resources:Resource, lblActionDelete %>" 
                                          ConfirmDialogType="RadWindow"
                                          ConfirmTitle="<%$ Resources:Resource, lblActionDelete %>" ButtonType="ImageButton" CommandName="Delete" HeaderStyle-Width="30px" ItemStyle-Width="30px">
                    <ItemStyle BackColor="Control" />
                </telerik:GridButtonColumn>
                </Columns>
            </MasterTableView>
        </telerik:RadGrid>
    </div>

    <asp:SqlDataSource ID="SqlDataSource_ReplacementPassCases" runat="server" ConnectionString="<%$ ConnectionStrings:Insite_Dev_ConnectionString %>" OnInserted="SqlDataSource_Inserted"
                       OldValuesParameterFormatString="original_{0}"
                       DeleteCommand="INSERT INTO History_ReplacementPassCases SELECT * FROM Master_ReplacementPassCases WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND [ReplacementPassCaseID] = @original_ReplacementPassCaseID; 
                       DELETE FROM [Master_ReplacementPassCases] WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND [ReplacementPassCaseID] = @original_ReplacementPassCaseID"
                       InsertCommand="INSERT INTO [Master_ReplacementPassCases] ([SystemID], [BpID], [NameVisible], [DescriptionShort], [WillBeCharged], [Cost], Currency, [InvoiceTo], [OldPassInvalid], [CreditForOldPass], IsInitialIssue, [CreatedFrom], [CreatedOn], [EditFrom], [EditOn]) VALUES (@SystemID, @BpID, @NameVisible, @DescriptionShort, @WillBeCharged, @Cost, @Currency, @InvoiceTo, @OldPassInvalid, @CreditForOldPass, @IsInitialIssue, @UserName, SYSDATETIME(), @UserName, SYSDATETIME()) 
                       SELECT @ReturnValue = SCOPE_IDENTITY()"
                       SelectCommand="SELECT * FROM [Master_ReplacementPassCases] WHERE (([SystemID] = @SystemID) AND ([BpID] = @BpID)) ORDER BY [NameVisible]"
                       UpdateCommand="INSERT INTO History_ReplacementPassCases SELECT * FROM Master_ReplacementPassCases WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND [ReplacementPassCaseID] = @original_ReplacementPassCaseID; 
                       UPDATE [Master_ReplacementPassCases] SET [NameVisible] = @NameVisible, [DescriptionShort] = @DescriptionShort, [WillBeCharged] = @WillBeCharged, [Cost] = @Cost, Currency = @Currency, [InvoiceTo] = @InvoiceTo, [OldPassInvalid] = @OldPassInvalid, [CreditForOldPass] = @CreditForOldPass, IsInitialIssue = @IsInitialIssue, [EditFrom] = @UserName, [EditOn] = SYSDATETIME() WHERE [SystemID] = @original_SystemID AND [BpID] = @original_BpID AND [ReplacementPassCaseID] = @original_ReplacementPassCaseID">
        <DeleteParameters>
            <asp:Parameter Name="original_SystemID" Type="Int32" />
            <asp:Parameter Name="original_BpID" Type="Int32" />
            <asp:Parameter Name="original_ReplacementPassCaseID" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:SessionParameter DefaultValue="0" Name="SystemID" SessionField="SystemID" Type="Int32" />
            <asp:SessionParameter DefaultValue="0" Name="BpID" SessionField="BpID" Type="Int32" />
            <asp:Parameter Name="NameVisible" Type="String" />
            <asp:Parameter Name="DescriptionShort" Type="String" />
            <asp:Parameter Name="WillBeCharged" Type="Boolean" />
            <asp:Parameter Name="Cost" Type="Decimal" />
            <asp:Parameter Name="Currency" Type="String" />
            <asp:Parameter Name="InvoiceTo" Type="String" />
            <asp:Parameter Name="OldPassInvalid" Type="Boolean" />
            <asp:Parameter Name="CreditForOldPass" Type="Boolean" />
            <asp:Parameter Name="IsInitialIssue"></asp:Parameter>
            <asp:SessionParameter DefaultValue="" Name="UserName" SessionField="LoginName" Type="String" />
            <asp:Parameter Name="ReturnValue" />
        </InsertParameters>
        <SelectParameters>
            <asp:SessionParameter DefaultValue="0" Name="SystemID" SessionField="SystemID" Type="Int32" />
            <asp:SessionParameter DefaultValue="0" Name="BpID" SessionField="BpID" Type="Int32" />
        </SelectParameters>
        <UpdateParameters>
            <asp:Parameter Name="original_SystemID" Type="Int32" />
            <asp:Parameter Name="original_BpID" Type="Int32" />
            <asp:Parameter Name="original_ReplacementPassCaseID" Type="Int32" />
            <asp:Parameter Name="NameVisible" Type="String" />
            <asp:Parameter Name="DescriptionShort" Type="String" />
            <asp:Parameter Name="WillBeCharged" Type="Boolean" />
            <asp:Parameter Name="Cost" Type="Decimal" />
            <asp:Parameter Name="Currency" Type="String" />
            <asp:Parameter Name="InvoiceTo" Type="String"></asp:Parameter>

            <asp:Parameter Name="OldPassInvalid" Type="Boolean" />
            <asp:Parameter Name="CreditForOldPass" Type="Boolean" />
            <asp:Parameter Name="IsInitialIssue" />
            <asp:SessionParameter SessionField="LoginName" DefaultValue="" Name="UserName" Type="String"></asp:SessionParameter>
        </UpdateParameters>
    </asp:SqlDataSource>

    <asp:SqlDataSource ID="SqlDataSource_Currencies" runat="server" ConnectionString="<%$ ConnectionStrings:Insite_Dev_ConnectionString %>" 
                       SelectCommand="SELECT DISTINCT [ISO_Alphabetic], [Currency] FROM [System_Currencies] ORDER BY [Currency]">
    </asp:SqlDataSource>
</asp:Content>
