CREATE TABLE [dbo].[Master_Terminal]
(
	[SystemID] INT NOT NULL ,
    [BfID] INT NOT NULL, 
    [BpID] INT NOT NULL,
    [AccessAreaID] INT NOT NULL, 
    [TerminalID] INT NOT NULL, 
    [NameVisible]      NVARCHAR (50)  NULL,
    [TerminalType] INT NOT NULL, 
    [FirmwareVersion] NVARCHAR(50) NULL, 
    [SoftwareVersion] NVARCHAR(50) NULL, 
    [IsActivated] BIT NOT NULL DEFAULT 0, 
    [IsOnline] BIT NOT NULL DEFAULT 0, 
    [StatusTimestamp] DATETIME NOT NULL DEFAULT SYSDATETIME(), 
    [StatusTimestampLast] DATETIME NOT NULL DEFAULT SYSDATETIME(), 
    [OnlineTime] INT NOT NULL DEFAULT 0, 
    [OnlineTimeLast] INT NOT NULL DEFAULT 0, 
    [EnterEvents] INT NOT NULL DEFAULT 0, 
    [EnterEventsLast] INT NOT NULL DEFAULT 0, 
    [ExitEvents] INT NOT NULL DEFAULT 0, 
    [ExitEventsLast] INT NOT NULL DEFAULT 0, 
    [OnOffChanges] INT NOT NULL DEFAULT 0, 
    [OnOffChangesLast] INT NOT NULL DEFAULT 0, 
    [ErrorEvents] INT NOT NULL DEFAULT 0, 
    [ErrorEventsLast] INT NOT NULL DEFAULT 0, 
    [EditFrom]         NVARCHAR (50)  NULL,
    [EditOn]           DATETIME DEFAULT SYSDATETIME() NOT NULL, 
    PRIMARY KEY ([SystemID], [TerminalID], [BfID], [BpID], [AccessAreaID]), 
)
