//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_PresenceEmployee
    {
        public int SystemID { get; set; }
        public int BpID { get; set; }
        public int CompanyID { get; set; }
        public int TradeID { get; set; }
        public System.DateTime PresenceDay { get; set; }
        public int EmployeeID { get; set; }
        public byte CountAs { get; set; }
        public long PresenceSeconds { get; set; }
    }
}
