CREATE TABLE [dbo].[Data_ProcessEvents]
(
	[SystemID] INT NOT NULL , 
    [ProcessEventID] INT NOT NULL IDENTITY,
    [BpID] INT NOT NULL DEFAULT 0, 
    [CompanyCentralID] INT NOT NULL DEFAULT 0, 
    [UserIDInitiator] INT NOT NULL DEFAULT 0, 
    [UserIDExecutive] INT NOT NULL DEFAULT 0, 
	[NameVisible] [nvarchar](255) NULL,
    [ResourceID] NVARCHAR(50) NULL, 
	[DescriptionShort] [nvarchar](2000) NULL,
    [TypeID] INT NOT NULL DEFAULT 1, 
    [DialogID] INT NOT NULL DEFAULT 0, 
    [ActionID] INT NOT NULL DEFAULT 0, 
    [RefID] INT NOT NULL DEFAULT 0,
    [StatusID] INT NOT NULL DEFAULT 0, 
    [ProcessUrl] NVARCHAR(200) NULL, 
	[DoneFrom] [nvarchar](50) NULL,
	[DoneOn] [datetime] NULL, 
	[CreatedFrom] [nvarchar](50) NULL,
	[CreatedOn] [datetime] NOT NULL DEFAULT SYSDATETIME(),
	[EditFrom] [nvarchar](50) NULL,
	[EditOn] [datetime] NOT NULL DEFAULT SYSDATETIME(), 
    PRIMARY KEY ([SystemID], [ProcessEventID]), 
)
