//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    
    public partial class GetCompanyStatistics_Result
    {
        public Nullable<int> SubContractorsTotal { get; set; }
        public Nullable<int> SubContractorsDirect { get; set; }
        public Nullable<int> EmployeesTotal { get; set; }
        public Nullable<int> EmployeesSelf { get; set; }
    }
}
