CREATE TABLE [dbo].[Master_Users] (
    [SystemID]    INT           NOT NULL,
    [BpID]        INT           NOT NULL,
    [UserID]      INT NOT NULL,
    [CompanyID] INT NOT NULL DEFAULT 0, 
    [FirstName]   NVARCHAR (50) NULL,
    [LastName]    NVARCHAR (50) NULL,
    [Company]     NVARCHAR (50) NULL,
    [LoginName]   NVARCHAR (50) NULL,
    [Password]    NVARCHAR (200) NULL,
    [RoleID] INT NOT NULL DEFAULT 0, 
    [TypeID]      TINYINT       CONSTRAINT [DF_Master_Users_TypeID] DEFAULT ((1)) NOT NULL,
    [LanguageID] NVARCHAR(10) NOT NULL, 
    [SkinName] NVARCHAR(50) NULL, 
    [Phone] NVARCHAR(50) NULL, 
    [Email] NVARCHAR(200) NULL, 
    [SessionID] NVARCHAR(200) NULL, 
    [TreeStatus] NVARCHAR(200) NULL, 
    [IsVisible]   BIT           CONSTRAINT [DF_Master_Users_IsVisible] DEFAULT ((1)) NOT NULL,
    [IsRoot]   BIT           NOT NULL DEFAULT 0,
    [IsSysAdmin] BIT NOT NULL DEFAULT 0, 
    [NeedsPwdChange] BIT NOT NULL DEFAULT 0, 
    [StatusID] INT NOT NULL DEFAULT 0, 
    [Salutation] NVARCHAR(50) NULL, 
    [GenderID] INT NOT NULL DEFAULT 0, 
    [LastLogin] DATETIME NULL, 
    [UseEmail] BIT NOT NULL DEFAULT 1, 
    [Soundex] NVARCHAR(1000) NULL, 
    [CreatedFrom] NVARCHAR (50) NULL,
    [CreatedOn]   DATETIME      CONSTRAINT [DF_Master_Users_CreatedOn] DEFAULT (sysdatetime()) NOT NULL,
    [EditFrom]    NVARCHAR (50) NULL,
    [EditOn]      DATETIME      CONSTRAINT [DF_Master_Users_EditOn] DEFAULT (sysdatetime()) NOT NULL,
    [RequestFrom] NVARCHAR(50) NULL, 
    [RequestOn] DATETIME NULL , 
    [ReleaseFrom] NVARCHAR(50) NULL, 
    [ReleaseOn] DATETIME NULL , 
    [LockedFrom] NVARCHAR(50) NULL, 
    [LockedOn] DATETIME NULL , 
    CONSTRAINT [PK_Master_Users] PRIMARY KEY CLUSTERED ([SystemID] ASC, [BpID] ASC, [UserID] ASC)
);

