CREATE TABLE [dbo].[History_BuildingProjects] (
    [SystemID]         INT            NOT NULL,
    [BpID]             INT            NOT NULL,
    [NameVisible]      NVARCHAR (50)  NULL,
    [DescriptionShort] NVARCHAR (200)  NULL,
    [TypeID]           TINYINT     DEFAULT ((0)) NOT NULL,
    [BasedOn] INT NOT NULL DEFAULT 0, 
    [IsVisible]        BIT            NOT NULL,
    [CountryID] NVARCHAR(10) NULL, 
    [BuilderName] NVARCHAR(200) NULL, 
    [PresentType] TINYINT NOT NULL DEFAULT 0, 
    [MWCheck] BIT NOT NULL DEFAULT 0, 
    [MWHours] INT NOT NULL DEFAULT 0, 
    [MWDeadline] INT NOT NULL DEFAULT 0, 
    [MWLackTrigger] INT NOT NULL DEFAULT 0, 
    [MinWageAccessRelevance] BIT NOT NULL DEFAULT 0, 
    [Address] NVARCHAR(500) NULL, 
    [DefaultRoleID] INT NOT NULL DEFAULT 0, 
    [DefaultAccessAreaID] INT NOT NULL DEFAULT 0, 
    [DefaultTimeSlotGroupID] INT NOT NULL DEFAULT 0, 
    [DefaultSTAccessAreaID] INT NOT NULL DEFAULT 0, 
    [DefaultSTTimeSlotGroupID] INT NOT NULL DEFAULT 0, 
    [PrintPassOnCompleteDocs] BIT NOT NULL DEFAULT 0, 
    [DefaultTariffScope] INT NOT NULL DEFAULT 0, 
    [ContainerManagementName] NVARCHAR(50) NULL, 
    [AccessRightValidDays] INT NOT NULL DEFAULT 365, 
    [CreatedFrom]      NVARCHAR (50)  NULL,
    [CreatedOn]        DATETIME      DEFAULT (sysdatetime()) NOT NULL,
    [EditFrom]         NVARCHAR (50)  NULL,
    [EditOn]           DATETIME      DEFAULT (sysdatetime()) NOT NULL,
    CONSTRAINT [PK_History_BuildingProject] PRIMARY KEY CLUSTERED ([SystemID], [BpID], [EditOn])
);
