//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    
    public partial class GetEmployees_Result
    {
        public string FirstChar { get; set; }
        public int SystemID { get; set; }
        public int BpID { get; set; }
        public int EmployeeID { get; set; }
        public string ExternalID { get; set; }
        public string InternalID { get; set; }
        public int AddressID { get; set; }
        public int CompanyID { get; set; }
        public int TradeID { get; set; }
        public string StaffFunction { get; set; }
        public int EmploymentStatusID { get; set; }
        public int MaxHrsPerMonth { get; set; }
        public int AttributeID { get; set; }
        public string ExternalPassID { get; set; }
        public string Description { get; set; }
        public string CreatedFrom { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string EditFrom { get; set; }
        public System.DateTime EditOn { get; set; }
        public string ReleaseCFrom { get; set; }
        public Nullable<System.DateTime> ReleaseCOn { get; set; }
        public string ReleaseBFrom { get; set; }
        public Nullable<System.DateTime> ReleaseBOn { get; set; }
        public string LockedFrom { get; set; }
        public Nullable<System.DateTime> LockedOn { get; set; }
        public string Salutation { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FullAddress { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Zip { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int DenominationID { get; set; }
        public string CountryID { get; set; }
        public string LanguageID { get; set; }
        public string NationalityID { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string WWW { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> Gender { get; set; }
        public string PhotoFileName { get; set; }
        public byte[] PhotoData { get; set; }
        public byte[] ThumbnailData { get; set; }
        public string NameVisible { get; set; }
        public string NameAdditional { get; set; }
        public int StatusID { get; set; }
        public string UserString1 { get; set; }
        public string UserString2 { get; set; }
        public string UserString3 { get; set; }
        public string UserString4 { get; set; }
        public bool UserBit1 { get; set; }
        public bool UserBit2 { get; set; }
        public bool UserBit3 { get; set; }
        public bool UserBit4 { get; set; }
        public string TradeName { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> PassID { get; set; }
        public Nullable<System.DateTime> ValidUntil { get; set; }
        public int PassActive { get; set; }
        public int PassLocked { get; set; }
        public int CompanyActive { get; set; }
        public string NationalityName { get; set; }
        public string FlagName { get; set; }
        public bool AccessAllowed { get; set; }
        public string AccessDenialReason { get; set; }
        public Nullable<System.DateTime> AccessDenialTimeStamp { get; set; }
        public string PassColor { get; set; }
        public Nullable<int> Present { get; set; }
        public System.DateTime AccessTime { get; set; }
        public Nullable<System.DateTime> AccessRightValidUntil { get; set; }
        public string Duplicates { get; set; }
        public string EmploymentStatus { get; set; }
    }
}
