CREATE TABLE [dbo].[History_S_Addresses] (
    [SystemID]         INT            NOT NULL,
    [AddressID]        INT NOT NULL,
    [Salutation]       NVARCHAR (50)  NULL,
    [Title]            NVARCHAR (50)  NULL,
    [FirstName]        NVARCHAR (50)  NULL,
    [MiddleName]       NVARCHAR (50)  NULL,
    [LastName]         NVARCHAR (50)  NULL,
    [Address1]         NVARCHAR (100) NULL,
    [Address2]         NVARCHAR (100) NULL,
    [Zip]              NVARCHAR (20)  NULL,
    [City]             NVARCHAR (100) NULL,
    [State]            NVARCHAR (100) NULL,
    [DenominationID]       INT             DEFAULT ((0)) NOT NULL,
    [CountryID]      NVARCHAR(10)       NULL,
    [LanguageID]     NVARCHAR(10)       NULL,
    [Phone]            NVARCHAR (50)  NULL,
    [Mobile]           NVARCHAR (50)  NULL,
    [Email]            NVARCHAR (200) NULL,
    [WWW] NVARCHAR(200) NULL, 
    [DescriptionShort] NVARCHAR (200) NULL,
    [Soundex] NVARCHAR(1000) NULL, 
    [CreatedFrom]      NVARCHAR (50)  NULL,
    [CreatedOn]        DATETIME        DEFAULT (sysdatetime()) NOT NULL,
    [EditFrom]         NVARCHAR (50)  NULL,
    [EditOn]           DATETIME        DEFAULT (sysdatetime()) NOT NULL, 
    CONSTRAINT [PK_History_S_Addresses] PRIMARY KEY ([SystemID], [AddressID], [EditOn]),
);

