//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_StatisticsTerminals
    {
        public int SystemID { get; set; }
        public int BfID { get; set; }
        public int BpID { get; set; }
        public System.DateTime StatisticsDate { get; set; }
        public int AccessAreaID { get; set; }
        public int TerminalID { get; set; }
        public int OnlineTime { get; set; }
        public int EnterEvents { get; set; }
        public int ExitEvents { get; set; }
        public int OnOffChanges { get; set; }
        public int ErrorEvents { get; set; }
        public Nullable<System.DateTime> SnapshotTimestamp { get; set; }
    }
}
