//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_EmployeeMinWageAttestation
    {
        public int SystemID { get; set; }
        public int BpID { get; set; }
        public int EmployeeID { get; set; }
        public int MinWageAttestationID { get; set; }
        public decimal AccumulatedHours { get; set; }
        public System.DateTime ForMonth { get; set; }
        public decimal Amount { get; set; }
        public int WageGroupID { get; set; }
        public int Status { get; set; }
        public string ReceivedBy { get; set; }
        public Nullable<System.DateTime> ReceivedOn { get; set; }
        public string RequestBy { get; set; }
        public Nullable<System.DateTime> RequestOn { get; set; }
        public string DocumentID { get; set; }
        public string CreatedFrom { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string EditFrom { get; set; }
        public System.DateTime EditOn { get; set; }
    }
}
