//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder-Klasse
    // mit einem Tool wie ResGen oder Visual Studio automatisch generiert.
    // Bearbeiten Sie zum Hinzufügen oder Entfernen eines Members die RESX-Datei, und führen Sie dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen das Visual Studio-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccessMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccessMessages() {
        }
        
        /// <summary>
        ///   Gibt die von dieser Klasse verwendete zwischengespeicherte ResourceManager-Instanz zurück.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AccessMessages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenlookups, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All assigned access areas invalid ähnelt.
        /// </summary>
        internal static string admAccessAreasInvalid {
            get {
                return ResourceManager.GetString("admAccessAreasInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Access right no longer valid ähnelt.
        /// </summary>
        internal static string admAccessRightValidUntilExpired {
            get {
                return ResourceManager.GetString("admAccessRightValidUntilExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Company locked ähnelt.
        /// </summary>
        internal static string admCompanyLocked {
            get {
                return ResourceManager.GetString("admCompanyLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Document {0} relevant for {1} is not present ähnelt.
        /// </summary>
        internal static string admDocumentNotPresent {
            get {
                return ResourceManager.GetString("admDocumentNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Document relevant for residence right *or* labour right *or* insurance is not present ähnelt.
        /// </summary>
        internal static string admDocumentNotPresentRule1 {
            get {
                return ResourceManager.GetString("admDocumentNotPresentRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Document relevant for residence right *or* labour right is not present ähnelt.
        /// </summary>
        internal static string admDocumentNotPresentRule3 {
            get {
                return ResourceManager.GetString("admDocumentNotPresentRule3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Document {0} relevant for {1} is no longer valid ähnelt.
        /// </summary>
        internal static string admDocumentNotValid {
            get {
                return ResourceManager.GetString("admDocumentNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Employee locked ähnelt.
        /// </summary>
        internal static string admEmployeeLocked {
            get {
                return ResourceManager.GetString("admEmployeeLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Employee not yet activated ähnelt.
        /// </summary>
        internal static string admEmployeeNotYetActivated {
            get {
                return ResourceManager.GetString("admEmployeeNotYetActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Main contractor {0} locked ähnelt.
        /// </summary>
        internal static string admMainContractorLocked {
            get {
                return ResourceManager.GetString("admMainContractorLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No access areas assigned ähnelt.
        /// </summary>
        internal static string admNoAccessAreas {
            get {
                return ResourceManager.GetString("admNoAccessAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No document checking rule assigned ähnelt.
        /// </summary>
        internal static string admNoDocumentCheckingRule {
            get {
                return ResourceManager.GetString("admNoDocumentCheckingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parent customer locked ähnelt.
        /// </summary>
        internal static string admParentCustomerLocked {
            get {
                return ResourceManager.GetString("admParentCustomerLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pass deactivated ähnelt.
        /// </summary>
        internal static string admPassDeactivated {
            get {
                return ResourceManager.GetString("admPassDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pass locked permanently ähnelt.
        /// </summary>
        internal static string admPassLocked {
            get {
                return ResourceManager.GetString("admPassLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pass not active ähnelt.
        /// </summary>
        internal static string admPassNotActive {
            get {
                return ResourceManager.GetString("admPassNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Area currently overcrowded ähnelt.
        /// </summary>
        internal static string lblAccAreaCurrentlyOvercrowded {
            get {
                return ResourceManager.GetString("lblAccAreaCurrentlyOvercrowded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Company locked ähnelt.
        /// </summary>
        internal static string lblAccCompanyLocked {
            get {
                return ResourceManager.GetString("lblAccCompanyLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Employee locked ähnelt.
        /// </summary>
        internal static string lblAccEmployeeLocked {
            get {
                return ResourceManager.GetString("lblAccEmployeeLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid action ähnelt.
        /// </summary>
        internal static string lblAccInvalidAction {
            get {
                return ResourceManager.GetString("lblAccInvalidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No exit without access ähnelt.
        /// </summary>
        internal static string lblAccNoExitWithoutAccess {
            get {
                return ResourceManager.GetString("lblAccNoExitWithoutAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pass invalid ähnelt.
        /// </summary>
        internal static string lblAccPassInvalid {
            get {
                return ResourceManager.GetString("lblAccPassInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pass locked ähnelt.
        /// </summary>
        internal static string lblAccPassLocked {
            get {
                return ResourceManager.GetString("lblAccPassLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pass not yet assigned ähnelt.
        /// </summary>
        internal static string lblAccPassNotAssigned {
            get {
                return ResourceManager.GetString("lblAccPassNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pass not valid for this area ähnelt.
        /// </summary>
        internal static string lblAccPassNotValidForArea {
            get {
                return ResourceManager.GetString("lblAccPassNotValidForArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pass already on area ähnelt.
        /// </summary>
        internal static string lblAccPassOnArea {
            get {
                return ResourceManager.GetString("lblAccPassOnArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pass unknown ähnelt.
        /// </summary>
        internal static string lblAccPassUnknown {
            get {
                return ResourceManager.GetString("lblAccPassUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service  not available ähnelt.
        /// </summary>
        internal static string lblAccServiceNotAvailable {
            get {
                return ResourceManager.GetString("lblAccServiceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time invalid ähnelt.
        /// </summary>
        internal static string lblAccTimeInvalid {
            get {
                return ResourceManager.GetString("lblAccTimeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Using other turnstile ähnelt.
        /// </summary>
        internal static string lblAccUseOtherTurnstile {
            get {
                return ResourceManager.GetString("lblAccUseOtherTurnstile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insurance ähnelt.
        /// </summary>
        internal static string selRDInsurance {
            get {
                return ResourceManager.GetString("selRDInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insurance additional ähnelt.
        /// </summary>
        internal static string selRDInsuranceAdditional {
            get {
                return ResourceManager.GetString("selRDInsuranceAdditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Labor right ähnelt.
        /// </summary>
        internal static string selRDLaborRight {
            get {
                return ResourceManager.GetString("selRDLaborRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Legitimation ähnelt.
        /// </summary>
        internal static string selRDLegitimation {
            get {
                return ResourceManager.GetString("selRDLegitimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No mapping ähnelt.
        /// </summary>
        internal static string selRDNone {
            get {
                return ResourceManager.GetString("selRDNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Residence right ähnelt.
        /// </summary>
        internal static string selRDResidenceRight {
            get {
                return ResourceManager.GetString("selRDResidenceRight", resourceCulture);
            }
        }
    }
}
