//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadGrid {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder-Klasse
    // mit einem Tool wie ResGen oder Visual Studio automatisch generiert.
    // Bearbeiten Sie zum Hinzufügen oder Entfernen eines Members die RESX-Datei, und führen Sie dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen das Visual Studio-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Gibt die von dieser Klasse verwendete zwischengespeicherte ResourceManager-Instanz zurück.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadGrid.Main", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenlookups, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string AddNewRecordImageUrl {
            get {
                return ResourceManager.GetString("AddNewRecordImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add new record ähnelt.
        /// </summary>
        internal static string AddNewRecordText {
            get {
                return ResourceManager.GetString("AddNewRecordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Avg ähnelt.
        /// </summary>
        internal static string AggregateFunctionAvg {
            get {
                return ResourceManager.GetString("AggregateFunctionAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Count ähnelt.
        /// </summary>
        internal static string AggregateFunctionCount {
            get {
                return ResourceManager.GetString("AggregateFunctionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CountDistinct ähnelt.
        /// </summary>
        internal static string AggregateFunctionCountDistinct {
            get {
                return ResourceManager.GetString("AggregateFunctionCountDistinct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom ähnelt.
        /// </summary>
        internal static string AggregateFunctionCustom {
            get {
                return ResourceManager.GetString("AggregateFunctionCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First ähnelt.
        /// </summary>
        internal static string AggregateFunctionFirst {
            get {
                return ResourceManager.GetString("AggregateFunctionFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last ähnelt.
        /// </summary>
        internal static string AggregateFunctionLast {
            get {
                return ResourceManager.GetString("AggregateFunctionLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max ähnelt.
        /// </summary>
        internal static string AggregateFunctionMax {
            get {
                return ResourceManager.GetString("AggregateFunctionMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Min ähnelt.
        /// </summary>
        internal static string AggregateFunctionMin {
            get {
                return ResourceManager.GetString("AggregateFunctionMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sum ähnelt.
        /// </summary>
        internal static string AggregateFunctionSum {
            get {
                return ResourceManager.GetString("AggregateFunctionSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Between ähnelt.
        /// </summary>
        internal static string BetweenText {
            get {
                return ResourceManager.GetString("BetweenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel changes ähnelt.
        /// </summary>
        internal static string CancelChangesText {
            get {
                return ResourceManager.GetString("CancelChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change Page Size ähnelt.
        /// </summary>
        internal static string ChangePageSizeButtonToolTip {
            get {
                return ResourceManager.GetString("ChangePageSizeButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ChangePageSizeComboBoxTableSummary {
            get {
                return ResourceManager.GetString("ChangePageSizeComboBoxTableSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ChangePageSizeComboBoxToolTip {
            get {
                return ResourceManager.GetString("ChangePageSizeComboBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Page size: ähnelt.
        /// </summary>
        internal static string ChangePageSizeLabelText {
            get {
                return ResourceManager.GetString("ChangePageSizeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change ähnelt.
        /// </summary>
        internal static string ChangePageSizeLinkButtonText {
            get {
                return ResourceManager.GetString("ChangePageSizeLinkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ChangePageSizeTextBoxToolTip {
            get {
                return ResourceManager.GetString("ChangePageSizeTextBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        internal static string CloseText {
            get {
                return ResourceManager.GetString("CloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Collapse group ähnelt.
        /// </summary>
        internal static string CollapseTooltip {
            get {
                return ResourceManager.GetString("CollapseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Width: &lt;strong&gt;{0}&lt;/strong&gt; &lt;em&gt;pixels&lt;/em&gt; ähnelt.
        /// </summary>
        internal static string ColumnResizeTooltipFormatString {
            get {
                return ResourceManager.GetString("ColumnResizeTooltipFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contains ähnelt.
        /// </summary>
        internal static string ContainsText {
            get {
                return ResourceManager.GetString("ContainsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom ähnelt.
        /// </summary>
        internal static string CustomText {
            get {
                return ResourceManager.GetString("CustomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string DeleteText {
            get {
                return ResourceManager.GetString("DeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DoesNotContain ähnelt.
        /// </summary>
        internal static string DoesNotContainText {
            get {
                return ResourceManager.GetString("DoesNotContainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drag to group or reorder ähnelt.
        /// </summary>
        internal static string DragToGroupOrReorder {
            get {
                return ResourceManager.GetString("DragToGroupOrReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drag to resize ähnelt.
        /// </summary>
        internal static string DragToResize {
            get {
                return ResourceManager.GetString("DragToResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drop here to reorder ähnelt.
        /// </summary>
        internal static string DropHereToReorder {
            get {
                return ResourceManager.GetString("DropHereToReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        internal static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EndsWith ähnelt.
        /// </summary>
        internal static string EndsWithText {
            get {
                return ResourceManager.GetString("EndsWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EqualTo ähnelt.
        /// </summary>
        internal static string EqualToText {
            get {
                return ResourceManager.GetString("EqualToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expand group ähnelt.
        /// </summary>
        internal static string ExpandTooltip {
            get {
                return ResourceManager.GetString("ExpandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ExportToCsvImageUrl {
            get {
                return ResourceManager.GetString("ExportToCsvImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export to CSV ähnelt.
        /// </summary>
        internal static string ExportToCsvText {
            get {
                return ResourceManager.GetString("ExportToCsvText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ExportToExcelImageUrl {
            get {
                return ResourceManager.GetString("ExportToExcelImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export to Excel ähnelt.
        /// </summary>
        internal static string ExportToExcelText {
            get {
                return ResourceManager.GetString("ExportToExcelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ExportToPdfImageUrl {
            get {
                return ResourceManager.GetString("ExportToPdfImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export to PDF ähnelt.
        /// </summary>
        internal static string ExportToPdfText {
            get {
                return ResourceManager.GetString("ExportToPdfText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ExportToWordImageUrl {
            get {
                return ResourceManager.GetString("ExportToWordImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export to Word ähnelt.
        /// </summary>
        internal static string ExportToWordText {
            get {
                return ResourceManager.GetString("ExportToWordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string FilterExpression {
            get {
                return ResourceManager.GetString("FilterExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        /// </summary>
        internal static string FilterImageToolTip {
            get {
                return ResourceManager.GetString("FilterImageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string FirstPageText {
            get {
                return ResourceManager.GetString("FirstPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First Page ähnelt.
        /// </summary>
        internal static string FirstPageToolTip {
            get {
                return ResourceManager.GetString("FirstPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Page: ähnelt.
        /// </summary>
        internal static string GoToPageLabelText {
            get {
                return ResourceManager.GetString("GoToPageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Go ähnelt.
        /// </summary>
        internal static string GoToPageLinkButtonText {
            get {
                return ResourceManager.GetString("GoToPageLinkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string GoToPageTextBoxToolTip {
            get {
                return ResourceManager.GetString("GoToPageTextBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GreaterThanOrEqualTo ähnelt.
        /// </summary>
        internal static string GreaterThanOrEqualToText {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GreaterThan ähnelt.
        /// </summary>
        internal static string GreaterThanText {
            get {
                return ResourceManager.GetString("GreaterThanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ;  ähnelt.
        /// </summary>
        internal static string GroupByFieldsSeparator {
            get {
                return ResourceManager.GetString("GroupByFieldsSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ... group continued from the previous page.  ähnelt.
        /// </summary>
        internal static string GroupContinuedFormatString {
            get {
                return ResourceManager.GetString("GroupContinuedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  Group continues on the next page. ähnelt.
        /// </summary>
        internal static string GroupContinuesFormatString {
            get {
                return ResourceManager.GetString("GroupContinuesFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drag a column header and drop it here to group by that column ähnelt.
        /// </summary>
        internal static string GroupPanelText {
            get {
                return ResourceManager.GetString("GroupPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Showing {0} of {1} items. ähnelt.
        /// </summary>
        internal static string GroupSplitDisplayFormat {
            get {
                return ResourceManager.GetString("GroupSplitDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ({0}) ähnelt.
        /// </summary>
        internal static string GroupSplitFormat {
            get {
                return ResourceManager.GetString("GroupSplitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aggregates ähnelt.
        /// </summary>
        internal static string HeaderContextMenuAggregates {
            get {
                return ResourceManager.GetString("HeaderContextMenuAggregates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die And ähnelt.
        /// </summary>
        internal static string HeaderContextMenuAndLabel {
            get {
                return ResourceManager.GetString("HeaderContextMenuAndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Avg ähnelt.
        /// </summary>
        internal static string HeaderContextMenuAvgAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuAvgAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Best Fit ähnelt.
        /// </summary>
        internal static string HeaderContextMenuBestFitText {
            get {
                return ResourceManager.GetString("HeaderContextMenuBestFitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear Filter ähnelt.
        /// </summary>
        internal static string HeaderContextMenuClearButton {
            get {
                return ResourceManager.GetString("HeaderContextMenuClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Columns ähnelt.
        /// </summary>
        internal static string HeaderContextMenuColumns {
            get {
                return ResourceManager.GetString("HeaderContextMenuColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Count ähnelt.
        /// </summary>
        internal static string HeaderContextMenuCountAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuCountAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CountDistinct ähnelt.
        /// </summary>
        internal static string HeaderContextMenuCountDistinctAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuCountDistinctAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom ähnelt.
        /// </summary>
        internal static string HeaderContextMenuCustomAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuCustomAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        /// </summary>
        internal static string HeaderContextMenuFilterButton {
            get {
                return ResourceManager.GetString("HeaderContextMenuFilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        /// </summary>
        internal static string HeaderContextMenuFilterItemText {
            get {
                return ResourceManager.GetString("HeaderContextMenuFilterItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First ähnelt.
        /// </summary>
        internal static string HeaderContextMenuFirstAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuFirstAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Freeze ähnelt.
        /// </summary>
        internal static string HeaderContextMenuFreeze {
            get {
                return ResourceManager.GetString("HeaderContextMenuFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group By ähnelt.
        /// </summary>
        internal static string HeaderContextMenuGroupBy {
            get {
                return ResourceManager.GetString("HeaderContextMenuGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last ähnelt.
        /// </summary>
        internal static string HeaderContextMenuLastAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuLastAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max ähnelt.
        /// </summary>
        internal static string HeaderContextMenuMaxAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuMaxAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Min ähnelt.
        /// </summary>
        internal static string HeaderContextMenuMinAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuMinAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        internal static string HeaderContextMenuNoneAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuNoneAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show rows with value that ähnelt.
        /// </summary>
        internal static string HeaderContextMenuRowsLabel {
            get {
                return ResourceManager.GetString("HeaderContextMenuRowsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort Ascending ähnelt.
        /// </summary>
        internal static string HeaderContextMenuSortAsc {
            get {
                return ResourceManager.GetString("HeaderContextMenuSortAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear Sorting ähnelt.
        /// </summary>
        internal static string HeaderContextMenuSortClear {
            get {
                return ResourceManager.GetString("HeaderContextMenuSortClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort Descending ähnelt.
        /// </summary>
        internal static string HeaderContextMenuSortDesc {
            get {
                return ResourceManager.GetString("HeaderContextMenuSortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sum ähnelt.
        /// </summary>
        internal static string HeaderContextMenuSumAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuSumAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unfreeze ähnelt.
        /// </summary>
        internal static string HeaderContextMenuUnfreeze {
            get {
                return ResourceManager.GetString("HeaderContextMenuUnfreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ungroup ähnelt.
        /// </summary>
        internal static string HeaderContextMenuUnGroupBy {
            get {
                return ResourceManager.GetString("HeaderContextMenuUnGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Collapse ähnelt.
        /// </summary>
        internal static string HierarchyCollapseTooltip {
            get {
                return ResourceManager.GetString("HierarchyCollapseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expand ähnelt.
        /// </summary>
        internal static string HierarchyExpandTooltip {
            get {
                return ResourceManager.GetString("HierarchyExpandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Self reference collapse ähnelt.
        /// </summary>
        internal static string HierarchySelfCollapseTooltip {
            get {
                return ResourceManager.GetString("HierarchySelfCollapseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Self reference expand ähnelt.
        /// </summary>
        internal static string HierarchySelfExpandTooltip {
            get {
                return ResourceManager.GetString("HierarchySelfExpandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert ähnelt.
        /// </summary>
        internal static string InsertText {
            get {
                return ResourceManager.GetString("InsertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IsEmpty ähnelt.
        /// </summary>
        internal static string IsEmptyText {
            get {
                return ResourceManager.GetString("IsEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IsNull ähnelt.
        /// </summary>
        internal static string IsNullText {
            get {
                return ResourceManager.GetString("IsNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string LastPageText {
            get {
                return ResourceManager.GetString("LastPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Page ähnelt.
        /// </summary>
        internal static string LastPageToolTip {
            get {
                return ResourceManager.GetString("LastPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LessThanOrEqualTo ähnelt.
        /// </summary>
        internal static string LessThanOrEqualToText {
            get {
                return ResourceManager.GetString("LessThanOrEqualToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LessThan ähnelt.
        /// </summary>
        internal static string LessThanText {
            get {
                return ResourceManager.GetString("LessThanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading... ähnelt.
        /// </summary>
        internal static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show/Hide Columns and Drag the Icon to Reorder ähnelt.
        /// </summary>
        internal static string MobileColumnsViewDescription {
            get {
                return ResourceManager.GetString("MobileColumnsViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Columns Display ähnelt.
        /// </summary>
        internal static string MobileColumnsViewTitle {
            get {
                return ResourceManager.GetString("MobileColumnsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        internal static string MobileEditViewTitle {
            get {
                return ResourceManager.GetString("MobileEditViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        internal static string MobileFilterViewOptionsText {
            get {
                return ResourceManager.GetString("MobileFilterViewOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter by {0} ähnelt.
        /// </summary>
        internal static string MobileFilterViewTitleFormat {
            get {
                return ResourceManager.GetString("MobileFilterViewTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value ähnelt.
        /// </summary>
        internal static string MobileFilterViewValueText {
            get {
                return ResourceManager.GetString("MobileFilterViewValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert ähnelt.
        /// </summary>
        internal static string MobileInsertViewTitle {
            get {
                return ResourceManager.GetString("MobileInsertViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        internal static string MobileViewBackButtonText {
            get {
                return ResourceManager.GetString("MobileViewBackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string MobileViewCancelButtonText {
            get {
                return ResourceManager.GetString("MobileViewCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Done ähnelt.
        /// </summary>
        internal static string MobileViewDoneButtonText {
            get {
                return ResourceManager.GetString("MobileViewDoneButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View Groups ähnelt.
        /// </summary>
        internal static string MobileViewGroupsText {
            get {
                return ResourceManager.GetString("MobileViewGroupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next ähnelt.
        /// </summary>
        internal static string NextFrozenColumnText {
            get {
                return ResourceManager.GetString("NextFrozenColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next Pages ähnelt.
        /// </summary>
        internal static string NextPagesToolTip {
            get {
                return ResourceManager.GetString("NextPagesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string NextPageText {
            get {
                return ResourceManager.GetString("NextPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next Page ähnelt.
        /// </summary>
        internal static string NextPageToolTip {
            get {
                return ResourceManager.GetString("NextPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No child records to display. ähnelt.
        /// </summary>
        internal static string NoDetailRecordsText {
            get {
                return ResourceManager.GetString("NoDetailRecordsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NoFilter ähnelt.
        /// </summary>
        internal static string NoFilterText {
            get {
                return ResourceManager.GetString("NoFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No records to display. ähnelt.
        /// </summary>
        internal static string NoMasterRecordsText {
            get {
                return ResourceManager.GetString("NoMasterRecordsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NotBetween ähnelt.
        /// </summary>
        internal static string NotBetweenText {
            get {
                return ResourceManager.GetString("NotBetweenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NotEqualTo ähnelt.
        /// </summary>
        internal static string NotEqualToText {
            get {
                return ResourceManager.GetString("NotEqualToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NotIsEmpty ähnelt.
        /// </summary>
        internal static string NotIsEmptyText {
            get {
                return ResourceManager.GetString("NotIsEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NotIsNull ähnelt.
        /// </summary>
        internal static string NotIsNullText {
            get {
                return ResourceManager.GetString("NotIsNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die of {0} ähnelt.
        /// </summary>
        internal static string PageOfLabelText {
            get {
                return ResourceManager.GetString("PageOfLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change page: {4} &amp;nbsp;Page &lt;strong&gt;{0}&lt;/strong&gt; of &lt;strong&gt;{1}&lt;/strong&gt;, items &lt;strong&gt;{2}&lt;/strong&gt; to &lt;strong&gt;{3}&lt;/strong&gt; of &lt;strong&gt;{5}&lt;/strong&gt;. ähnelt.
        /// </summary>
        internal static string PagerTextFormat {
            get {
                return ResourceManager.GetString("PagerTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Page &lt;strong&gt;{0}&lt;/strong&gt; of &lt;strong&gt;{1}&lt;/strong&gt; ähnelt.
        /// </summary>
        internal static string PagerTooltipFormatString {
            get {
                return ResourceManager.GetString("PagerTooltipFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Page size: ähnelt.
        /// </summary>
        internal static string PageSizeLabelText {
            get {
                return ResourceManager.GetString("PageSizeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prev ähnelt.
        /// </summary>
        internal static string PrevFrozenColumnText {
            get {
                return ResourceManager.GetString("PrevFrozenColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous Pages ähnelt.
        /// </summary>
        internal static string PrevPagesToolTip {
            get {
                return ResourceManager.GetString("PrevPagesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string PrevPageText {
            get {
                return ResourceManager.GetString("PrevPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous Page ähnelt.
        /// </summary>
        internal static string PrevPageToolTip {
            get {
                return ResourceManager.GetString("PrevPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Print RadGrid ähnelt.
        /// </summary>
        internal static string PrintGridText {
            get {
                return ResourceManager.GetString("PrintGridText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die From:  ähnelt.
        /// </summary>
        internal static string RangeFilteringFromText {
            get {
                return ResourceManager.GetString("RangeFilteringFromText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To:  ähnelt.
        /// </summary>
        internal static string RangeFilteringToText {
            get {
                return ResourceManager.GetString("RangeFilteringToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh ähnelt.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string RefreshImageUrl {
            get {
                return ResourceManager.GetString("RefreshImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please do not remove this key. ähnelt.
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save changes ähnelt.
        /// </summary>
        internal static string SaveChangesText {
            get {
                return ResourceManager.GetString("SaveChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decrease ähnelt.
        /// </summary>
        internal static string SliderDecreaseText {
            get {
                return ResourceManager.GetString("SliderDecreaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drag ähnelt.
        /// </summary>
        internal static string SliderDragText {
            get {
                return ResourceManager.GetString("SliderDragText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increase ähnelt.
        /// </summary>
        internal static string SliderIncreaseText {
            get {
                return ResourceManager.GetString("SliderIncreaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorted asc ähnelt.
        /// </summary>
        internal static string SortedAscToolTip {
            get {
                return ResourceManager.GetString("SortedAscToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorted desc ähnelt.
        /// </summary>
        internal static string SortedDescToolTip {
            get {
                return ResourceManager.GetString("SortedDescToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click here to sort ähnelt.
        /// </summary>
        internal static string SortToolTip {
            get {
                return ResourceManager.GetString("SortToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die StartsWith ähnelt.
        /// </summary>
        internal static string StartsWithText {
            get {
                return ResourceManager.GetString("StartsWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ready ähnelt.
        /// </summary>
        internal static string StatusReadyText {
            get {
                return ResourceManager.GetString("StatusReadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click here to ungroup ähnelt.
        /// </summary>
        internal static string UnGroupButtonTooltip {
            get {
                return ResourceManager.GetString("UnGroupButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drag out of the bar to ungroup ähnelt.
        /// </summary>
        internal static string UnGroupTooltip {
            get {
                return ResourceManager.GetString("UnGroupTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
        /// </summary>
        internal static string UpdateText {
            get {
                return ResourceManager.GetString("UpdateText", resourceCulture);
            }
        }
    }
}
