//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadImageEditor {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder-Klasse
    // mit einem Tool wie ResGen oder Visual Studio automatisch generiert.
    // Bearbeiten Sie zum Hinzufügen oder Entfernen eines Members die RESX-Datei, und führen Sie dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen das Visual Studio-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dialogs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dialogs() {
        }
        
        /// <summary>
        ///   Gibt die von dieser Klasse verwendete zwischengespeicherte ResourceManager-Instanz zurück.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadImageEditor.Dialogs", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenlookups, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color ähnelt.
        /// </summary>
        internal static string AddText_Color {
            get {
                return ResourceManager.GetString("AddText_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The color of the text to add ähnelt.
        /// </summary>
        internal static string AddText_ColorToolTip {
            get {
                return ResourceManager.GetString("AddText_ColorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (Current Color is {0}) ähnelt.
        /// </summary>
        internal static string AddText_CurrentColorText {
            get {
                return ResourceManager.GetString("AddText_CurrentColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Font Family ähnelt.
        /// </summary>
        internal static string AddText_FontFamily {
            get {
                return ResourceManager.GetString("AddText_FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The font family of the text to add ähnelt.
        /// </summary>
        internal static string AddText_FontFamilyToolTip {
            get {
                return ResourceManager.GetString("AddText_FontFamilyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Font Size ähnelt.
        /// </summary>
        internal static string AddText_FontSize {
            get {
                return ResourceManager.GetString("AddText_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The size of the text to add ähnelt.
        /// </summary>
        internal static string AddText_FontSizeToolTip {
            get {
                return ResourceManager.GetString("AddText_FontSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pick Color ähnelt.
        /// </summary>
        internal static string AddText_PickColorToolTip {
            get {
                return ResourceManager.GetString("AddText_PickColorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your text here... ähnelt.
        /// </summary>
        internal static string AddText_SampleText {
            get {
                return ResourceManager.GetString("AddText_SampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Text ähnelt.
        /// </summary>
        internal static string AddText_Title {
            get {
                return ResourceManager.GetString("AddText_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply ähnelt.
        /// </summary>
        internal static string BrightnessContrast_ApplyBtn_Text {
            get {
                return ResourceManager.GetString("BrightnessContrast_ApplyBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply the selected brightness/contrast levels to the image ähnelt.
        /// </summary>
        internal static string BrightnessContrast_ApplyBtn_ToolTip {
            get {
                return ResourceManager.GetString("BrightnessContrast_ApplyBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        internal static string BrightnessContrast_ResetBtn_Text {
            get {
                return ResourceManager.GetString("BrightnessContrast_ResetBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset the changes so far ähnelt.
        /// </summary>
        internal static string BrightnessContrast_ResetBtn_ToolTip {
            get {
                return ResourceManager.GetString("BrightnessContrast_ResetBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brightness/Contrast ähnelt.
        /// </summary>
        internal static string BrightnessContrast_Title {
            get {
                return ResourceManager.GetString("BrightnessContrast_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter a value between -100 and 100 ähnelt.
        /// </summary>
        internal static string Brightness_TxtBoxToolTip {
            get {
                return ResourceManager.GetString("Brightness_TxtBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Actual Size ähnelt.
        /// </summary>
        internal static string Common_ActualSize {
            get {
                return ResourceManager.GetString("Common_ActualSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply ähnelt.
        /// </summary>
        internal static string Common_Apply {
            get {
                return ResourceManager.GetString("Common_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Merge the drawn figure with the main canvas ähnelt.
        /// </summary>
        internal static string Common_AppyDrawToolTip {
            get {
                return ResourceManager.GetString("Common_AppyDrawToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Best Fit ähnelt.
        /// </summary>
        internal static string Common_BestFit {
            get {
                return ResourceManager.GetString("Common_BestFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Constrain Proportions? ähnelt.
        /// </summary>
        internal static string Common_ConstrainProportions {
            get {
                return ResourceManager.GetString("Common_ConstrainProportions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decrease ähnelt.
        /// </summary>
        internal static string Common_Decrease {
            get {
                return ResourceManager.GetString("Common_Decrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A file with a name same as the target already exists! ähnelt.
        /// </summary>
        internal static string Common_FileExists {
            get {
                return ResourceManager.GetString("Common_FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Height ähnelt.
        /// </summary>
        internal static string Common_Height {
            get {
                return ResourceManager.GetString("Common_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increase ähnelt.
        /// </summary>
        internal static string Common_Increase {
            get {
                return ResourceManager.GetString("Common_Increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert ähnelt.
        /// </summary>
        internal static string Common_Insert {
            get {
                return ResourceManager.GetString("Common_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Left ähnelt.
        /// </summary>
        internal static string Common_Left {
            get {
                return ResourceManager.GetString("Common_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot write to the target folder! ähnelt.
        /// </summary>
        internal static string Common_MessageCannotWriteToFolder {
            get {
                return ResourceManager.GetString("Common_MessageCannotWriteToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected file could not be deleted because the application did not have enough permissions. Please, contact the administrator. ähnelt.
        /// </summary>
        internal static string Common_NoPermissionsToDeleteFile {
            get {
                return ResourceManager.GetString("Common_NoPermissionsToDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overwrite if file exists? ähnelt.
        /// </summary>
        internal static string Common_OverwriteExisting {
            get {
                return ResourceManager.GetString("Common_OverwriteExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Position ähnelt.
        /// </summary>
        internal static string Common_Position {
            get {
                return ResourceManager.GetString("Common_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set ähnelt.
        /// </summary>
        internal static string Common_Set {
            get {
                return ResourceManager.GetString("Common_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drag to change the value ähnelt.
        /// </summary>
        internal static string Common_SliderDrag {
            get {
                return ResourceManager.GetString("Common_SliderDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Swap Width and Height ähnelt.
        /// </summary>
        internal static string Common_SwapWidthHeight {
            get {
                return ResourceManager.GetString("Common_SwapWidthHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Top ähnelt.
        /// </summary>
        internal static string Common_Top {
            get {
                return ResourceManager.GetString("Common_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transform ähnelt.
        /// </summary>
        internal static string Common_Transform {
            get {
                return ResourceManager.GetString("Common_Transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die URL ähnelt.
        /// </summary>
        internal static string Common_Url {
            get {
                return ResourceManager.GetString("Common_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Width ähnelt.
        /// </summary>
        internal static string Common_Width {
            get {
                return ResourceManager.GetString("Common_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X ähnelt.
        /// </summary>
        internal static string Common_X {
            get {
                return ResourceManager.GetString("Common_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Y ähnelt.
        /// </summary>
        internal static string Common_Y {
            get {
                return ResourceManager.GetString("Common_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter a value between -127 and 127 ähnelt.
        /// </summary>
        internal static string Contrast_TxtBoxToolTip {
            get {
                return ResourceManager.GetString("Contrast_TxtBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aspect Ratio ähnelt.
        /// </summary>
        internal static string Crop_AspectRatio {
            get {
                return ResourceManager.GetString("Crop_AspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Aspect Ratio ähnelt.
        /// </summary>
        internal static string Crop_AspectRatioToolTip {
            get {
                return ResourceManager.GetString("Crop_AspectRatioToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crop ähnelt.
        /// </summary>
        internal static string Crop_Button {
            get {
                return ResourceManager.GetString("Crop_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crop Image ähnelt.
        /// </summary>
        internal static string Crop_Title {
            get {
                return ResourceManager.GetString("Crop_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color: ähnelt.
        /// </summary>
        internal static string DrawCircle_Color {
            get {
                return ResourceManager.GetString("DrawCircle_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (Current color is {0}) ähnelt.
        /// </summary>
        internal static string DrawCircle_CurrentColorText {
            get {
                return ResourceManager.GetString("DrawCircle_CurrentColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fill Color: ähnelt.
        /// </summary>
        internal static string DrawCircle_FillColor {
            get {
                return ResourceManager.GetString("DrawCircle_FillColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Line size: ähnelt.
        /// </summary>
        internal static string DrawCircle_LineSize {
            get {
                return ResourceManager.GetString("DrawCircle_LineSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set line size ähnelt.
        /// </summary>
        internal static string DrawCircle_LineSizeToolTip {
            get {
                return ResourceManager.GetString("DrawCircle_LineSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PickColor ähnelt.
        /// </summary>
        internal static string DrawCircle_PickColor {
            get {
                return ResourceManager.GetString("DrawCircle_PickColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pick Fill Color ähnelt.
        /// </summary>
        internal static string DrawCircle_PickFillColor {
            get {
                return ResourceManager.GetString("DrawCircle_PickFillColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Draw Circle ähnelt.
        /// </summary>
        internal static string DrawCircle_Title {
            get {
                return ResourceManager.GetString("DrawCircle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color: ähnelt.
        /// </summary>
        internal static string DrawRectangle_Color {
            get {
                return ResourceManager.GetString("DrawRectangle_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (Current color is {0}) ähnelt.
        /// </summary>
        internal static string DrawRectangle_CurrentColorText {
            get {
                return ResourceManager.GetString("DrawRectangle_CurrentColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fill Color: ähnelt.
        /// </summary>
        internal static string DrawRectangle_FillColor {
            get {
                return ResourceManager.GetString("DrawRectangle_FillColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Line size: ähnelt.
        /// </summary>
        internal static string DrawRectangle_LineSize {
            get {
                return ResourceManager.GetString("DrawRectangle_LineSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set line size ähnelt.
        /// </summary>
        internal static string DrawRectangle_LineSizeToolTip {
            get {
                return ResourceManager.GetString("DrawRectangle_LineSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PickColor ähnelt.
        /// </summary>
        internal static string DrawRectangle_PickColor {
            get {
                return ResourceManager.GetString("DrawRectangle_PickColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pick Fill Color ähnelt.
        /// </summary>
        internal static string DrawRectangle_PickFillColor {
            get {
                return ResourceManager.GetString("DrawRectangle_PickFillColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Draw Rectangle ähnelt.
        /// </summary>
        internal static string DrawRectangle_Title {
            get {
                return ResourceManager.GetString("DrawRectangle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose image extension ähnelt.
        /// </summary>
        internal static string Export_ChooseExtension {
            get {
                return ResourceManager.GetString("Export_ChooseExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Image ähnelt.
        /// </summary>
        internal static string Export_ClientRadioText {
            get {
                return ResourceManager.GetString("Export_ClientRadioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File Name ähnelt.
        /// </summary>
        internal static string Export_FileNameLabel {
            get {
                return ResourceManager.GetString("Export_FileNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter File Name ähnelt.
        /// </summary>
        internal static string Export_FileNameToolTip {
            get {
                return ResourceManager.GetString("Export_FileNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Image on Server ähnelt.
        /// </summary>
        internal static string Export_ServerRadioText {
            get {
                return ResourceManager.GetString("Export_ServerRadioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export Image ähnelt.
        /// </summary>
        internal static string Export_Title {
            get {
                return ResourceManager.GetString("Export_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flip None ähnelt.
        /// </summary>
        internal static string Flip_None {
            get {
                return ResourceManager.GetString("Flip_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flip ähnelt.
        /// </summary>
        internal static string Flip_Title {
            get {
                return ResourceManager.GetString("Flip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply ähnelt.
        /// </summary>
        internal static string HueSaturation_ApplyBtn_Text {
            get {
                return ResourceManager.GetString("HueSaturation_ApplyBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply the selected hue/saturation levels to the image ähnelt.
        /// </summary>
        internal static string HueSaturation_ApplyBtn_ToolTip {
            get {
                return ResourceManager.GetString("HueSaturation_ApplyBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        internal static string HueSaturation_ResetBtn_Text {
            get {
                return ResourceManager.GetString("HueSaturation_ResetBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset the changes so far ähnelt.
        /// </summary>
        internal static string HueSaturation_ResetBtn_ToolTip {
            get {
                return ResourceManager.GetString("HueSaturation_ResetBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hue/Saturation ähnelt.
        /// </summary>
        internal static string HueSaturation_Title {
            get {
                return ResourceManager.GetString("HueSaturation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter a value between 0 and 360 ähnelt.
        /// </summary>
        internal static string Hue_TxtBoxToolTip {
            get {
                return ResourceManager.GetString("Hue_TxtBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Image ähnelt.
        /// </summary>
        internal static string InsertImage_Title {
            get {
                return ResourceManager.GetString("InsertImage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die URL of an Image to Insert (example http://domain.com/img.png) ähnelt.
        /// </summary>
        internal static string InsertImage_UrlTxtToolTip {
            get {
                return ResourceManager.GetString("InsertImage_UrlTxtToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color: ähnelt.
        /// </summary>
        internal static string Line_Color {
            get {
                return ResourceManager.GetString("Line_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (Current color is {0}) ähnelt.
        /// </summary>
        internal static string Line_CurrentColorText {
            get {
                return ResourceManager.GetString("Line_CurrentColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Line size: ähnelt.
        /// </summary>
        internal static string Line_LineSize {
            get {
                return ResourceManager.GetString("Line_LineSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set line size ähnelt.
        /// </summary>
        internal static string Line_LineSizeToolTip {
            get {
                return ResourceManager.GetString("Line_LineSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PickColor ähnelt.
        /// </summary>
        internal static string Line_PickColor {
            get {
                return ResourceManager.GetString("Line_PickColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Draw Line ähnelt.
        /// </summary>
        internal static string Line_Title {
            get {
                return ResourceManager.GetString("Line_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter a value between 0 and 100% ähnelt.
        /// </summary>
        internal static string Opacity_TextboxToolTip {
            get {
                return ResourceManager.GetString("Opacity_TextboxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Opacity ähnelt.
        /// </summary>
        internal static string Opacity_Title {
            get {
                return ResourceManager.GetString("Opacity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color: ähnelt.
        /// </summary>
        internal static string Pencil_Color {
            get {
                return ResourceManager.GetString("Pencil_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (Current color is {0}) ähnelt.
        /// </summary>
        internal static string Pencil_CurrentColorText {
            get {
                return ResourceManager.GetString("Pencil_CurrentColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Line size: ähnelt.
        /// </summary>
        internal static string Pencil_LineSize {
            get {
                return ResourceManager.GetString("Pencil_LineSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set line size ähnelt.
        /// </summary>
        internal static string Pencil_LineSizeToolTip {
            get {
                return ResourceManager.GetString("Pencil_LineSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PickColor ähnelt.
        /// </summary>
        internal static string Pencil_PickColor {
            get {
                return ResourceManager.GetString("Pencil_PickColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pencil ähnelt.
        /// </summary>
        internal static string Pencil_Title {
            get {
                return ResourceManager.GetString("Pencil_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Print ähnelt.
        /// </summary>
        internal static string Print_Button {
            get {
                return ResourceManager.GetString("Print_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Print Image ähnelt.
        /// </summary>
        internal static string Print_Title {
            get {
                return ResourceManager.GetString("Print_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please do not delete this string. ähnelt.
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resize ähnelt.
        /// </summary>
        internal static string Resize_Button {
            get {
                return ResourceManager.GetString("Resize_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Percentage ähnelt.
        /// </summary>
        internal static string Resize_Percentage {
            get {
                return ResourceManager.GetString("Resize_Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Percentage of original Width x Height [0,100%] ähnelt.
        /// </summary>
        internal static string Resize_PercentageToolTip {
            get {
                return ResourceManager.GetString("Resize_PercentageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset Sizes ähnelt.
        /// </summary>
        internal static string Resize_PresetSizes {
            get {
                return ResourceManager.GetString("Resize_PresetSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Preset Width x Height ähnelt.
        /// </summary>
        internal static string Resize_PresetSizesToolTip {
            get {
                return ResourceManager.GetString("Resize_PresetSizesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resize ähnelt.
        /// </summary>
        internal static string Resize_Title {
            get {
                return ResourceManager.GetString("Resize_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a rotation angle ähnelt.
        /// </summary>
        internal static string Rotate_DropDownToolTip {
            get {
                return ResourceManager.GetString("Rotate_DropDownToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rotate ähnelt.
        /// </summary>
        internal static string Rotate_Title {
            get {
                return ResourceManager.GetString("Rotate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter a value between -100 and 100 ähnelt.
        /// </summary>
        internal static string Saturation_TxtBoxToolTip {
            get {
                return ResourceManager.GetString("Saturation_TxtBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Image ähnelt.
        /// </summary>
        internal static string Save_ClientRadioText {
            get {
                return ResourceManager.GetString("Save_ClientRadioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File Name ähnelt.
        /// </summary>
        internal static string Save_FileNameLabel {
            get {
                return ResourceManager.GetString("Save_FileNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter File Name ähnelt.
        /// </summary>
        internal static string Save_FileNameToolTip {
            get {
                return ResourceManager.GetString("Save_FileNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Image on Server ähnelt.
        /// </summary>
        internal static string Save_ServerRadioText {
            get {
                return ResourceManager.GetString("Save_ServerRadioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Image ähnelt.
        /// </summary>
        internal static string Save_Title {
            get {
                return ResourceManager.GetString("Save_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom to 100% ähnelt.
        /// </summary>
        internal static string Zoom_ActualSizeToolTip {
            get {
                return ResourceManager.GetString("Zoom_ActualSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fit image in editable area ähnelt.
        /// </summary>
        internal static string Zoom_BestFitToolTip {
            get {
                return ResourceManager.GetString("Zoom_BestFitToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter a value between 0 and 100% ähnelt.
        /// </summary>
        internal static string Zoom_TextboxToolTip {
            get {
                return ResourceManager.GetString("Zoom_TextboxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom ähnelt.
        /// </summary>
        internal static string Zoom_Title {
            get {
                return ResourceManager.GetString("Zoom_Title", resourceCulture);
            }
        }
    }
}
