//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_PassHistory
    {
        public int SystemID { get; set; }
        public int BpID { get; set; }
        public int PassID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Reason { get; set; }
        public Nullable<int> ActionID { get; set; }
        public Nullable<int> ReplacementPassCaseID { get; set; }
    }
}
