//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Terminal
    {
        public int SystemID { get; set; }
        public int BfID { get; set; }
        public int BpID { get; set; }
        public int AccessAreaID { get; set; }
        public int TerminalID { get; set; }
        public string NameVisible { get; set; }
        public int TerminalType { get; set; }
        public string FirmwareVersion { get; set; }
        public string SoftwareVersion { get; set; }
        public bool IsActivated { get; set; }
        public bool IsOnline { get; set; }
        public System.DateTime StatusTimestamp { get; set; }
        public System.DateTime StatusTimestampLast { get; set; }
        public int OnlineTime { get; set; }
        public int OnlineTimeLast { get; set; }
        public int EnterEvents { get; set; }
        public int EnterEventsLast { get; set; }
        public int ExitEvents { get; set; }
        public int ExitEventsLast { get; set; }
        public int OnOffChanges { get; set; }
        public int OnOffChangesLast { get; set; }
        public int ErrorEvents { get; set; }
        public int ErrorEventsLast { get; set; }
        public string EditFrom { get; set; }
        public System.DateTime EditOn { get; set; }
    }
}
