CREATE TABLE [dbo].[History_S_Companies] (
    [SystemID]         INT            NOT NULL,
    [CompanyID]        INT NOT NULL,
    [NameVisible]      NVARCHAR (200)  NULL,
    [NameAdditional]      NVARCHAR (200)  NULL,
    [Description] NVARCHAR (2000) NULL,
    [AddressID] INT NOT NULL DEFAULT 0, 
    [IsVisible] BIT NOT NULL DEFAULT 1, 
    [IsValid] BIT NOT NULL DEFAULT 1, 
    [TradeAssociation] NVARCHAR(200) NULL, 
    [BlnSOKA] BIT NOT NULL DEFAULT 0, 
    [MinWageAttestation] BIT NOT NULL DEFAULT 0, 
    [UserID] INT NOT NULL DEFAULT 0, 
    [StatusID] INT NOT NULL DEFAULT 0, 
    [Soundex] NVARCHAR(1000) NULL, 
    [CreatedFrom]      NVARCHAR (50)  NULL,
    [CreatedOn]        DATETIME       DEFAULT (sysdatetime()) NOT NULL,
    [EditFrom]         NVARCHAR (50)  NULL,
    [EditOn]           DATETIME       DEFAULT (sysdatetime()) NOT NULL, 
    [RequestFrom] NVARCHAR(50) NULL, 
    [RequestOn] DATETIME NULL , 
    [ReleaseFrom] NVARCHAR(50) NULL, 
    [ReleaseOn] DATETIME NULL , 
    [LockedFrom] NVARCHAR(50) NULL, 
    [LockedOn] DATETIME NULL , 
    CONSTRAINT [PK_History_S_Companies] PRIMARY KEY ([SystemID], [CompanyID], [EditOn]),
);
