<%@ Page Title="<%$ Resources:Resource, lblStatisticTrades %>" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="StatisticTradeGroups.aspx.cs" Inherits="InSite.App.Views.Central.StatisticTradeGroups" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeaderContent" runat="server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="BodyContent" runat="server">
    <telerik:RadPersistenceManagerProxy ID="RadPersistenceManagerProxy1" runat="server">
        <PersistenceSettings>
            <telerik:PersistenceSetting ControlID="RadGrid1" />
            <telerik:PersistenceSetting ControlID="RadGridTrades" />
        </PersistenceSettings>
    </telerik:RadPersistenceManagerProxy>

    <telerik:RadAjaxManagerProxy ID="AjaxManagerProxy1" runat="server">
        <AjaxSettings>
            <telerik:AjaxSetting AjaxControlID="RadGrid1">
                <UpdatedControls>
                    <telerik:AjaxUpdatedControl ControlID="RadGrid1" LoadingPanelID="RadAjaxLoadingPanelMaster" />
                </UpdatedControls>
            </telerik:AjaxSetting>
            <telerik:AjaxSetting AjaxControlID="RadGridTrades">
                <UpdatedControls>
                    <telerik:AjaxUpdatedControl ControlID="RadGridTrades" LoadingPanelID="RadAjaxLoadingPanelMaster" />
                </UpdatedControls>
            </telerik:AjaxSetting>
        </AjaxSettings>
    </telerik:RadAjaxManagerProxy>

    <div>
        <%-- TradeGroups Grid --%>
        <telerik:RadGrid ID="RadGrid1" runat="server" CellSpacing="0" DataSourceID="SqlDataSource_TradeGroups" GridLines="None" CssClass="MainGrid" AllowAutomaticDeletes="True"
                         AllowAutomaticInserts="True" AllowAutomaticUpdates="True" AllowSorting="true"
                         OnPreRender="RadGrid1_PreRender" OnItemDeleted="RadGrid1_ItemDeleted" OnItemCommand="RadGrid1_ItemCommand" OnItemUpdated="RadGrid1_ItemUpdated"
                         OnDetailTableDataBind="RadGrid1_DetailTableDataBind" OnItemInserted="RadGrid1_ItemInserted" OnItemCreated="RadGrid1_ItemCreated"
                         OnItemDataBound="RadGrid1_ItemDataBound" OnGroupsChanging="RadGrid1_GroupsChanging">

            <ExportSettings ExportOnlyData="True" IgnorePaging="True">
                <Pdf PaperSize="A4">
                </Pdf>
                <Excel Format="ExcelML" />
            </ExportSettings>

            <ClientSettings AllowColumnsReorder="True" AllowDragToGroup="True" EnableRowHoverStyle="True" EnablePostBackOnRowClick="false">
                <Resizing AllowColumnResize="true"></Resizing>
                <Selecting AllowRowSelect="True" />
                <ClientEvents OnRowClick="OnRowClick" OnGridCreated="OnGridCreated" OnKeyPress="GridKeyPress" />
            </ClientSettings>

            <%-- TradeGroups Master --%>
            <SortingSettings SortedBackColor="Transparent" />

            <MasterTableView AutoGenerateColumns="False" DataKeyNames="SystemID,TradeGroupID" CommandItemDisplay="Top" EditMode="PopUp" DataSourceID="SqlDataSource_TradeGroups"
                             HierarchyLoadMode="ServerOnDemand" Name="TradeGroups" ShowHeader="true" Caption="<%$ Resources:Resource, lblTradeGroups %>" AllowPaging="true" PageSize="10" CssClass="MasterClass">

                <PagerStyle Mode="NextPrevAndNumeric" AlwaysVisible="true" />

                <SortExpressions>
                    <telerik:GridSortExpression FieldName="Position" SortOrder="Ascending"></telerik:GridSortExpression>
                </SortExpressions>

                <CommandItemSettings ShowRefreshButton="true" ShowAddNewRecordButton="true" ShowExportToCsvButton="false" ShowExportToExcelButton="True" ShowExportToPdfButton="false"
                                     AddNewRecordText="<%$ Resources:Resource, lblActionNew %>" RefreshText="<%$ Resources:Resource, lblActionRefresh %>" />

                <EditFormSettings EditFormType="AutoGenerated" CaptionDataField="NameVisible" CaptionFormatString="{0}">
                    <PopUpSettings Modal="true" ShowCaptionInEditForm="false" ScrollBars="Auto" Height="500px" />
                    <EditColumn ButtonType="ImageButton" UniqueName="EditCommandColumn1" CancelText="<%$ Resources:Resource, lblActionCancel %>" EditText="<%$ Resources:Resource, lblActionEdit %>"
                                UpdateText="<%$ Resources:Resource, lblActionUpdate %>" />
                    <FormTableStyle CellPadding="3" CellSpacing="3" />
                </EditFormSettings>

                <%-- TradeGroup Nested View --%>
                <NestedViewTemplate>
                    <asp:Panel runat="server" ID="InnerContainer1" Visible="true">
                        <telerik:RadTabStrip runat="server" ID="TabStrip1" MultiPageID="Multipage1" SelectedIndex="0">
                            <Tabs>
                                <telerik:RadTab runat="server" Text='<%$ Resources:Resource, lblTrades %>' Font-Bold="true" PageViewID="PageView1_1">
                                </telerik:RadTab>
                                <telerik:RadTab runat="server" Text="<%$ Resources:Resource, lblDetails %>" Font-Bold="true" PageViewID="PageView1_2">
                                </telerik:RadTab>
                            </Tabs>
                        </telerik:RadTabStrip>

                        <telerik:RadMultiPage runat="server" ID="Multipage1" SelectedIndex="0" RenderSelectedPageOnly="false">

                            <%-- TradeGroup Trades --%>
                            <telerik:RadPageView runat="server" ID="PageView1_1">
                                <asp:HiddenField runat="server" ID="TradeGroupID" Value='<%# Eval("TradeGroupID") %>' />

                                <%-- Trades Grid --%>
                                <telerik:RadGrid ID="RadGridTrades" EnableHierarchyExpandAll="true" DataSourceID="SqlDataSource_Trades" Width="100%" AllowAutomaticInserts="true"
                                                 runat="server" AllowPaging="true" ShowFooter="false" EnableLinqExpressions="false" AllowAutomaticUpdates="True" AllowAutomaticDeletes="true"
                                                 AllowSorting="true"
                                                 OnItemInserted="RadGrid1_ItemInserted" OnPreRender="RadGrid1_PreRender" OnItemCreated="RadGridTrades_ItemCreated"
                                                 OnItemDeleted="RadGridTrades_ItemDeleted" OnItemUpdated="RadGridTrades_ItemUpdated" OnItemCommand="RadGridTrades_ItemCommand"
                                                 OnItemDataBound="RadGridTrades_ItemDataBound">

                                    <ExportSettings ExportOnlyData="True" IgnorePaging="True">
                                        <Pdf PaperSize="A4">
                                        </Pdf>
                                        <Excel Format="ExcelML" />
                                    </ExportSettings>

                                    <ClientSettings AllowColumnsReorder="True" AllowDragToGroup="True" EnableRowHoverStyle="True" EnablePostBackOnRowClick="false">
                                        <KeyboardNavigationSettings AllowSubmitOnEnter="true" />
                                        <Resizing AllowColumnResize="true"></Resizing>
                                        <Selecting AllowRowSelect="True" />
                                        <ClientEvents OnRowClick="OnRowClick" OnGridCreated="OnGridCreated" OnKeyPress="GridKeyPress" />
                                    </ClientSettings>

                                    <%-- Trades Master --%>
                                    <SortingSettings SortedBackColor="Transparent" />

                                    <MasterTableView Name="Trades" DataSourceID="SqlDataSource_Trades" HierarchyLoadMode="ServerOnDemand" EnableHierarchyExpandAll="true"
                                                     CssClass="MasterClass" EditMode="PopUp" AutoGenerateColumns="False"
                                                     DataKeyNames="SystemID,TradeGroupID,TradeID"
                                                     CommandItemDisplay="Top">

                                        <PagerStyle Mode="NextPrevAndNumeric" AlwaysVisible="true" />

                                        <SortExpressions>
                                            <telerik:GridSortExpression FieldName="TradeNumber" SortOrder="Ascending"></telerik:GridSortExpression>
                                        </SortExpressions>

                                        <CommandItemSettings ShowRefreshButton="true" ShowAddNewRecordButton="true" ShowExportToCsvButton="False" ShowExportToExcelButton="True" ShowExportToPdfButton="False"
                                                             AddNewRecordText="<%$ Resources:Resource, lblActionNew %>" RefreshText="<%$ Resources:Resource, lblActionRefresh %>" />

                                        <EditFormSettings EditFormType="AutoGenerated" CaptionDataField="NameVisible" CaptionFormatString="{0}">
                                            <PopUpSettings Modal="true" ShowCaptionInEditForm="false" ScrollBars="Auto" />
                                            <EditColumn ButtonType="ImageButton" UniqueName="EditCommandColumn2" CancelText="<%$ Resources:Resource, lblActionCancel %>" EditText="<%$ Resources:Resource, lblActionEdit %>"
                                                        UpdateText="<%$ Resources:Resource, lblActionUpdate %>" />
                                            <FormTableStyle CellPadding="3" CellSpacing="3" />
                                        </EditFormSettings>

                                        <%-- Trade Details --%>
                                        <NestedViewTemplate>
                                            <fieldset style="padding: 10px; width: 500px; margin-left: 10px; margin-bottom: 10px;">
                                                <legend style="padding: 5px; background-color: transparent;">
                                                    <b><%= Resources.Resource.lblDetailsFor%> <%# Eval("NameVisible") %></b>
                                                </legend>
                                                <table style="width: 100%;">
                                                    <tr>
                                                        <td><%= Resources.Resource.lblID%>: </td>
                                                        <td>
                                                            <asp:Label Text='<%#Eval("TradeID")%>' runat="server"></asp:Label>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td><%= Resources.Resource.lblNameVisible%>: </td>
                                                        <td>
                                                            <asp:Label Text='<%#Eval("NameVisible")%>' runat="server"></asp:Label>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td><%= Resources.Resource.lblDescriptionShort%>: </td>
                                                        <td>
                                                            <asp:Label Text='<%#Eval("DescriptionShort")%>' runat="server"></asp:Label>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td><%= Resources.Resource.lblTradeNumber%>: </td>
                                                        <td>
                                                            <asp:Label Text='<%#Eval("TradeNumber")%>' runat="server"></asp:Label>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td><%= Resources.Resource.lblCostLocation%>: </td>
                                                        <td>
                                                            <telerik:RadComboBox ID="RadComboBoxCostLocationID" DataSourceID="SqlDataSource_CostLocations" DataTextField="CostLocationNumber"
                                                                                 DataValueField="CostLocationID" Height="200px" AppendDataBoundItems="true" SelectedValue='<%# Eval("CostLocationID") %>'
                                                                                 runat="server" Enabled="false">
                                                                <Items>
                                                                    <telerik:RadComboBoxItem Text="<%$ Resources:Resource, lblAll %>" />
                                                                </Items>
                                                            </telerik:RadComboBox>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td><%= Resources.Resource.lblCreatedFrom%>: </td>
                                                        <td>
                                                            <asp:Label Text='<%#Eval("CreatedFrom")%>' runat="server"></asp:Label>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td><%= Resources.Resource.lblCreatedOn%>: </td>
                                                        <td>
                                                            <asp:Label Text='<%#Eval("CreatedOn")%>' runat="server"></asp:Label>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td><%= Resources.Resource.lblEditFrom%>: </td>
                                                        <td>
                                                            <asp:Label Text='<%#Eval("EditFrom")%>' runat="server"></asp:Label>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td><%= Resources.Resource.lblEditOn%>: </td>
                                                        <td>
                                                            <asp:Label Text='<%#Eval("EditOn")%>' runat="server"></asp:Label>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </fieldset>
                                        </NestedViewTemplate>

                                        <%-- Trade Columns --%>
                                        <Columns>
                                            <telerik:GridEditCommandColumn ButtonType="ImageButton" UniqueName="EditCommandColumn" CancelText="<%$ Resources:Resource, lblActionCancel %>" EditText="<%$ Resources:Resource, lblActionEdit %>"
                                                                           UpdateText="<%$ Resources:Resource, lblActionUpdate %>" Reorderable="false" Resizable="false">
                                                <ItemStyle BackColor="Control" Width="30px" />
                                                <HeaderStyle Width="30px" />
                                            </telerik:GridEditCommandColumn>

                                            <telerik:GridTemplateColumn DataField="TradeNumber" FilterControlAltText="Filter TradeNumber column" HeaderText="<%$ Resources:Resource, lblTradeNumber %>"
                                                                        SortExpression="TradeNumber" UniqueName="TradeNumber" GroupByExpression="TradeNumber TradeNumber GROUP BY TradeNumber">
                                                <EditItemTemplate>
                                                    <telerik:RadTextBox runat="server" ID="TradeNumber" Text='<%# Bind("TradeNumber") %>'></telerik:RadTextBox>
                                                </EditItemTemplate>
                                                <ItemTemplate>
                                                    <asp:Label runat="server" ID="LabelTradeNumber" Text='<%# Eval("TradeNumber") %>'></asp:Label>
                                                </ItemTemplate>
                                            </telerik:GridTemplateColumn>

                                            <telerik:GridTemplateColumn DataField="NameVisible" HeaderText="<%$ Resources:Resource, lblNameVisible %>" SortExpression="NameVisible" UniqueName="NameVisible"
                                                                        GroupByExpression="NameVisible NameVisible GROUP BY NameVisible">
                                                <EditItemTemplate>
                                                    <telerik:RadTextBox runat="server" ID="NameVisible" Text='<%# Bind("NameVisible") %>'></telerik:RadTextBox>
                                                </EditItemTemplate>
                                                <ItemTemplate>
                                                    <asp:Label runat="server" ID="NameVisible" Text='<%# Eval("NameVisible") %>'></asp:Label>
                                                </ItemTemplate>
                                            </telerik:GridTemplateColumn>

                                            <telerik:GridTemplateColumn DataField="DescriptionShort" FilterControlAltText="Filter DescriptionShort column" HeaderText="<%$ Resources:Resource, lblDescriptionShort %>"
                                                                        SortExpression="DescriptionShort" UniqueName="DescriptionShort" GroupByExpression="DescriptionShort DescriptionShort GROUP BY DescriptionShort">
                                                <EditItemTemplate>
                                                    <telerik:RadTextBox runat="server" ID="DescriptionShort" Text='<%# Bind("DescriptionShort") %>' Width="300px"></telerik:RadTextBox>
                                                </EditItemTemplate>
                                                <ItemTemplate>
                                                    <asp:Label runat="server" ID="LabelDescriptionShort" Text='<%# Eval("DescriptionShort") %>'></asp:Label>
                                                </ItemTemplate>
                                            </telerik:GridTemplateColumn>

                                            <telerik:GridDropDownColumn DataField="CostLocationID" DataSourceID="SqlDataSource_CostLocations" HeaderText="<%$ Resources:Resource, lblCostLocation %>" ListTextField="CostLocationNumber"
                                                                        ListValueField="CostLocationID" UniqueName="CostLocationID" DropDownControlType="RadComboBox">
                                                <FilterTemplate>
                                                    <telerik:RadComboBox ID="RadComboBoxCostLocationID" DataSourceID="SqlDataSource_CostLocations" DataTextField="CostLocationNumber"
                                                                         DataValueField="CostLocationID" Height="200px" AppendDataBoundItems="true" SelectedValue='<%# ((GridItem)Container).OwnerTableView.GetColumn("CostLocationID").CurrentFilterValue %>'
                                                                         runat="server" OnClientSelectedIndexChanged="CostLocationIDIndexChanged">
                                                        <Items>
                                                            <telerik:RadComboBoxItem Text="<%$ Resources:Resource, lblAll %>" />
                                                        </Items>
                                                    </telerik:RadComboBox>
                                                    <telerik:RadScriptBlock ID="RadScriptBlock2" runat="server">
                                                        <script type="text/javascript">
                                                            function CostLocationIDIndexChanged(sender, args) {
                                                                var tableView = $find("<%# ((GridItem)Container).OwnerTableView.ClientID %>");
                                                                tableView.filter("CostLocationID", args.get_item().get_value(), "EqualTo");
                                                            }
                                                        </script>
                                                    </telerik:RadScriptBlock>
                                                </FilterTemplate>
                                            </telerik:GridDropDownColumn>

                                            <telerik:GridTemplateColumn DataField="CreatedFrom" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter CreatedFrom column" HeaderText="<%$ Resources:Resource, lblCreatedFrom %>" SortExpression="CreatedFrom" UniqueName="CreatedFrom" Visible="False">
                                                <ItemTemplate>
                                                    <asp:Label ID="CreatedFromLabel" runat="server" Text='<%# Eval("CreatedFrom")%>'></asp:Label>
                                                </ItemTemplate>
                                            </telerik:GridTemplateColumn>

                                            <telerik:GridTemplateColumn DataField="CreatedOn" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter CreatedOn column" HeaderText="<%$ Resources:Resource, lblCreatedOn %>" SortExpression="CreatedOn" UniqueName="CreatedOn" Visible="False">
                                                <ItemTemplate>
                                                    <asp:Label ID="CreatedOnLabel" runat="server" Text='<%# Eval("CreatedOn")%>'></asp:Label>
                                                </ItemTemplate>
                                            </telerik:GridTemplateColumn>

                                            <telerik:GridTemplateColumn DataField="EditFrom" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter EditFrom column" HeaderText="<%$ Resources:Resource, lblEditFrom %>" SortExpression="EditFrom" UniqueName="EditFrom" Visible="False">
                                                <ItemTemplate>
                                                    <asp:Label ID="EditFromLabel" runat="server" Text='<%# Eval("EditFrom")%>'></asp:Label>
                                                </ItemTemplate>
                                            </telerik:GridTemplateColumn>

                                            <telerik:GridTemplateColumn DataField="EditOn" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter EditOn column" HeaderText="<%$ Resources:Resource, lblEditOn %>" SortExpression="EditOn" UniqueName="EditOn" Visible="False">
                                                <ItemTemplate>
                                                    <asp:Label ID="EditOnLabel" runat="server" Text='<%# Eval("EditOn") %>'></asp:Label>
                                                </ItemTemplate>
                                            </telerik:GridTemplateColumn>

                                            <telerik:GridButtonColumn UniqueName="deleteColumn1" Visible="true" ConfirmText="<%$ Resources:Resource, qstDeleteRow %>" Text="<%$ Resources:Resource, lblActionDelete %>" 
                                                                      ConfirmDialogType="RadWindow"
                                                                      ConfirmTitle="<%$ Resources:Resource, lblActionDelete %>" ButtonType="ImageButton" CommandName="Delete" HeaderStyle-Width="30px" ItemStyle-Width="30px">
                                                <ItemStyle BackColor="Control" />
                                            </telerik:GridButtonColumn>
                                        </Columns>
                                    </MasterTableView>
                                </telerik:RadGrid>

                                <asp:SqlDataSource ID="SqlDataSource_Trades" runat="server" ConnectionString="<%$ ConnectionStrings:Insite_Dev_ConnectionString %>" OnInserted="SqlDataSource_Inserted"
                                                   OldValuesParameterFormatString="original_{0}"
                                                   DeleteCommand="INSERT INTO History_S_TradesStatistical SELECT * FROM System_TradesStatistical WHERE [SystemID] = @original_SystemID AND (TradeGroupID = @original_TradeGroupID) AND (TradeID = @original_TradeID); 
                                                   DELETE FROM System_TradesStatistical WHERE (SystemID = @original_SystemID) AND (TradeGroupID = @original_TradeGroupID) AND (TradeID = @original_TradeID)"
                                                   InsertCommand="INSERT INTO System_TradesStatistical(SystemID, TradeGroupID, NameVisible, DescriptionShort, TradeNumber, CostLocationID, CreatedFrom, CreatedOn, EditFrom, EditOn) VALUES (@SystemID, @TradeGroupID, @NameVisible, @DescriptionShort, @TradeNumber, @CostLocationID, @UserName, SYSDATETIME(), @UserName, SYSDATETIME()) 
                                                   SELECT @ReturnValue = SCOPE_IDENTITY()"
                                                   SelectCommand="SELECT * FROM System_TradesStatistical WHERE (SystemID = @SystemID) AND (TradeGroupID = @TradeGroupID) ORDER BY TradeNumber"
                                                   UpdateCommand="INSERT INTO History_S_TradesStatistical SELECT * FROM System_TradesStatistical WHERE [SystemID] = @original_SystemID AND (TradeGroupID = @original_TradeGroupID) AND (TradeID = @original_TradeID); 
                                                   UPDATE System_TradesStatistical SET NameVisible = @NameVisible, DescriptionShort = @DescriptionShort, TradeNumber = @TradeNumber, CostLocationID = @CostLocationID, EditFrom = @UserName, EditOn = SYSDATETIME() WHERE (SystemID = @original_SystemID) AND (TradeGroupID = @original_TradeGroupID) AND (TradeID = @original_TradeID)">
                                    <DeleteParameters>
                                        <asp:Parameter Name="original_SystemID" />
                                        <asp:Parameter Name="original_TradeGroupID" />
                                        <asp:Parameter Name="original_TradeID" />
                                    </DeleteParameters>
                                    <InsertParameters>
                                        <asp:SessionParameter DefaultValue="0" Name="SystemID" SessionField="SystemID" />
                                        <asp:ControlParameter ControlID="TradeGroupID" PropertyName="Value" Type="Int32" Name="TradeGroupID"></asp:ControlParameter>
                                        <asp:Parameter Name="NameVisible" />
                                        <asp:Parameter Name="DescriptionShort" />
                                        <asp:Parameter Name="TradeNumber" />
                                        <asp:Parameter Name="CostLocationID" />
                                        <asp:SessionParameter DefaultValue="" Name="UserName" SessionField="LoginName" Type="String" />
                                        <asp:Parameter Direction="Output" Name="ReturnValue" Type="Int32" />
                                    </InsertParameters>
                                    <SelectParameters>
                                        <asp:SessionParameter DefaultValue="0" Name="SystemID" SessionField="SystemID" />
                                        <asp:ControlParameter ControlID="TradeGroupID" PropertyName="Value" Type="Int32" Name="TradeGroupID"></asp:ControlParameter>
                                    </SelectParameters>
                                    <UpdateParameters>
                                        <asp:Parameter Name="NameVisible" />
                                        <asp:Parameter Name="DescriptionShort" />
                                        <asp:Parameter Name="TradeNumber" />
                                        <asp:Parameter Name="CostLocationID" />
                                        <asp:Parameter Name="original_SystemID" />
                                        <asp:Parameter Name="original_TradeGroupID" />
                                        <asp:Parameter Name="original_TradeID" />
                                        <asp:SessionParameter DefaultValue="" Name="UserName" SessionField="LoginName" Type="String" />
                                    </UpdateParameters>
                                </asp:SqlDataSource>

                                <asp:SqlDataSource ID="SqlDataSource_CostLocations" runat="server" ConnectionString="<%$ ConnectionStrings:Insite_Dev_ConnectionString %>"
                                                   SelectCommand="SELECT SystemID, CostLocationID, CostLocationNumber, NameVisible, DescriptionShort, TypeID, IsVisible, CreatedFrom, CreatedOn, EditFrom, EditOn FROM System_CostLocations WHERE (SystemID = @SystemID) ORDER BY CostLocationNumber">
                                    <SelectParameters>
                                        <asp:SessionParameter DefaultValue="0" Name="SystemID" SessionField="SystemID" />
                                    </SelectParameters>
                                </asp:SqlDataSource>
                            </telerik:RadPageView>

                            <%-- TradeGroup Details --%>
                            <telerik:RadPageView runat="server" ID="PageView1_2">
                                <fieldset style="padding: 10px; width: 500px; margin-left: 10px; margin-bottom: 10px;">
                                    <legend style="padding: 5px; background-color: transparent;">
                                        <b><%# String.Concat(Resources.Resource.lblDetailsFor, " ", Eval("NameVisible"))%></b>
                                    </legend>
                                    <table style="width: 100%;">
                                        <tr>
                                            <td><%= Resources.Resource.lblID%>: </td>
                                            <td>
                                                <asp:Label Text='<%#Eval("TradeGroupID")%>' runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><%= Resources.Resource.lblNameVisible%>: </td>
                                            <td>
                                                <asp:Label Text='<%#Eval("NameVisible")%>' runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><%= Resources.Resource.lblDescriptionShort%>: </td>
                                            <td>
                                                <asp:Label Text='<%#Eval("DescriptionShort")%>' runat="server" Width="300px"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><%= Resources.Resource.lblPosition%>: </td>
                                            <td>
                                                <asp:Label Text='<%#Eval("Position")%>' runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><%= Resources.Resource.lblPassColor%>: </td>
                                            <td>
                                                <div style='width: 50px; height: 16px; background-color: <%# Eval("PassColor") %>'></div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><%= Resources.Resource.lblCreatedFrom%>: </td>
                                            <td>
                                                <asp:Label Text='<%#Eval("CreatedFrom")%>' runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><%= Resources.Resource.lblCreatedOn%>: </td>
                                            <td>
                                                <asp:Label Text='<%#Eval("CreatedOn")%>' runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><%= Resources.Resource.lblEditFrom%>: </td>
                                            <td>
                                                <asp:Label Text='<%#Eval("EditFrom")%>' runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><%= Resources.Resource.lblEditOn%>: </td>
                                            <td>
                                                <asp:Label Text='<%#Eval("EditOn")%>' runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                    </table>
                                </fieldset>
                            </telerik:RadPageView>

                        </telerik:RadMultiPage>
                    </asp:Panel>
                </NestedViewTemplate>

                <Columns>
                    <telerik:GridEditCommandColumn ButtonType="ImageButton" UniqueName="EditCommandColumn" CancelText="<%$ Resources:Resource, lblActionCancel %>" EditText="<%$ Resources:Resource, lblActionEdit %>"
                                                   UpdateText="<%$ Resources:Resource, lblActionUpdate %>" Reorderable="false" Resizable="false">
                        <ItemStyle BackColor="Control" Width="30px" />
                        <HeaderStyle Width="30px" />
                    </telerik:GridEditCommandColumn>

                    <telerik:GridTemplateColumn DataField="TradeGroupID" Visible="false" DataType="System.Int32" FilterControlAltText="Filter TradeGroupID column" HeaderText="<%$ Resources:Resource, lblID %>"
                                                SortExpression="TradeGroupID" UniqueName="TradeGroupID" GroupByExpression="TradeGroupID TradeGroupID GROUP BY TradeGroupID">
                        <EditItemTemplate>
                            <asp:Label runat="server" ID="LabelTradeGroupID" Text='<%# Eval("TradeGroupID") %>'></asp:Label>
                        </EditItemTemplate>
                        <InsertItemTemplate>
                        </InsertItemTemplate>
                        <ItemTemplate>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="Position" DataType="System.Int32" FilterControlAltText="Filter Position column" HeaderText="<%$ Resources:Resource, lblPosition %>"
                                                SortExpression="Position" UniqueName="Position" GroupByExpression="Position Position GROUP BY Position" HeaderStyle-Width="70px" ItemStyle-Width="70px">
                        <EditItemTemplate>
                            <telerik:RadTextBox runat="server" ID="Position" Text='<%# Bind("Position") %>'></telerik:RadTextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="LabelPosition" Text='<%# Eval("Position") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="NameVisible" HeaderText="<%$ Resources:Resource, lblNameVisible %>" SortExpression="NameVisible" UniqueName="NameVisible"
                                                GroupByExpression="NameVisible NameVisible GROUP BY NameVisible">
                        <EditItemTemplate>
                            <telerik:RadTextBox runat="server" ID="NameVisible" Text='<%# Bind("NameVisible") %>'></telerik:RadTextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="NameVisible" Text='<%# Eval("NameVisible") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="DescriptionShort" FilterControlAltText="Filter DescriptionShort column" HeaderText="<%$ Resources:Resource, lblDescriptionShort %>"
                                                SortExpression="DescriptionShort" UniqueName="DescriptionShort" GroupByExpression="DescriptionShort DescriptionShort GROUP BY DescriptionShort">
                        <EditItemTemplate>
                            <telerik:RadTextBox runat="server" ID="DescriptionShort" Text='<%# Bind("DescriptionShort") %>' Width="400px"></telerik:RadTextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="LabelDescriptionShort" Text='<%# Eval("DescriptionShort") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="PassColor" FilterControlAltText="Filter PassColor column" HeaderText="<%$ Resources:Resource, lblPassColor %>"
                                                SortExpression="PassColor" UniqueName="PassColor" GroupByExpression="PassColor PassColor GROUP BY PassColor">
                        <EditItemTemplate>
                            <telerik:RadColorPicker ID="RadColorPicker1" runat="server" EnableTheming="true" ShowRecentColors="true" ShowIcon="true" EnableEmbeddedSkins="true"
                                                    SelectedColor='<%# InSite.App.Helpers.Html2Color(InSite.App.Helpers.CStr(Eval("PassColor"))) %>' PaletteModes="All" ShowEmptyColor="true" 
                                                    Width="300px">
                            </telerik:RadColorPicker>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <div style='width: 50px; height: 16px; background-color: <%# Eval("PassColor") %>'></div>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="CreatedFrom" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter CreatedFrom column" HeaderText="<%$ Resources:Resource, lblCreatedFrom %>" SortExpression="CreatedFrom" UniqueName="CreatedFrom" Visible="False">
                        <ItemTemplate>
                            <asp:Label ID="CreatedFromLabel" runat="server" Text='<%# Eval("CreatedFrom")%>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="CreatedOn" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter CreatedOn column" HeaderText="<%$ Resources:Resource, lblCreatedOn %>" SortExpression="CreatedOn" UniqueName="CreatedOn" Visible="False">
                        <ItemTemplate>
                            <asp:Label ID="CreatedOnLabel" runat="server" Text='<%# Eval("CreatedOn")%>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="EditFrom" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter EditFrom column" HeaderText="<%$ Resources:Resource, lblEditFrom %>" SortExpression="EditFrom" UniqueName="EditFrom" Visible="False">
                        <ItemTemplate>
                            <asp:Label ID="EditFromLabel" runat="server" Text='<%# Eval("EditFrom")%>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="EditOn" InsertVisiblityMode="AlwaysHidden" FilterControlAltText="Filter EditOn column" HeaderText="<%$ Resources:Resource, lblEditOn %>" SortExpression="EditOn" UniqueName="EditOn" Visible="False">
                        <ItemTemplate>
                            <asp:Label ID="EditOnLabel" runat="server" Text='<%# Eval("EditOn") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridTemplateColumn DataField="TradeGroupID" Visible="false">
                        <EditItemTemplate>
                            <br />
                            <br />
                            <br />
                            <br />
                            <br />
                            <br />
                            <br />
                            <br />
                            <br />
                            <br />
                        </EditItemTemplate>
                    </telerik:GridTemplateColumn>

                    <telerik:GridButtonColumn UniqueName="deleteColumn" Visible="true" ConfirmText="<%$ Resources:Resource, qstDeleteRow %>" Text="<%$ Resources:Resource, lblActionDelete %>" 
                                              ConfirmDialogType="RadWindow"
                                              ConfirmTitle="<%$ Resources:Resource, lblActionDelete %>" ButtonType="ImageButton" CommandName="Delete" HeaderStyle-Width="30px" ItemStyle-Width="30px">
                        <ItemStyle BackColor="Control" />
                    </telerik:GridButtonColumn>
                </Columns>
            </MasterTableView>

        </telerik:RadGrid>
    </div>

    <asp:SqlDataSource ID="SqlDataSource_TradeGroups" runat="server" ConnectionString="<%$ ConnectionStrings:Insite_Dev_ConnectionString %>" OnInserted="SqlDataSource_Inserted"
                       OldValuesParameterFormatString="original_{0}"
                       DeleteCommand="INSERT INTO History_S_TradeGroupsStatistical SELECT * FROM System_TradeGroupsStatistical WHERE [SystemID] = @original_SystemID AND (TradeGroupID = @original_TradeGroupID); 
                       DELETE FROM System_TradeGroupsStatistical WHERE (SystemID = @SystemID) AND (TradeGroupID = @TradeGroupID)"
                       InsertCommand="INSERT INTO System_TradeGroupsStatistical(SystemID, NameVisible, DescriptionShort, Position, PassColor, CreatedFrom, CreatedOn, EditFrom, EditOn) VALUES (@SystemID, @NameVisible, @DescriptionShort, @Position, @PassColor, @UserName, SYSDATETIME(), @UserName, SYSDATETIME()) 
                       SELECT @ReturnValue = SCOPE_IDENTITY()"
                       SelectCommand="SELECT * FROM System_TradeGroupsStatistical WHERE (SystemID = @SystemID) ORDER BY Position"
                       UpdateCommand="INSERT INTO History_S_TradeGroupsStatistical SELECT * FROM System_TradeGroupsStatistical WHERE [SystemID] = @original_SystemID AND (TradeGroupID = @original_TradeGroupID); 
                       UPDATE System_TradeGroupsStatistical SET NameVisible = @NameVisible, DescriptionShort = @DescriptionShort, Position = @Position, PassColor = @PassColor, EditFrom = @UserName, EditOn = SYSDATETIME() WHERE (SystemID = @original_SystemID) AND (TradeGroupID = @original_TradeGroupID)">
        <DeleteParameters>
            <asp:Parameter Name="original_SystemID" Type="String" />
            <asp:Parameter Name="original_TradeGroupID" Type="String" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="NameVisible" />
            <asp:Parameter Name="DescriptionShort" />
            <asp:Parameter Name="Position" />
            <asp:Parameter Name="PassColor" />
            <asp:SessionParameter DefaultValue="0" Name="SystemID" SessionField="SystemID" />
            <asp:SessionParameter DefaultValue="" Name="UserName" SessionField="LoginName" Type="String" />
            <asp:Parameter Direction="Output" Name="ReturnValue" Type="Int32" />
        </InsertParameters>
        <SelectParameters>
            <asp:SessionParameter DefaultValue="0" Name="SystemID" SessionField="SystemID" />
        </SelectParameters>
        <UpdateParameters>
            <asp:Parameter Name="NameVisible" />
            <asp:Parameter Name="DescriptionShort" />
            <asp:Parameter Name="Position" />
            <asp:Parameter Name="PassColor" />
            <asp:Parameter Name="original_SystemID" />
            <asp:Parameter Name="original_TradeGroupID" />
            <asp:SessionParameter DefaultValue="" Name="UserName" SessionField="LoginName" Type="String" />
        </UpdateParameters>
    </asp:SqlDataSource>
</asp:Content>
