//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    
    public partial class GetShortTermVisitors_Result
    {
        public int ShortTermVisitorID { get; set; }
        public string TypeName { get; set; }
        public string InternalID { get; set; }
        public int StatusID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Company { get; set; }
        public string CompanyName { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<System.DateTime> AccessAllowedUntil { get; set; }
        public System.DateTime EditOn { get; set; }
        public string ActivatedFrom { get; set; }
        public Nullable<System.DateTime> ActivatedOn { get; set; }
        public string DeactivatedFrom { get; set; }
        public Nullable<System.DateTime> DeactivatedOn { get; set; }
        public Nullable<System.DateTime> LastAccess { get; set; }
        public Nullable<System.DateTime> LastExit { get; set; }
        public string CreatedFrom { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string EditFrom { get; set; }
        public string Salutation { get; set; }
        public int ShortTermPassID { get; set; }
        public string IdentifiedWith { get; set; }
        public int AssignedCompanyID { get; set; }
        public int AssignedEmployeeID { get; set; }
        public int SystemID { get; set; }
        public int BpID { get; set; }
        public string DocumentID { get; set; }
        public string VisitorName { get; set; }
        public string LockedFrom { get; set; }
        public Nullable<System.DateTime> LockedOn { get; set; }
        public string NationalityID { get; set; }
        public Nullable<int> Present { get; set; }
        public Nullable<System.DateTime> AccessTime { get; set; }
    }
}
