//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    
    public partial class GetEmployeesDropDown_Result
    {
        public int SystemID { get; set; }
        public int BpID { get; set; }
        public int EmployeeID { get; set; }
        public int CompanyID { get; set; }
        public string Description { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string NameVisible { get; set; }
        public string NameAdditional { get; set; }
        public int StatusID { get; set; }
        public string TradeName { get; set; }
        public string EmployeeName { get; set; }
    }
}
