//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    
    public partial class GetCompaniesCentralNotAddedToBp_Result
    {
        public int SystemID { get; set; }
        public int BpID { get; set; }
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
    }
}
