//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    
    public partial class GetAccessAreaEvents_Result
    {
        public int SystemID { get; set; }
        public int BpID { get; set; }
        public int AccessRightEventID { get; set; }
        public int AccessAreaEventID { get; set; }
        public int AccessAreaID { get; set; }
        public int TimeSlotID { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidUntil { get; set; }
        public string ValidDays { get; set; }
        public Nullable<System.TimeSpan> TimeFrom { get; set; }
        public Nullable<System.TimeSpan> TimeUntil { get; set; }
        public int AdditionalRights { get; set; }
        public string AccessAreaName { get; set; }
        public string TimeSlotName { get; set; }
    }
}
