//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadEditor {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder-Klasse
    // mit einem Tool wie ResGen oder Visual Studio automatisch generiert.
    // Bearbeiten Sie zum Hinzufügen oder Entfernen eines Members die RESX-Datei, und führen Sie dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen das Visual Studio-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tools {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tools() {
        }
        
        /// <summary>
        ///   Gibt die von dieser Klasse verwendete zwischengespeicherte ResourceManager-Instanz zurück.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadEditor.Tools", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenlookups, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About RadEditor ähnelt.
        /// </summary>
        internal static string AboutDialog {
            get {
                return ResourceManager.GetString("AboutDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set Absolute Position ähnelt.
        /// </summary>
        internal static string AbsolutePosition {
            get {
                return ResourceManager.GetString("AbsolutePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AJAX Spellchecker ähnelt.
        /// </summary>
        internal static string AjaxSpellCheck {
            get {
                return ResourceManager.GetString("AjaxSpellCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alignment selector ähnelt.
        /// </summary>
        internal static string AlignmentSelector {
            get {
                return ResourceManager.GetString("AlignmentSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply CSS Class ähnelt.
        /// </summary>
        internal static string ApplyClass {
            get {
                return ResourceManager.GetString("ApplyClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Background Color ähnelt.
        /// </summary>
        internal static string BackColor {
            get {
                return ResourceManager.GetString("BackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bold ähnelt.
        /// </summary>
        internal static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cell Border ähnelt.
        /// </summary>
        internal static string CellBorder {
            get {
                return ResourceManager.GetString("CellBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clipboard ähnelt.
        /// </summary>
        internal static string Clipboard {
            get {
                return ResourceManager.GetString("Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ColorPicker ähnelt.
        /// </summary>
        internal static string ColorPicker {
            get {
                return ResourceManager.GetString("ColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Content ähnelt.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Convert to lower case ähnelt.
        /// </summary>
        internal static string ConvertToLower {
            get {
                return ResourceManager.GetString("ConvertToLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Convert to upper case ähnelt.
        /// </summary>
        internal static string ConvertToUpper {
            get {
                return ResourceManager.GetString("ConvertToUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy ähnelt.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compliance Check ähnelt.
        /// </summary>
        internal static string CSDialog {
            get {
                return ResourceManager.GetString("CSDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cut ähnelt.
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decrease Size ähnelt.
        /// </summary>
        internal static string DecreaseSize {
            get {
                return ResourceManager.GetString("DecreaseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Cell ähnelt.
        /// </summary>
        internal static string DeleteCell {
            get {
                return ResourceManager.GetString("DeleteCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Column ähnelt.
        /// </summary>
        internal static string DeleteColumn {
            get {
                return ResourceManager.GetString("DeleteColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Row ähnelt.
        /// </summary>
        internal static string DeleteRow {
            get {
                return ResourceManager.GetString("DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Table ähnelt.
        /// </summary>
        internal static string DeleteTable {
            get {
                return ResourceManager.GetString("DeleteTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string DeleteTableItems {
            get {
                return ResourceManager.GetString("DeleteTableItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Document Manager ähnelt.
        /// </summary>
        internal static string DocumentManager {
            get {
                return ResourceManager.GetString("DocumentManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Content ähnelt.
        /// </summary>
        internal static string EditContent {
            get {
                return ResourceManager.GetString("EditContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Editing ähnelt.
        /// </summary>
        internal static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter Pressed ähnelt.
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Find And Replace ähnelt.
        /// </summary>
        internal static string FindAndReplace {
            get {
                return ResourceManager.GetString("FindAndReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flash Manager ähnelt.
        /// </summary>
        internal static string FlashManager {
            get {
                return ResourceManager.GetString("FlashManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Font ähnelt.
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Font Name ähnelt.
        /// </summary>
        internal static string FontName {
            get {
                return ResourceManager.GetString("FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Size ähnelt.
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Foreground Color ähnelt.
        /// </summary>
        internal static string ForeColor {
            get {
                return ResourceManager.GetString("ForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paragraph Style ähnelt.
        /// </summary>
        internal static string FormatBlock {
            get {
                return ResourceManager.GetString("FormatBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Format Code Block ähnelt.
        /// </summary>
        internal static string FormatCodeBlock {
            get {
                return ResourceManager.GetString("FormatCodeBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Format Painter ähnelt.
        /// </summary>
        internal static string FormatPainter {
            get {
                return ResourceManager.GetString("FormatPainter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply Format ähnelt.
        /// </summary>
        internal static string FormatPainterApply {
            get {
                return ResourceManager.GetString("FormatPainterApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear Format ähnelt.
        /// </summary>
        internal static string FormatPainterClear {
            get {
                return ResourceManager.GetString("FormatPainterClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy Format ähnelt.
        /// </summary>
        internal static string FormatPainterCopy {
            get {
                return ResourceManager.GetString("FormatPainterCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Format Sets ähnelt.
        /// </summary>
        internal static string FormatSets {
            get {
                return ResourceManager.GetString("FormatSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Format Stripper ähnelt.
        /// </summary>
        internal static string FormatStripper {
            get {
                return ResourceManager.GetString("FormatStripper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image Border ähnelt.
        /// </summary>
        internal static string ImageBorder {
            get {
                return ResourceManager.GetString("ImageBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image Editor ähnelt.
        /// </summary>
        internal static string ImageEditor {
            get {
                return ResourceManager.GetString("ImageEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image Manager ähnelt.
        /// </summary>
        internal static string ImageManager {
            get {
                return ResourceManager.GetString("ImageManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image Map Editor ähnelt.
        /// </summary>
        internal static string ImageMapDialog {
            get {
                return ResourceManager.GetString("ImageMapDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Size and Margins ähnelt.
        /// </summary>
        internal static string ImageSizeMargins {
            get {
                return ResourceManager.GetString("ImageSizeMargins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increase Size ähnelt.
        /// </summary>
        internal static string IncreaseSize {
            get {
                return ResourceManager.GetString("IncreaseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Indent ähnelt.
        /// </summary>
        internal static string Indent {
            get {
                return ResourceManager.GetString("Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert ähnelt.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Anchor ähnelt.
        /// </summary>
        internal static string InsertAnchor {
            get {
                return ResourceManager.GetString("InsertAnchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Column to the Left ähnelt.
        /// </summary>
        internal static string InsertColumnLeft {
            get {
                return ResourceManager.GetString("InsertColumnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Column to the Right ähnelt.
        /// </summary>
        internal static string InsertColumnRight {
            get {
                return ResourceManager.GetString("InsertColumnRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom Links ähnelt.
        /// </summary>
        internal static string InsertCustomLink {
            get {
                return ResourceManager.GetString("InsertCustomLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Date ähnelt.
        /// </summary>
        internal static string InsertDate {
            get {
                return ResourceManager.GetString("InsertDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Email Link ähnelt.
        /// </summary>
        internal static string InsertEmailLink {
            get {
                return ResourceManager.GetString("InsertEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert External Video ähnelt.
        /// </summary>
        internal static string InsertExternalVideo {
            get {
                return ResourceManager.GetString("InsertExternalVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Button ähnelt.
        /// </summary>
        internal static string InsertFormButton {
            get {
                return ResourceManager.GetString("InsertFormButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Checkbox ähnelt.
        /// </summary>
        internal static string InsertFormCheckbox {
            get {
                return ResourceManager.GetString("InsertFormCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Form Element ähnelt.
        /// </summary>
        internal static string InsertFormElement {
            get {
                return ResourceManager.GetString("InsertFormElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Form ähnelt.
        /// </summary>
        internal static string InsertFormForm {
            get {
                return ResourceManager.GetString("InsertFormForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Hidden ähnelt.
        /// </summary>
        internal static string InsertFormHidden {
            get {
                return ResourceManager.GetString("InsertFormHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Password ähnelt.
        /// </summary>
        internal static string InsertFormPassword {
            get {
                return ResourceManager.GetString("InsertFormPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Radio ähnelt.
        /// </summary>
        internal static string InsertFormRadio {
            get {
                return ResourceManager.GetString("InsertFormRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Reset ähnelt.
        /// </summary>
        internal static string InsertFormReset {
            get {
                return ResourceManager.GetString("InsertFormReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Select ähnelt.
        /// </summary>
        internal static string InsertFormSelect {
            get {
                return ResourceManager.GetString("InsertFormSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Submit ähnelt.
        /// </summary>
        internal static string InsertFormSubmit {
            get {
                return ResourceManager.GetString("InsertFormSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Textbox ähnelt.
        /// </summary>
        internal static string InsertFormText {
            get {
                return ResourceManager.GetString("InsertFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Textarea ähnelt.
        /// </summary>
        internal static string InsertFormTextarea {
            get {
                return ResourceManager.GetString("InsertFormTextarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Groupbox ähnelt.
        /// </summary>
        internal static string InsertGroupbox {
            get {
                return ResourceManager.GetString("InsertGroupbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Horizontal Rule ähnelt.
        /// </summary>
        internal static string InsertHorizontalRule {
            get {
                return ResourceManager.GetString("InsertHorizontalRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Image ähnelt.
        /// </summary>
        internal static string InsertImage {
            get {
                return ResourceManager.GetString("InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Link ähnelt.
        /// </summary>
        internal static string InsertLink {
            get {
                return ResourceManager.GetString("InsertLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Numbered List ähnelt.
        /// </summary>
        internal static string InsertOrderedList {
            get {
                return ResourceManager.GetString("InsertOrderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Paragraph ähnelt.
        /// </summary>
        internal static string InsertParagraph {
            get {
                return ResourceManager.GetString("InsertParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Row Above ähnelt.
        /// </summary>
        internal static string InsertRowAbove {
            get {
                return ResourceManager.GetString("InsertRowAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Row Below ähnelt.
        /// </summary>
        internal static string InsertRowBelow {
            get {
                return ResourceManager.GetString("InsertRowBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Code Snippet ähnelt.
        /// </summary>
        internal static string InsertSnippet {
            get {
                return ResourceManager.GetString("InsertSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Symbol ähnelt.
        /// </summary>
        internal static string InsertSymbol {
            get {
                return ResourceManager.GetString("InsertSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Table ähnelt.
        /// </summary>
        internal static string InsertTable {
            get {
                return ResourceManager.GetString("InsertTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Table ähnelt.
        /// </summary>
        internal static string InsertTableDialog {
            get {
                return ResourceManager.GetString("InsertTableDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert ähnelt.
        /// </summary>
        internal static string InsertTableItems {
            get {
                return ResourceManager.GetString("InsertTableItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Table ähnelt.
        /// </summary>
        internal static string InsertTableLight {
            get {
                return ResourceManager.GetString("InsertTableLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Time ähnelt.
        /// </summary>
        internal static string InsertTime {
            get {
                return ResourceManager.GetString("InsertTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bullet List ähnelt.
        /// </summary>
        internal static string InsertUnorderedList {
            get {
                return ResourceManager.GetString("InsertUnorderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Italic ähnelt.
        /// </summary>
        internal static string Italic {
            get {
                return ResourceManager.GetString("Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Align Center ähnelt.
        /// </summary>
        internal static string JustifyCenter {
            get {
                return ResourceManager.GetString("JustifyCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Justify ähnelt.
        /// </summary>
        internal static string JustifyFull {
            get {
                return ResourceManager.GetString("JustifyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Align Left ähnelt.
        /// </summary>
        internal static string JustifyLeft {
            get {
                return ResourceManager.GetString("JustifyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove alignment ähnelt.
        /// </summary>
        internal static string JustifyNone {
            get {
                return ResourceManager.GetString("JustifyNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Align Right ähnelt.
        /// </summary>
        internal static string JustifyRight {
            get {
                return ResourceManager.GetString("JustifyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hyperlink Manager ähnelt.
        /// </summary>
        internal static string LinkManager {
            get {
                return ResourceManager.GetString("LinkManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Links ähnelt.
        /// </summary>
        internal static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Media ähnelt.
        /// </summary>
        internal static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Media Manager ähnelt.
        /// </summary>
        internal static string MediaManager {
            get {
                return ResourceManager.GetString("MediaManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Merge Cells Horizontally ähnelt.
        /// </summary>
        internal static string MergeColumns {
            get {
                return ResourceManager.GetString("MergeColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Merge Cells Vertically ähnelt.
        /// </summary>
        internal static string MergeRows {
            get {
                return ResourceManager.GetString("MergeRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Merge and Split Cells ähnelt.
        /// </summary>
        internal static string MergeSplitCells {
            get {
                return ResourceManager.GetString("MergeSplitCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        internal static string MobileEdit {
            get {
                return ResourceManager.GetString("MobileEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Table Properties ähnelt.
        /// </summary>
        internal static string MobileTableProperties {
            get {
                return ResourceManager.GetString("MobileTableProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Module Manager ähnelt.
        /// </summary>
        internal static string ModuleManager {
            get {
                return ResourceManager.GetString("ModuleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Outdent ähnelt.
        /// </summary>
        internal static string Outdent {
            get {
                return ResourceManager.GetString("Outdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Page Properties ähnelt.
        /// </summary>
        internal static string PageProperties {
            get {
                return ResourceManager.GetString("PageProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paragraph ähnelt.
        /// </summary>
        internal static string Paragraph {
            get {
                return ResourceManager.GetString("Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paste ähnelt.
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paste As Html ähnelt.
        /// </summary>
        internal static string PasteAsHtml {
            get {
                return ResourceManager.GetString("PasteAsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paste from Word ähnelt.
        /// </summary>
        internal static string PasteFromWord {
            get {
                return ResourceManager.GetString("PasteFromWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paste from Word, strip font ähnelt.
        /// </summary>
        internal static string PasteFromWordNoFontsNoSizes {
            get {
                return ResourceManager.GetString("PasteFromWordNoFontsNoSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paste Html ähnelt.
        /// </summary>
        internal static string PasteHtml {
            get {
                return ResourceManager.GetString("PasteHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paste Markdown ähnelt.
        /// </summary>
        internal static string PasteMarkdown {
            get {
                return ResourceManager.GetString("PasteMarkdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paste Plain Text ähnelt.
        /// </summary>
        internal static string PastePlainText {
            get {
                return ResourceManager.GetString("PastePlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paste Options ähnelt.
        /// </summary>
        internal static string PasteStrip {
            get {
                return ResourceManager.GetString("PasteStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preferences ähnelt.
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Print ähnelt.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Proofing ähnelt.
        /// </summary>
        internal static string Proofing {
            get {
                return ResourceManager.GetString("Proofing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Real font size ähnelt.
        /// </summary>
        internal static string RealFontSize {
            get {
                return ResourceManager.GetString("RealFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Redo ähnelt.
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repeat Last Command ähnelt.
        /// </summary>
        internal static string RepeatLastCommand {
            get {
                return ResourceManager.GetString("RepeatLastCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please, do not delete this string. RadEditor needs it to determine if an external resource file is present in App_GlobalResources. ähnelt.
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Review ähnelt.
        /// </summary>
        internal static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select All ähnelt.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cell Properties ähnelt.
        /// </summary>
        internal static string SetCellProperties {
            get {
                return ResourceManager.GetString("SetCellProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Properties... ähnelt.
        /// </summary>
        internal static string SetImageProperties {
            get {
                return ResourceManager.GetString("SetImageProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Properties... ähnelt.
        /// </summary>
        internal static string SetLinkProperties {
            get {
                return ResourceManager.GetString("SetLinkProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Table Properties ähnelt.
        /// </summary>
        internal static string SetTableProperties {
            get {
                return ResourceManager.GetString("SetTableProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Silverlight Manager ähnelt.
        /// </summary>
        internal static string SilverlightManager {
            get {
                return ResourceManager.GetString("SilverlightManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Size and Margins ähnelt.
        /// </summary>
        internal static string SizeMargins {
            get {
                return ResourceManager.GetString("SizeMargins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spellchecker ähnelt.
        /// </summary>
        internal static string SpellCheck {
            get {
                return ResourceManager.GetString("SpellCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Split Cell Vertically ähnelt.
        /// </summary>
        internal static string SplitCell {
            get {
                return ResourceManager.GetString("SplitCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Split Cell Horizontally ähnelt.
        /// </summary>
        internal static string SplitCellHorizontal {
            get {
                return ResourceManager.GetString("SplitCellHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Strikethrough ähnelt.
        /// </summary>
        internal static string StrikeThrough {
            get {
                return ResourceManager.GetString("StrikeThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Strip All Formatting ähnelt.
        /// </summary>
        internal static string StripAll {
            get {
                return ResourceManager.GetString("StripAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Strip Css Formatting ähnelt.
        /// </summary>
        internal static string StripCss {
            get {
                return ResourceManager.GetString("StripCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Strip Font Elements ähnelt.
        /// </summary>
        internal static string StripFont {
            get {
                return ResourceManager.GetString("StripFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Strip Span Elements ähnelt.
        /// </summary>
        internal static string StripSpan {
            get {
                return ResourceManager.GetString("StripSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Strip Word Formatting ähnelt.
        /// </summary>
        internal static string StripWord {
            get {
                return ResourceManager.GetString("StripWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Style Builder ähnelt.
        /// </summary>
        internal static string StyleBuilder {
            get {
                return ResourceManager.GetString("StyleBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Styles ähnelt.
        /// </summary>
        internal static string Styles {
            get {
                return ResourceManager.GetString("Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subscript ähnelt.
        /// </summary>
        internal static string Subscript {
            get {
                return ResourceManager.GetString("Subscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SuperScript ähnelt.
        /// </summary>
        internal static string Superscript {
            get {
                return ResourceManager.GetString("Superscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Table Border ähnelt.
        /// </summary>
        internal static string TableBorder {
            get {
                return ResourceManager.GetString("TableBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tables ähnelt.
        /// </summary>
        internal static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Table Wizard ähnelt.
        /// </summary>
        internal static string TableWizard {
            get {
                return ResourceManager.GetString("TableWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Template Manager ähnelt.
        /// </summary>
        internal static string TemplateManager {
            get {
                return ResourceManager.GetString("TemplateManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dock all Floating Toolbars/Modules ähnelt.
        /// </summary>
        internal static string ToggleDocking {
            get {
                return ResourceManager.GetString("ToggleDocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle Edit Mode ähnelt.
        /// </summary>
        internal static string ToggleEditMode {
            get {
                return ResourceManager.GetString("ToggleEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle Floating Toolbar ähnelt.
        /// </summary>
        internal static string ToggleFloatingToolbar {
            get {
                return ResourceManager.GetString("ToggleFloatingToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle Full Screen Mode ähnelt.
        /// </summary>
        internal static string ToggleScreenMode {
            get {
                return ResourceManager.GetString("ToggleScreenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show/Hide Border ähnelt.
        /// </summary>
        internal static string ToggleTableBorder {
            get {
                return ResourceManager.GetString("ToggleTableBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Underline ähnelt.
        /// </summary>
        internal static string Underline {
            get {
                return ResourceManager.GetString("Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Undo ähnelt.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Link ähnelt.
        /// </summary>
        internal static string Unlink {
            get {
                return ResourceManager.GetString("Unlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View ähnelt.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XHTML Validator ähnelt.
        /// </summary>
        internal static string XhtmlValidator {
            get {
                return ResourceManager.GetString("XhtmlValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom ähnelt.
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
