//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_TimeSlots
    {
        public int SystemID { get; set; }
        public int BpID { get; set; }
        public int TimeSlotGroupID { get; set; }
        public int TimeSlotID { get; set; }
        public string NameVisible { get; set; }
        public string DescriptionShort { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidUntil { get; set; }
        public string ValidDays { get; set; }
        public Nullable<System.TimeSpan> TimeFrom { get; set; }
        public Nullable<System.TimeSpan> TimeUntil { get; set; }
        public string CreatedFrom { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string EditFrom { get; set; }
        public System.DateTime EditOn { get; set; }
    }
}
