//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Systems
    {
        public int SystemID { get; set; }
        public string NameVisible { get; set; }
        public string DescriptionShort { get; set; }
        public bool IsActive { get; set; }
        public bool IsMainSystem { get; set; }
        public Nullable<System.DateTime> LastBackup { get; set; }
    }
}
