//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsiteServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Variables
    {
        public int SystemID { get; set; }
        public int FieldID { get; set; }
        public string VariableName { get; set; }
        public string VariablePattern { get; set; }
        public int VariableType { get; set; }
        public string VariableValue { get; set; }
        public string ResourceID { get; set; }
        public string FormatPattern { get; set; }
    }
}
